// adapters/svelte/src/components/SafeAreaView.svelte
<script lang="ts" module>
  // SafeAreaView primitive. A plain view whose native side insets its children to the safe area
  // (notch, rounded corners, system bars). There is no JS-side translation; RN just renders the
  // native RCTSafeAreaView and lets the host do the inset math, so this maps style + children
  // straight onto the intrinsic — same object-bag pattern as View.svelte.
  import type { ISafeAreaViewProps } from './safe-area-view-props';

  export type { ISafeAreaViewProps };
</script>

<script lang="ts">
  import { dlog } from '@symbiote-native/engine';
  import { resolveAccessibilityProps } from '@symbiote-native/components';

  import { createAttachmentsSync } from '../runes/attachments';
  import type { ShimElement } from '../dom-shim';

  let { children, ...rest }: ISafeAreaViewProps = $props();

  dlog('SafeAreaView -> SafeAreaView');

  const bag = $derived(resolveAccessibilityProps(rest));

  // See View.svelte's note on `{@attach}`.
  let hostShim = $state.raw<ShimElement | null>(null);
  const syncAttachments = createAttachmentsSync();
  $effect(() => {
    syncAttachments(hostShim, rest);
  });
</script>

<symbiote-safe-area-view p={bag} bind:this={hostShim}>
  {@render children?.()}
</symbiote-safe-area-view>

// adapters/react/src/components/safe-area-view/index.ts
// SafeAreaView primitive. A plain view whose native side insets its children to
// the safe area (notch, rounded corners, system bars). There is no JS-side
// translation; RN just renders the native RCTSafeAreaView and lets the host do
// the inset math, so this maps style + children straight onto the intrinsic.

import { createElement, type FC, type ReactNode } from 'react';
import { dlog, type ISymbioteEvent } from '@symbiote/engine';
import {
  resolveAccessibilityProps,
  type IAccessibilityProps,
  type IAriaProps,
} from '@symbiote/components';
import type { IStyleProp, IViewStyle } from '../../utils/styles';

export interface ISafeAreaViewProps extends IAccessibilityProps, IAriaProps {
  style?: IStyleProp<IViewStyle>;
  children?: ReactNode;
  onLayout?: (event: ISymbioteEvent) => void;
}

export const SafeAreaView: FC<ISafeAreaViewProps> = rawProps => {
  // Owns its host element (symbiote-safe-area-view), so it folds aria/role here;
  // the resolved accessibility* surface rides the node via `...accessibilityRest`.
  const props = resolveAccessibilityProps(rawProps);
  const { style, children, onLayout, ...accessibilityRest } = props;

  dlog('SafeAreaView -> SafeAreaView');

  const nodeProps: Record<string, unknown> = { ...accessibilityRest, style };
  if (onLayout !== undefined) nodeProps.onLayout = onLayout;

  return createElement('symbiote-safe-area-view', nodeProps, children);
};
