// adapters/solid/src/render.ts
// Mount a Solid app onto a Fabric surface. The native host hands us a rootTag; we create a surface
// for it and let Solid's universal renderer drive the engine, which commits into
// nativeFabricUIManager — RN's own renderer never in the path.

import {
  createSurface,
  disposeRoot,
  dlog,
  type IRootTag,
  type SymbioteSurface,
} from '@symbiote-native/engine';
import type { Component } from 'solid-js';
import { createComponent, render, setActiveSurface } from './renderer';

// One Solid root per surface, so a surface can be torn down (unmount) or cleanly re-mounted on the
// same rootTag: the bridgeless host stops and restarts a surface on Fast Refresh and on
// lifecycle/focus changes, reusing the rootTag. The value is Solid's own dispose function — the
// whole reactive root goes with it, effects and cleanups included.
const roots = new Map<IRootTag, () => void>();

function teardown(rootTag: IRootTag): void {
  const dispose = roots.get(rootTag);
  if (dispose === undefined) return;
  dispose();
  roots.delete(rootTag);
  // Cleared AFTER dispose() on purpose: disposing runs user cleanups, which can still mutate the
  // tree, and those mutations should reach the surface they belong to rather than be dropped by
  // renderer.ts's post-unmount guard.
  setActiveSurface(undefined);
  disposeRoot(rootTag);
}

export function mount(
  rootTag: IRootTag,
  RootComponent: Component,
): SymbioteSurface {
  // A re-mount on a live rootTag starts clean; otherwise the stale root double-drives the surface.
  teardown(rootTag);

  const surface = createSurface(rootTag);
  setActiveSurface(surface);

  // `createComponent(RootComponent, {})` is exactly what compiled JSX emits for `<RootComponent />`
  // — written by hand here because this file is plain TS, deliberately: render.ts is the one module
  // an app's entry point imports before any JSX has been compiled, so keeping it JSX-free means it
  // needs no Babel pass of its own.
  //
  // The surface IS the render container: a top-level insert routes to surface.appendChild
  // (renderer.ts's insertNode), and the engine wraps surface.children in its synthetic flex root.
  const dispose = render(() => createComponent(RootComponent, {}), surface);
  roots.set(rootTag, dispose);

  return surface;
}

// Tear down a surface by rootTag: the public pair of `mount`, and the JS half of the bridgeless
// `RN$stopSurface` contract (see installStopSurfaceGlobal below).
export function unmount(rootTag: IRootTag): void {
  dlog(`solid unmount root=${rootTag}`);
  teardown(rootTag);
}

// `global.RN$stopSurface` is the JSI hook C++ AppRegistryBinding::stopSurface calls to stop a Fabric
// surface. RN installs it from its own renderer; symbiote REPLACES that renderer, so without this
// the binding throws "Global was not installed" on every surface stop (Fast Refresh,
// focus/lifecycle) and the screen goes blank. Same contract as every other adapter: an app uses one
// adapter, so exactly one installer runs.
declare global {
  var RN$stopSurface: ((surfaceId: number) => void) | undefined;
}

function installStopSurfaceGlobal(): void {
  globalThis.RN$stopSurface = (surfaceId: number): void => {
    unmount(surfaceId);
  };
  dlog('installed global.RN$stopSurface');
}

installStopSurfaceGlobal();

// adapters/react/src/render.ts
// Mount a React element tree onto a Fabric surface. The native host hands us a
// rootTag (via AppRegistry.registerRunnable); we create a surface for it and let
// the reconciler drive shared, which commits into nativeFabricUIManager.

import type { ReactNode } from 'react';
import {
  createSurface,
  disposeRoot,
  setEventDispatcher,
  dlog,
  type IRootTag,
  type SymbioteSurface,
} from '@symbiote-native/engine';
import reconciler, { withDiscretePriority } from './host-config';
import { LegacyRoot } from './reconciler-constants';

const noop = (): void => {};

// A native event runs the listener (which may call setState) outside React's
// loop. Run it at discrete priority so the update takes the sync lane, then
// flush that work synchronously to paint the result.
setEventDispatcher(run => {
  withDiscretePriority(run);
  // @ts-expect-error flushSyncWork exists at runtime in react-reconciler 0.33
  reconciler.flushSyncWork();
});

// The reconciler container per surface, so a surface can be torn down (unmount)
// or cleanly re-mounted on the same rootTag. The bridgeless host stops and restarts a
// surface on Fast Refresh and on lifecycle/focus changes, reusing the rootTag.
type IOpaqueRoot = ReturnType<typeof reconciler.createContainer>;
const containers = new Map<IRootTag, IOpaqueRoot>();

// Unmount a surface's React tree (render null → empty completeRoot, clearing the
// native views) and drop its shared root container so a later mount on the same
// rootTag rebuilds from scratch instead of cloning the stopped surface's dead handles.
function teardown(rootTag: IRootTag): void {
  const container = containers.get(rootTag);
  if (container === undefined) return;
  // @ts-expect-error updateContainerSync exists at runtime in react-reconciler 0.33
  reconciler.updateContainerSync(null, container, null, noop);
  // @ts-expect-error flushSyncWork exists at runtime in react-reconciler 0.33
  reconciler.flushSyncWork();
  containers.delete(rootTag);
  disposeRoot(rootTag);
}

export function mount(rootTag: IRootTag, element: ReactNode): SymbioteSurface {
  // A re-mount on a live rootTag (host restarted the surface without stopping it
  // first) starts clean. Otherwise the stale container double-drives the surface.
  teardown(rootTag);

  const surface = createSurface(rootTag);

  const container = reconciler.createContainer(
    surface,
    LegacyRoot,
    null,
    false,
    null,
    'symbiote',
    noop,
    noop,
    noop,
    noop,
    null,
  );
  containers.set(rootTag, container);

  // react-reconciler 0.33 exposes updateContainerSync + flushSyncWork for an
  // immediate render/commit; @types 0.32 still lists the older updateContainer /
  // flushSync names, so these calls are type-suppressed until the types catch up.
  // @ts-expect-error updateContainerSync exists at runtime in react-reconciler 0.33
  reconciler.updateContainerSync(element, container, null, noop);
  // @ts-expect-error flushSyncWork exists at runtime in react-reconciler 0.33
  reconciler.flushSyncWork();

  return surface;
}

// Tear down a surface by rootTag, the public pair of `mount`. This is also the JS half of
// the bridgeless `RN$stopSurface` contract (see installStopSurfaceGlobal): the native
// AppRegistryBinding calls our global to stop a surface; we unmount its tree and dispose its root.
export function unmount(rootTag: IRootTag): void {
  dlog(`unmount root=${rootTag}`);
  teardown(rootTag);
}

// `global.RN$stopSurface` is the JSI hook the C++ AppRegistryBinding::stopSurface calls
// to stop a Fabric surface. RN installs it from its own renderer (ReactFabric.js:
// `global.RN$stopSurface = ReactFabric.stopSurface`). Because symbiote REPLACES RN's
// renderer, that line never runs, so without this the binding throws "Global was not
// installed" on every surface stop. Fast Refresh and focus/lifecycle changes then fail
// to tear down, the host loops start/stop, and the screen goes blank. We install our own.
declare global {
  var RN$stopSurface: ((surfaceId: number) => void) | undefined;
}

function installStopSurfaceGlobal(): void {
  globalThis.RN$stopSurface = (surfaceId: number): void => {
    unmount(surfaceId);
  };
  dlog('installed global.RN$stopSurface');
}

installStopSurfaceGlobal();
