// examples/svelte/components/ActionButton.svelte
<script lang="ts">
  // Drop-in replacement for RN's stock <Button> — a bare Button renders as unstyled tinted text
  // on iOS, visually indistinguishable from a body Text line. One consistent bordered pill,
  // tinted in the caller's own `color`, matching examples/react/components/ActionButton.tsx.
  import { Pressable, Text } from '@symbiote-native/svelte';

  let {
    title,
    onPress,
    color,
    testID,
  }: { title: string; onPress: () => void; color: string; testID?: string } =
    $props();
</script>

<Pressable
  {testID}
  {onPress}
  class="action-button"
  style={({ pressed }) => ({ borderColor: color, opacity: pressed ? 0.6 : 1 })}
>
  <Text class="action-button-text" style={{ color }}>{title}</Text>
</Pressable>

// examples/expo-react/components/ActionButton.tsx
type IActionButtonProps = {
  title: string;
  onPress: () => void;
  color: string;
  testID?: string;
};

// Drop-in replacement for RN's stock <Button> (same title/onPress/color/testID surface) — a bare
// Button renders as unstyled tinted text on iOS, indistinguishable from body text. One consistent
// bordered pill, tinted by the caller's own `color`, keeps each screen's line color intact.
export function ActionButton({
  title,
  onPress,
  color,
  testID,
}: IActionButtonProps) {
  return (
    <pressable
      testID={testID}
      onPress={onPress}
      className="action-button"
      style={({ pressed }) => ({
        borderColor: color,
        opacity: pressed ? 0.6 : 1,
      })}
    >
      <text className="action-button-text" style={{ color }}>
        {title}
      </text>
    </pressable>
  );
}
