// packages/audio/src/solid/use-audio-stream.ts
import { createMemo, onCleanup, type Accessor } from 'solid-js';
import {
  createResourceHook,
  createEventValueHook,
} from '@symbiote-native/solid';
import { createAudioStreamHooks } from '../core/audio-stream-hooks';
import { toAudioStreamKey } from '../core/audio-stream-subscription';
import { runAudioStreamBufferEffect } from '../core/audio-stream-lifecycle';
import type { IAudioStreamResult, IUseAudioStreamOptions } from '../core';

const { useStreamResource, useStreamStatus } = createAudioStreamHooks(
  createResourceHook,
  createEventValueHook,
);

/** Solid twin of `expo-audio`'s `useAudioStream` */
export function useAudioStream(
  getOptions: Accessor<IUseAudioStreamOptions>,
): Accessor<IAudioStreamResult> {
  const stream = useStreamResource(() => [toAudioStreamKey(getOptions())]);
  const status = useStreamStatus(stream);

  runAudioStreamBufferEffect(
    stream,
    () => getOptions().onBuffer,
    fn => fn(),
    onCleanup,
  );

  return createMemo(() => ({
    stream: stream(),
    isStreaming: status().isStreaming,
  }));
}

// packages/audio/src/react/use-audio-stream.ts
import { useEffect } from 'react';
import {
  createResourceHook,
  createEventValueHook,
} from '@symbiote-native/react';
import { createAudioStreamController } from '../core/audio-stream-controller';
import {
  subscribeAudioStreamBuffer,
  toAudioStreamKey,
} from '../core/audio-stream-subscription';
import { AUDIO_STREAM_STATUS } from '../core/types';
import type {
  AudioStream,
  IAudioStreamResult,
  IAudioStreamStatus,
  IUseAudioStreamOptions,
} from '../core';

const useStreamResource = createResourceHook(createAudioStreamController);
const useStreamStatus = createEventValueHook<
  AudioStream,
  IAudioStreamStatus,
  typeof AUDIO_STREAM_STATUS
>(AUDIO_STREAM_STATUS, stream => ({ isStreaming: stream.isStreaming }));

/** React twin of `expo-audio`'s `useAudioStream` */
export function useAudioStream(
  options: IUseAudioStreamOptions = {},
): IAudioStreamResult {
  const stream = useStreamResource(toAudioStreamKey(options));
  const status = useStreamStatus(stream);

  useEffect(
    () => subscribeAudioStreamBuffer(stream, options.onBuffer),
    [stream, options.onBuffer],
  );

  return { stream, isStreaming: status.isStreaming };
}
