// adapters/react/src/components/virtualized-list/use-separators.ts
// Per-gap separator overrides, render state read straight by the cell walk

import { useCallback, useRef, useState, type RefObject } from 'react';
import {
  EMPTY_OFFSET,
  buildSeparatorHandles,
  isSeparatorGapInRange,
  type ISeparatorProps,
  type ISeparators,
} from '@symbiote-native/components';

export type ISeparatorOverrides<ItemT> = Map<
  number,
  Partial<ISeparatorProps<ItemT>>
>;

export type IListSeparators<ItemT> = {
  // Keyed by the LEADING cell index of the gap
  overridesRef: RefObject<ISeparatorOverrides<ItemT>>;
  makeSeparators: (index: number) => ISeparators;
};

export function useSeparators<ItemT>(count: number): IListSeparators<ItemT> {
  const overridesRef = useRef<ISeparatorOverrides<ItemT>>(new Map());
  const [, setVersion] = useState(EMPTY_OFFSET);

  // A gap outside [0, count - 2] has no separator, so the write is a no-op, RN bails the same way
  const mergeSeparator = useCallback(
    (gapIndex: number, patch: Partial<ISeparatorProps<ItemT>>): void => {
      if (!isSeparatorGapInRange(gapIndex, count)) return;
      const overrides = overridesRef.current;
      overrides.set(gapIndex, { ...overrides.get(gapIndex), ...patch });
      setVersion(version => version + 1);
    },
    [count],
  );

  const makeSeparators = useCallback(
    (index: number): ISeparators =>
      buildSeparatorHandles(index, mergeSeparator),
    [mergeSeparator],
  );
  return { overridesRef, makeSeparators };
}

// adapters/solid/src/components/virtualized-list/use-separators.ts
// Per-gap separator overrides, read straight by the cell walk

import { createSignal } from 'solid-js';
import {
  buildSeparatorHandles,
  buildSeparatorProps,
  isSeparatorGapInRange,
  type ISeparatorProps,
  type ISeparators,
} from '@symbiote-native/components';
import type { IVirtualizedListProps } from './virtualized-list-props';

export type IListSeparators<ItemT> = {
  makeSeparators: (index: number) => ISeparators;
  separatorPropsFor: (index: number) => ISeparatorProps<ItemT>;
};

// Keyed by the leading cell index of the gap, a gap outside [0, count - 2] addresses no separator
export function createSeparators<ItemT>(
  props: IVirtualizedListProps<ItemT>,
  currentCount: () => number,
): IListSeparators<ItemT> {
  const overrides = new Map<number, Partial<ISeparatorProps<ItemT>>>();
  const [version, setVersion] = createSignal(0);
  const mergeSeparator = (
    gapIndex: number,
    patch: Partial<ISeparatorProps<ItemT>>,
  ): void => {
    if (!isSeparatorGapInRange(gapIndex, currentCount())) return;
    overrides.set(gapIndex, { ...overrides.get(gapIndex), ...patch });
    setVersion(tick => tick + 1);
  };
  return {
    makeSeparators: index => buildSeparatorHandles(index, mergeSeparator),
    // Reads `version` so a highlight call reactively refreshes this gap, the Map tracks nothing
    separatorPropsFor: index => {
      version();
      return buildSeparatorProps(
        props.getItem(props.data, index),
        props.getItem(props.data, index + 1),
        overrides.get(index),
      );
    },
  };
}
