// adapters/react/src/jsx-runtime.ts
// The package's own JSX namespace — what an app points `jsxImportSource` at:
//
//   // tsconfig.json
//   "jsx": "react-jsx",
//   "jsxImportSource": "@symbiote-native/react"
//
// WHY IT EXISTS, and it is not ergonomics. `src/jsx.ts` declares our tags by MERGING into
// `declare module 'react'`, which is the only spelling available for somebody else's namespace —
// and a merge inherits every key `@types/react` already owns. `view`, `text`, `image` and `switch`
// are real SVG elements with entries there, so an un-prefixed tag of those names is a TS2717
// ("subsequent property declarations must have the same type") and the `symbiote-` prefix is what
// has been avoiding it. Declaring the interface FRESH here is what frees the short names.
//
// The Solid adapter reached the same place first and its file (`adapters/solid/src/jsx-runtime.ts`)
// carries the measurements — chiefly that TypeScript resolves the namespace from
// `<jsxImportSource>/jsx-runtime` and nothing else. Two differences here:
//
//   1. This entry is NOT type-only. `babel-preset-solid` rewrites JSX into renderer calls, so
//      Solid's emitted runtime is empty and never imported; React's factories are real, and an app
//      that points BABEL's importSource here too must find them. Re-exporting React's own is one
//      line and makes the module correct under either config.
//   2. Only `IntrinsicElements` is declared fresh. Every other member is React's own, re-exported.
//      Solid declares its whole namespace so that `<div>` becomes an error; doing that here is a
//      separate change with its own risk — React's `ElementType` is what admits a component at all,
//      and narrowing it wrongly makes every component call site fail. Today's `jsx.ts` merges into
//      React's table and therefore already accepts `<div>`, so re-exporting keeps that exactly as
//      it is rather than regressing it. Closing the DOM tags is its own task.
import type { ICrossTypedIntrinsics } from '@symbiote-native/components';
import type { Key } from 'react';
import type { IViewProps, ITextProps } from './components';
import type { IPressableProps } from './components/pressable/pressable-props';
import type { IButtonProps } from './components/button-props';
import type { ICheckboxProps } from './components/checkbox-props';
import type { IImageProps } from './components/image/image-props';
import type { IImageBackgroundProps } from './components/image-background-props';
import type { IInputAccessoryViewProps } from './components/input-accessory-view-props';
import type { IRefreshControlProps } from './components/refresh-control-props';
import type { ISafeAreaViewProps } from './components/safe-area-view-props';
import type { ITouchableNativeFeedbackProps } from './components/touchable-native-feedback/touchable-native-feedback-props';
import type {
  ITouchableOpacityProps,
  ITouchableHighlightProps,
} from './components/touchable/touchable-props';
import type { ITouchableWithoutFeedbackProps } from './components/touchable-without-feedback/touchable-without-feedback-props';
import type { IScrollViewProps } from './components/scroll-view/scroll-view-props';
import type { ISwitchProps } from './components/switch/switch-props';
import type { ITextInputProps } from './components/text-input/text-input-props';
import type { IModalProps } from './components/modal';
import type { IActivityIndicatorProps } from './components/activity-indicator-props';

export { Fragment, jsx, jsxs } from 'react/jsx-runtime';

// The loose host boundary for every tag without a dedicated prop type (`sticky-header`,
// `horizontal-scroll-view`, ...). Its index signature already accepts `key` and any other name;
// IWithKey below exists because a closed, crossed type doesn't get that for free.
interface IHostProps {
  style?: unknown;
  children?: import('react').ReactNode;
  [key: string]: unknown;
}

// Every tag with a real, non-generic prop type - mirrors Vue's/Solid's/Svelte's
// `ICrossedPrimitiveProps` (`ICrossTypedIntrinsics`, `@symbiote-native/components`).
// `FlatList`/`SectionList`/`VirtualizedList`/`KeyboardAvoidingView` are absent: composed from
// several intrinsics, never a single tag an app writes.
export interface ICrossedPrimitiveProps {
  view: IViewProps;
  text: ITextProps;
  pressable: IPressableProps;
  button: IButtonProps;
  checkbox: ICheckboxProps;
  image: IImageProps;
  'image-background': IImageBackgroundProps;
  'input-accessory-view': IInputAccessoryViewProps;
  'refresh-control': IRefreshControlProps;
  'safe-area-view': ISafeAreaViewProps;
  'touchable-native-feedback': ITouchableNativeFeedbackProps;
  'touchable-opacity': ITouchableOpacityProps;
  'touchable-highlight': ITouchableHighlightProps;
  'touchable-without-feedback': ITouchableWithoutFeedbackProps;
  'scroll-view': IScrollViewProps;
  switch: ISwitchProps;
  'text-input': ITextInputProps;
  modal: IModalProps;
  'activity-indicator': IActivityIndicatorProps;
}

// TypeScript only auto-merges `JSX.IntrinsicAttributes` (the `key` field) into a value-based
// element's props, not into a crossed intrinsic - verified directly: a component under this same
// jsxImportSource accepts `key`, but a closed crossed type reports "Property 'key' does not exist".
// The loose bag above escapes this only because its index signature already accepts any name.
type IWithKey<Props> = Props & { key?: Key | null };

// The member names are TypeScript's own — the compiler looks each up by exact name — so the repo's
// `I`-prefix convention cannot apply inside this namespace.
/* eslint-disable @typescript-eslint/no-namespace */
export namespace JSX {
  export type ElementType = import('react').JSX.ElementType;
  export type Element = import('react').JSX.Element;
  export type ElementClass = import('react').JSX.ElementClass;
  export type ElementAttributesProperty =
    import('react').JSX.ElementAttributesProperty;
  export type ElementChildrenAttribute =
    import('react').JSX.ElementChildrenAttribute;
  export type LibraryManagedAttributes<C, P> =
    import('react').JSX.LibraryManagedAttributes<C, P>;
  export type IntrinsicAttributes = import('react').JSX.IntrinsicAttributes;
  export type IntrinsicClassAttributes<T> =
    import('react').JSX.IntrinsicClassAttributes<T>;

  // DERIVED from the intrinsic union rather than retyped, so a new host tag becomes valid JSX in
  // the commit that registers its Fabric name.
  // eslint-disable-next-line @typescript-eslint/no-empty-object-type
  export interface IntrinsicElements extends ICrossTypedIntrinsics<
    IHostProps,
    { [K in keyof ICrossedPrimitiveProps]: IWithKey<ICrossedPrimitiveProps[K]> }
  > {}
}
/* eslint-enable @typescript-eslint/no-namespace */

// Off OUR namespace, not React's. It used to be `keyof import('react').JSX.IntrinsicElements`,
// which was every HTML and SVG tag plus ours; now it is the host tags alone.
export type ISymbioteIntrinsicTag = keyof JSX.IntrinsicElements;

// adapters/solid/src/jsx-runtime.ts
// The package's own JSX namespace — what an app points `jsxImportSource` at:
//
//   // tsconfig.json
//   "jsx": "preserve",
//   "jsxImportSource": "@symbiote-native/solid"
//
// TypeScript resolves the namespace from `<jsxImportSource>/jsx-runtime` and NOTHING ELSE. That
// holds under `jsx: "preserve"` too, which is easy to doubt — the flag is documented as naming the
// module the `jsx`/`jsxs` factories are imported from, and `preserve` imports nothing. Measured:
// pointing jsxImportSource at a package that does not exist fails with
// `TS2875: This JSX tag requires the module path '<source>/jsx-runtime' to exist`, on a config
// whose `jsx` is `preserve`. So the entry is type-only by nature — the emitted build/jsx-runtime.js
// is empty and never imported by anything, because babel-preset-solid rewrites JSX into calls on
// ./renderer instead (that is the `moduleName` option, a separate mechanism from this one).
//
// WHY OUR OWN NAMESPACE AND NOT AN AUGMENTATION OF SOLID'S. `@lightningtv/solid` (3.2.5), the
// most widely used universal renderer on a non-DOM host, ships exactly
// `declare module 'solid-js' { namespace JSX { interface IntrinsicElements { … } } }` plus
// `export type { JSX } from 'solid-js'`. That re-export is genuinely all it takes to make the
// entry resolvable, and it is what this package's own src/jsx.ts did before this file replaced it.
// It buys one thing: an app stops needing a `/// <reference types="@symbiote-native/solid" />` line
// to pull the augmentation into its program. It does NOT buy the other two, and both matter more:
//
//   1. Augmenting MERGES into solid-js's own IntrinsicElements, which lists every HTML and SVG
//      tag. `<div>` stays valid JSX in a React Native app and fails at runtime, not at compile
//      time. Declaring the interface fresh here is what makes an unknown tag an error.
//   2. solid-js's `JSX.Element` is `Node | ArrayElement | (string & {}) | number | boolean | null
//      | undefined`, and `Node` is a DOM type. A React Native program has no DOM lib (this repo:
//      `lib: ["ES2022"]`; the canary: RN's own config, equally DOM-less), so the name does not
//      resolve — and `skipLibCheck: true` SUPPRESSES that error inside solid-js's .d.ts rather
//      than surfacing it, leaving `Node` as `any`. One `any` in a union collapses the whole union,
//      so `JSX.Element` is `any` and every JSX child position in every consuming app goes
//      unchecked. Measured two ways: `const bogus: JSX.Element = { definitelyNotAnElement: true }`
//      compiles, and `const node: Node = …` in a first-party file (not skipLibCheck'd) reports
//      `TS2304: Cannot find name 'Node'`.
//
// The risk this trades against — recorded when the swap was deferred — is that our `Element` has
// to line up with what solid-js's own `<Show>` / `<For>` return. It does, for a reason that only
// holds because of point 2 above: those return solid's `JSX.Element`, which IS `any` in exactly the
// DOM-less programs we target, so it is assignable to anything of ours. jsx-runtime.test.tsx pins
// the runtime half (both compose through this renderer and re-render on a signal); the type half is
// carried by examples/solid's own `tsc --noEmit`. The one configuration that would break the
// alignment is an app that pulls in the DOM lib, giving solid's `Element` a real `Node` — recorded
// in `.claude/rules/solid-jsx-namespace.md`.

import type { ICrossTypedIntrinsics } from '@symbiote-native/components';
import type { ISymbioteNode } from '@symbiote-native/engine';
import type { IViewProps } from './components/view-props';
import type { ITextProps } from './components/text-props';
import type { IPressableProps } from './components/pressable-props';
import type { IButtonProps } from './components/button-props';
import type { ICheckboxProps } from './components/checkbox-props';
import type { IImageProps } from './components/image-props';
import type { IImageBackgroundProps } from './components/image-background-props';
import type { IInputAccessoryViewProps } from './components/input-accessory-view-props';
import type { IRefreshControlProps } from './components/refresh-control-props';
import type { ISafeAreaViewProps } from './components/safe-area-view-props';
import type { ITouchableNativeFeedbackProps } from './components/touchable-native-feedback/touchable-native-feedback-props';
import type {
  ITouchableOpacityProps,
  ITouchableHighlightProps,
} from './components/touchable-props';
import type { ITouchableWithoutFeedbackProps } from './components/touchable-without-feedback/touchable-without-feedback-props';
import type { IScrollViewProps } from './components/scroll-view-props';
import type { ISwitchProps } from './components/switch-props';
import type { ITextInputProps } from './components/text-input-props';
import type { IModalProps } from './components/modal';
import type { IActivityIndicatorProps } from './components/activity-indicator-props';

// A flat bag, matching what routeProp actually accepts: it decides prop-vs-event per the node's
// ViewConfig at runtime, so there is no statically-known attribute set to enumerate. Values stay
// `unknown` rather than `any` — an index signature of `unknown` accepts any attribute without
// handing the rest of the file an escape hatch.
//
// This is the PLUMBING type, not the public API: apps use the typed components (`View`, `Text`, …)
// whose props are the real contract. Raw intrinsics are what those components and the Descriptor
// bridge emit.
type ISymbioteHostAttributes = {
  readonly children?: JSX.Element;
  readonly [attribute: string]: unknown;
};

// The member names below are TypeScript's, not ours — the compiler looks up `Element`,
// `IntrinsicElements`, `ElementChildrenAttribute` and friends by exact name, so the repo's
// `I`-prefix convention cannot apply to them. `IArrayElement` is our own helper and does carry it.
//
// The shape is equally the compiler's. A `namespace` is the only container it will read a JSX
// contract out of, several members are REQUIRED to exist while having nothing to declare, and
// `children: {}` has to stay the wide `{}` because it names the property, not its type. So both
// rules below are disabled by the contract rather than by preference, and only inside it —
// solid-js's own jsx.d.ts carries the same empty declarations for the same reason.
// Every tag with a real, non-generic per-adapter prop type today — the same list
// `adapters/vue/src/jsx-runtime.ts` crosses, mirrored here (mirrors `adapters/react/src/jsx-
// runtime.ts` too, which crosses `view`/`text` alone; this one goes further, matching Vue's own
// expansion). `FlatList`/`SectionList`/`VirtualizedList` are deliberately absent: composed
// components built from several intrinsics, never a single tag an app writes, with generic
// (`<ItemT>`) prop types a non-generic `Record<ISymbioteIntrinsic, …>` cannot hold anyway.
interface ICrossedPrimitiveProps {
  view: IViewProps;
  text: ITextProps;
  pressable: IPressableProps;
  button: IButtonProps;
  checkbox: ICheckboxProps;
  image: IImageProps;
  'image-background': IImageBackgroundProps;
  'input-accessory-view': IInputAccessoryViewProps;
  'refresh-control': IRefreshControlProps;
  'safe-area-view': ISafeAreaViewProps;
  'touchable-native-feedback': ITouchableNativeFeedbackProps;
  'touchable-opacity': ITouchableOpacityProps;
  'touchable-highlight': ITouchableHighlightProps;
  'touchable-without-feedback': ITouchableWithoutFeedbackProps;
  'scroll-view': IScrollViewProps;
  switch: ISwitchProps;
  'text-input': ITextInputProps;
  modal: IModalProps;
  'activity-indicator': IActivityIndicatorProps;
}

/* eslint-disable @typescript-eslint/no-namespace, @typescript-eslint/no-empty-object-type */
export namespace JSX {
  // Mirrors solid-js's own union with the one substitution that matters: our committed host node
  // in place of the DOM's `Node`. `(string & {})` is solid's trick for accepting any string while
  // keeping literal types from widening at the use site.
  export type Element =
    | ISymbioteNode
    | IArrayElement
    | IFunctionElement
    | (string & {})
    | number
    | boolean
    | null
    | undefined;

  export interface IArrayElement extends Array<Element> {}

  // solid-js DECLARES this shape and then leaves it out of its own `Element` union. We put it in,
  // because our components hand `insert` a bare accessor by hand — `Pressable`'s zero-argument
  // child branch returns one so `insert` wraps it in its own render effect (the arity guard in
  // components/pressable.tsx). Without this member that line does not type-check; solid-js only
  // gets away with the omission because its accessors are emitted by the compiler, never written.
  //
  // It does NOT cost the contextual typing of a render prop, which was the fear: a children type of
  // `Element | ((state: Accessor<IPressState>) => Element)` now holds TWO function shapes, but they
  // differ in arity, and TypeScript picks the contextual signature by parameter count. Measured —
  // `{state => state().pressed}` with no annotation resolves `state` to `Accessor<IPressState>`,
  // and a bogus field on it reports `Property 'x' does not exist on type 'IPressState'`.
  export interface IFunctionElement {
    (): Element;
  }

  // Deliberately empty, exactly as solid-js leaves them: this adapter has no class components and
  // no props-bearing marker interface, and TypeScript requires the names to exist regardless.
  export interface ElementClass {}
  export interface ElementAttributesProperty {}

  export interface ElementChildrenAttribute {
    children: {};
  }

  // `key`, `ref` and friends are ordinary props here — routeProp sorts them at runtime — so there
  // is nothing to declare as universally-available.
  export interface IntrinsicAttributes {}

  // The tag union comes from @symbiote-native/components rather than being retyped, so a new host
  // tag becomes valid JSX in the same commit that registers its Fabric name — no second list to
  // forget. Declared FRESH (not merged into solid-js's HTML list), which is what makes `<div>` an
  // error in a React Native app. Crossed to `ICrossedPrimitiveProps` above for the tags that carry
  // a real prop type — `IntrinsicAttributes` above is empty (no index signature), so this is fully
  // strict: an unknown prop or a wrong value type on any of them is a real error, not swallowed.
  export interface IntrinsicElements extends ICrossTypedIntrinsics<
    ISymbioteHostAttributes,
    ICrossedPrimitiveProps
  > {}
}
/* eslint-enable @typescript-eslint/no-namespace, @typescript-eslint/no-empty-object-type */
