// adapters/solid/src/components/keyboard-avoiding-view.tsx
// KeyboardAvoidingView — the Solid lifecycle half. It composes a wrapper View and shifts it out of
// the keyboard's way as the keyboard shows/hides. The inset math (readKeyboardFrame /
// readLayoutFrame / computeInset) and the behavior → style/structure decision
// (resolveKeyboardAvoidingLayout) are framework-agnostic and live in @symbiote-native/components,
// shared verbatim with React, Vue, Svelte and Angular. Solid supplies only the reactivity: one
// signal for the inset, three plain variables for the measured frame and the cross-fade setting, a
// subscribe-at-setup / onCleanup pair over the Keyboard module, and the element assembly around its
// own children.
//
// render-keyboard-avoiding-view.ts deliberately returns a layout DESCRIPTION rather than a
// Descriptor tree — KAV wraps a live user subtree, which is the case the render-fn boundary rules
// OUT of core (.claude/rules/component-render-fn-boundary.md). So descriptorToSolid has nothing to
// do here, exactly as in View and Pressable; the two structural shapes ('nested' vs 'wrapper') are
// written directly as the two branches at the bottom.
//
// NO whenCommitted anywhere: KAV issues no imperative native call. It only reads `onLayout`, and the
// engine raises the native layout flag itself the moment a listener rides the prop bag — an event
// cannot arrive before the view exists, so there is no pre-commit window to retry across.
//
// NOTHING here destructures `props`. Solid props are getters and a component body runs ONCE; every
// read below sits inside an accessor, a memo, or an event handler — including
// `keyboardVerticalOffset`, which is read at EVENT time so a changed offset applies to the next
// keyboard event without re-subscribing (React re-runs its useEffect for that; here the closure
// already sees the live value).

import { createMemo, createSignal, onCleanup, splitProps } from 'solid-js';
import type { JSX } from '../jsx-runtime';
import {
  computeInset,
  configureKeyboardAvoidingAnimation,
  keyboardAvoidingEventNamesFor,
  readKeyboardAnimationTiming,
  readKeyboardFrame,
  readLayoutFrame,
  readPrefersCrossFadeTransitions,
  resolveKeyboardAvoidingLayout,
  DEFAULT_VERTICAL_OFFSET,
  type IAccessibilityProps,
  type IAriaProps,
  type IKeyboardAvoidingBehavior,
  type IMeasuredFrame,
} from '@symbiote-native/components';
import {
  Keyboard,
  Platform,
  dlog,
  type IClassNameValue,
  type IEventSubscription,
  type IStyleProp,
  type ISymbioteEvent,
  type IViewStyle,
} from '@symbiote-native/engine';
import { withStableKeys } from '../utils/stable-keys';
import type { IViewProps } from './view-props';

export type { IKeyboardAvoidingBehavior } from '@symbiote-native/components';

// Declared here, not imported from @symbiote-native/components and never from another adapter:
// `children` is a Solid JSX.Element, which is exactly the test
// <prop_types_split_agnostic_vs_per_adapter> applies — the agnostic FIELD BASE
// (IAccessibilityProps / IAriaProps, IKeyboardAvoidingBehavior, IStyleProp, ISymbioteEvent) is
// shared, the framework-flavoured field is per-adapter. React's, Vue's and Svelte's
// IKeyboardAvoidingViewProps are separate declarations for the same reason.
//
// No `ref`: none of the reference adapters exposes one, and P0 parity is measured against React.
export interface IKeyboardAvoidingViewProps
  extends IAccessibilityProps, IAriaProps {
  behavior?: IKeyboardAvoidingBehavior;
  // When false, the view passes through untouched; no inset is applied in any behavior mode. RN
  // gates every inset/height computation on `enabled ?? true` (KeyboardAvoidingView.js), so only an
  // explicit `false` disables.
  enabled?: boolean;
  // Distance from the top of the screen to this view; subtracted from the keyboard's top edge so a
  // view that doesn't start at y=0 still clears the keyboard exactly.
  keyboardVerticalOffset?: number;
  // Style of the inner content container, used only when behavior is 'position'.
  contentContainerStyle?: IStyleProp<IViewStyle>;
  style?: IStyleProp<IViewStyle>;
  // Solid's own spelling for a registered class name — `class`, matching View and Pressable
  // (React's is `className`). Forwarded untouched onto the wrapper View, which resolves it through
  // the shared style registry. contentContainerStyle stays JS-only: it is a plain style object, not
  // style/class itself.
  class?: IClassNameValue;
  // Fires with the wrapper's measured frame. KAV intercepts it to feed the inset math and then
  // calls the caller's handler, so a consumer still sees every layout event.
  onLayout?: (event: ISymbioteEvent) => void;
  children?: JSX.Element;
}

// Read by KeyboardAvoidingView itself; everything else (the aria/role aliases, accessibility*,
// testID, class) forwards onto the wrapper View, which folds them once through
// resolveAccessibilityProps and widens the vanished-key case with withStableKeys.
const HANDLED_PROPS = [
  'behavior',
  'enabled',
  'keyboardVerticalOffset',
  'contentContainerStyle',
  'style',
  'onLayout',
  'children',
] as const;

export function KeyboardAvoidingView(
  props: IKeyboardAvoidingViewProps,
): JSX.Element {
  const [local, rest] = splitProps(props, HANDLED_PROPS);

  const [inset, setInset] = createSignal(0);
  // Plain variables, not signals: a re-measure alone must not repaint anything. They only feed the
  // NEXT keyboard event's math, which is what re-runs the layout memo. Same shape as React's
  // frameRef/initialHeightRef, Vue's `let frame` and Svelte's non-$state pair.
  let frame: IMeasuredFrame | undefined;
  let initialHeight: number | undefined;

  // A device accessibility setting, not state: it cannot change mid-session, and nothing should
  // repaint when the promise lands. So a plain `let` rather than a signal — the same reason `frame`
  // above is one. It is read at EVENT time, by which point the microtask has long resolved; a
  // keyboard event that somehow beat it just sees the `false` default, which is the ordinary math.
  //
  // Through the shared reader, not AccessibilityInfo directly: the engine's getter REJECTS on a
  // native error (RN parity), and nothing awaits this call, so a rejection here would surface as an
  // unhandled promise. readPrefersCrossFadeTransitions owns that fallback once for all five adapters
  // and answers false, which is also what a missing module and an Android host answer.
  let prefersCrossFadeTransitions = false;
  void readPrefersCrossFadeTransitions().then(enabled => {
    prefersCrossFadeTransitions = enabled;
  });

  const onShow = (payload: unknown): void => {
    const keyboard = readKeyboardFrame(payload);
    const offset = local.keyboardVerticalOffset ?? DEFAULT_VERTICAL_OFFSET;
    const previousInset = inset();
    const next = computeInset(frame, keyboard, offset, {
      behavior: local.behavior,
      // The inset CURRENTLY applied (RN's this.state.bottom). Read from the signal at event time so
      // it is live: in 'height' mode the wrapper is SHRUNK by it, so the next onLayout reports a
      // frame shorter by exactly that much and core adds it back to cancel the shrink. Without it
      // each further keyboard event computes a smaller overlap and the view walks back down under
      // the keyboard. Core gates the correction on 'height'; the other modes ignore the value.
      previousInset,
      prefersCrossFadeTransitions,
    });
    // RN's `_updateBottomIfNecessary` skips the animation when the inset did not change.
    if (next !== previousInset)
      configureKeyboardAvoidingAnimation(
        readKeyboardAnimationTiming(payload),
        local.enabled !== false,
      );
    dlog(`KeyboardAvoidingView show -> inset ${next}`);
    setInset(next);
  };
  const onHide = (): void => {
    dlog('KeyboardAvoidingView hide -> inset 0');
    setInset(0);
  };

  // TWO listeners, never three, and their names come from the host (RN KeyboardAvoidingView.js):
  // iOS takes the WILL pair so the view rides up with the keyboard animation instead of snapping
  // into place after it; Android has no will-notifications and keeps the DID pair. The change-frame
  // notification is deliberately absent — RN's own comment says an undocked, split or floating iOS
  // keyboard emits it BEFORE the hide, so listening to it applies a frame captured mid-dismissal.
  //
  // Subscribed in the setup body, which runs once per mount — Solid's counterpart to React's
  // mount-effect and Vue's onMounted. onCleanup runs on dispose (render.ts's teardown disposes the
  // whole root), so an unmount removes exactly the listeners this mount added; leaking them would
  // leave a dead closure calling setInset on a disposed signal on every keystroke.
  const events = keyboardAvoidingEventNamesFor(Platform.OS);
  const subscriptions: IEventSubscription[] = [
    Keyboard.addListener(events.show, onShow),
    Keyboard.addListener(events.hide, onHide),
  ];
  onCleanup(() => {
    for (const subscription of subscriptions) subscription.remove();
  });

  const handleLayout = (event: ISymbioteEvent): void => {
    const measured = readLayoutFrame(event.nativeEvent.layout);
    if (measured !== undefined) {
      frame = measured;
      if (initialHeight === undefined) initialHeight = measured.height;
    }
    local.onLayout?.(event);
  };

  const layout = createMemo(() =>
    resolveKeyboardAvoidingLayout({
      behavior: local.behavior,
      // When disabled the inset is forced to 0, so every behavior mode renders untouched. `inset()`
      // is not read at all on that branch, so a disabled KAV does not even subscribe to the signal;
      // re-enabling re-runs this memo through the `local.enabled` getter and picks the value up.
      effectiveInset: local.enabled === false ? 0 : inset(),
      initialHeight,
      style: local.style,
      contentContainerStyle: local.contentContainerStyle,
    }),
  );

  // What keeps the children alive across a keystroke. Solid has no reconciler between this file and
  // the host nodes — `insert` REPLACES a subtree (.claude/rules/solid-descriptor-bridge.md §4) — and
  // the branch below runs inside the wrapper's `insert` render effect. `layout()` returns a fresh
  // object on every keyboard event, so anything that lets it reach that effect tears the wrapped
  // subtree down and rebuilds it on every show/hide: typically the form the user is typing in, which
  // loses focus mid-keystroke. createMemo's default `===` equality stops the churn at the BOOLEAN —
  // it only notifies when the structure actually flips, i.e. when `behavior` moves in or out of
  // 'position'.
  //
  // babel-preset-solid's `wrapConditionals` (on by default) would memoize the condition of the
  // ternary below on its own, so the inline form happens to be safe too. Naming the memo makes that
  // guarantee local instead of a compiler flag nobody reads, and it survives the refactor that
  // actually breaks it — measured: moving the same branch into a plain `renderContent()` helper (the
  // shape Pressable uses) defeats wrapConditionals and rebuilds the subtree on every keyboard event.
  const isNested = createMemo(() => layout().kind === 'nested');

  // The inset reaches the host as a PROP instead: `spread` runs a per-key diff on the SAME element,
  // so nothing is rebuilt.
  const innerStyle = (): IStyleProp<IViewStyle> | undefined => {
    const resolved = layout();
    return resolved.kind === 'nested' ? resolved.innerStyle : undefined;
  };

  const wrapperProps = createMemo((): IViewProps => ({
    ...rest,
    style: layout().wrapperStyle,
    // Last, so KAV's own measure always runs; the caller's handler is invoked from inside it.
    onLayout: handleLayout,
  }));

  // The half `View` used to supply, now that the wrapper is a bare tag: `spread` has no removal
  // pass, so a key that stops being emitted (`rest` is a splitProps proxy, and `wrapperStyle` is
  // absent in some behaviors) would keep its last value on the native view forever
  // (.claude/rules/solid-descriptor-bridge.md §1).
  const stableWrapperProps = withStableKeys(wrapperProps);

  // 'nested' ('position') pushes the children in an inner View by `bottom: inset`; the wrapper modes
  // ('padding' / 'height' / no behavior) adjust the single wrapper directly.
  return (
    <view {...stableWrapperProps()}>
      {isNested() ? (
        <view style={innerStyle()}>{local.children}</view>
      ) : (
        local.children
      )}
    </view>
  );
}

// adapters/angular/src/components/keyboard-avoiding-view/index.ts
// KeyboardAvoidingView: the Angular lifecycle half. A plain View that shifts out of the
// keyboard's way as it shows/hides. The inset math + the behavior → style/structure decision
// live framework-agnostic in @symbiote-native/components (render-keyboard-avoiding-view), shared verbatim
// with React/Vue; Angular supplies only the lifecycle: a plain inset field, ngOnInit subscribes to
// the core Keyboard module (the host's show / hide pair) and markForCheck pulls the OnPush view (the
// Angular twin of React's setState / Vue's reactive ref), ngOnDestroy tears the subscriptions down,
// and the wrapper's onLayout measures the frame that feeds the next event's inset. The user
// children nest under the wrapper (or, for 'position', an inner View) via <ng-content>. No native
// host of its own — it wraps view — so this stays a flat single file.
//
// Full parity: behavior 'height'|'position'|'padding', enabled, keyboardVerticalOffset,
// contentContainerStyle, onLayout, plus the full a11y/aria surface every View carries.

import {
  CUSTOM_ELEMENTS_SCHEMA,
  ChangeDetectionStrategy,
  ChangeDetectorRef,
  Component,
  ElementRef,
  EventEmitter,
  inject,
  Input,
  Output,
  type OnDestroy,
  type OnInit,
} from '@angular/core';
import {
  computeInset,
  configureKeyboardAvoidingAnimation,
  keyboardAvoidingEventNamesFor,
  readKeyboardAnimationTiming,
  readKeyboardFrame,
  readLayoutFrame,
  readPrefersCrossFadeTransitions,
  resolveAccessibilityProps,
  resolveKeyboardAvoidingLayout,
  DEFAULT_VERTICAL_OFFSET,
  type IAccessibilityProps,
  type IAriaProps,
  type IKeyboardAvoidingBehavior,
  type IKeyboardAvoidingLayout,
  type IMeasuredFrame,
} from '@symbiote-native/components';
import {
  Keyboard,
  Platform,
  dlog,
  isSymbioteEvent,
  type IEventSubscription,
  type IStyleProp,
  type ISymbioteEvent,
  type IViewStyle,
} from '@symbiote-native/engine';
import { AccessibilityEventsBase } from '../../accessibility-events';
import {
  anchorHostStyle,
  SymbioteHostPropsDirective,
  SymbioteStyleInputDirective,
  ViewHost,
} from '../../primitives';

export type { IKeyboardAvoidingBehavior } from '@symbiote-native/components';

// Mirrors React's IKeyboardAvoidingViewProps minus children (Angular takes children via
// <ng-content>), declared per-adapter over the shared accessibility base since a framework-specific
// children field keeps it from being fully shared across adapters.
export interface IAngularKeyboardAvoidingViewProps
  extends IAccessibilityProps, IAriaProps {
  behavior?: IKeyboardAvoidingBehavior;
  enabled?: boolean;
  keyboardVerticalOffset?: number;
  contentContainerStyle?: IStyleProp<IViewStyle>;
  style?: IStyleProp<IViewStyle>;
  onLayout?: (event: ISymbioteEvent) => void;
}

// What the component itself takes as plain @Input()s: the full surface minus onLayout and the
// accessibility callbacks, which it exposes as real @Output() EventEmitters instead (see the
// class below), mirroring Pressable's IAngularPressableInputs split.
export type IAngularKeyboardAvoidingViewInputs = Omit<
  IAngularKeyboardAvoidingViewProps,
  | 'onLayout'
  | 'onAccessibilityAction'
  | 'onAccessibilityTap'
  | 'onMagicTap'
  | 'onAccessibilityEscape'
>;

@Component({
  selector: 'KeyboardAvoidingView',
  standalone: true,
  hostDirectives: [
    { directive: SymbioteStyleInputDirective, inputs: ['style'] },
  ],
  schemas: [CUSTOM_ELEMENTS_SCHEMA],
  imports: [ViewHost, SymbioteHostPropsDirective],
  changeDetection: ChangeDetectionStrategy.OnPush,
  // The wrapper carries a11y + onLayout; 'position' ('nested') pushes the children in an inner
  // View by `bottom: inset`, the wrapper modes adjust the single wrapper directly. Only one @if
  // branch is instantiated, so each branch's <ng-content> projects the children unambiguously.
  // `layout` stays a plain, unconditional template binding: unlike the four accessibility events
  // below, this component READS its own onLayout internally (handleLayout measures the frame that
  // feeds the next keyboard event's inset math — see keyboard-avoiding-view-rn-contract.md), so the
  // gate must stay lit regardless of whether the app subscribes to the `layout` @Output(). Gating it
  // on `.observed` would silently break the inset fixpoint correction the moment an app didn't
  // listen to `layout`.
  template: `
    <view [symbioteHostProps]="hostProps" (layout)="handleLayout($event)">
      @if (isNested) {
        <view [style]="innerStyle">
          <ng-content></ng-content>
        </view>
      } @else {
        <ng-content></ng-content>
      }
    </view>
  `,
})
export class KeyboardAvoidingView
  extends AccessibilityEventsBase
  implements IAngularKeyboardAvoidingViewInputs, OnInit, OnDestroy
{
  @Input() behavior?: IKeyboardAvoidingBehavior;
  @Input() enabled?: boolean;
  @Input() keyboardVerticalOffset?: number;
  @Input() contentContainerStyle?: IStyleProp<IViewStyle>;
  @Input() style?: IStyleProp<IViewStyle>;
  // The wrapper's onLayout is a real @Output(): `(layout)="…"`, not `[onLayout]="…"`. Safe to
  // name it the same as the native `layout` event fired inside this component's own template
  // (see the class's `handleLayout`) — the engine's bubble() treats ANCHOR_HOST_COMPONENTS as
  // transparent to listener lookup, so there is no double-fire.
  @Output() readonly layout = new EventEmitter<ISymbioteEvent>();
  @Input() testID?: string;
  @Input() nativeID?: string;

  // How far the view must move so it no longer overlaps the keyboard. A plain field, not reactive:
  // OnPush + zoneless means a keyboard event mutates it and pulls the view via markForCheck.
  private inset = 0;
  // Mutable, not state: changing the measured frame alone shouldn't re-render; it feeds the next
  // keyboard event's inset math (React's frameRef / initialHeightRef, Vue's frame / initialHeight).
  private frame?: IMeasuredFrame;
  private initialHeight?: number;
  // The iOS "Prefer Cross-Fade Transitions" setting, read once per mount. Deliberately a plain
  // field and NOT markForCheck'd when the promise lands: it is a device setting that cannot change
  // mid-session, and it feeds only the NEXT keyboard event's math — never the current render — so
  // under zoneless CD there is nothing to repaint at resolve time. The keyboard event that does use
  // it already calls markForCheck itself.
  private prefersCrossFadeTransitions = false;
  private subscriptions: IEventSubscription[] = [];

  private readonly changeDetector = inject(ChangeDetectorRef);
  // This component's OWN host — the non-painting anchor `class="..."` at the use site resolves
  // onto (see anchorHostStyle's doc comment) — NOT a ViewChild into the inner view (this
  // component has none; the wrapper IS the outer template node hostProps binds onto).
  private readonly elementRef = inject(ElementRef);

  ngOnInit(): void {
    // TWO events, picked per host, never three: iOS takes the will* pair so the view rides up with
    // the keyboard animation, Android the did* pair. The change-frame notification is deliberately
    // absent — with an undocked/split/floating iOS keyboard it fires BEFORE the hide, so listening
    // to it applies a frame captured mid-dismissal (RN KeyboardAvoidingView.js's own comment).
    const events = keyboardAvoidingEventNamesFor(Platform.OS);
    this.subscriptions = [
      Keyboard.addListener(events.show, payload => this.onShow(payload)),
      Keyboard.addListener(events.hide, () => this.onHide()),
    ];
    // The core wrapper, not AccessibilityInfo directly: the engine's iOS getter REJECTS on a
    // native error (RN parity), and nobody awaits this read, so an unwrapped call would surface
    // as an unhandled rejection. The wrapper answers false on a failed read.
    void readPrefersCrossFadeTransitions().then(enabled => {
      this.prefersCrossFadeTransitions = enabled;
    });
  }

  ngOnDestroy(): void {
    for (const subscription of this.subscriptions) subscription.remove();
    this.subscriptions = [];
  }

  private onShow(payload: unknown): void {
    const keyboard = readKeyboardFrame(payload);
    const offset = this.keyboardVerticalOffset ?? DEFAULT_VERTICAL_OFFSET;
    const next = computeInset(this.frame, keyboard, offset, {
      // Read off the field at event time, not captured when the subscription was built: `behavior`
      // is an @Input that can change under a long-lived subscription, and a stale one keeps
      // applying the old mode's math (it gates the previous-inset correction below).
      behavior: this.behavior,
      // The inset CURRENTLY applied (RN's this.state.bottom), read off the field at event time so
      // 'height' mode's fixpoint correction sees the live value: that mode SHRINKS the wrapper by
      // the inset, so the next onLayout reports a frame shorter by exactly that much.
      previousInset: this.inset,
      prefersCrossFadeTransitions: this.prefersCrossFadeTransitions,
    });
    // RN's `_updateBottomIfNecessary` skips the animation when the inset did not change.
    if (next !== this.inset)
      configureKeyboardAvoidingAnimation(
        readKeyboardAnimationTiming(payload),
        this.enabled !== false,
      );
    dlog(`KeyboardAvoidingView show -> inset ${next}`);
    this.inset = next;
    this.changeDetector.markForCheck();
  }

  private onHide(): void {
    dlog('KeyboardAvoidingView hide -> inset 0');
    this.inset = 0;
    this.changeDetector.markForCheck();
  }

  // The wrapper's onLayout measures the frame BEFORE forwarding to the caller's onLayout, so the
  // next keyboard event's inset math has the view's real position (React/Vue's handleLayout).
  handleLayout(event: unknown): void {
    if (!isSymbioteEvent(event)) return;
    const measured = readLayoutFrame(event.nativeEvent.layout);
    if (measured !== undefined) {
      this.frame = measured;
      if (this.initialHeight === undefined)
        this.initialHeight = measured.height;
    }
    this.layout.emit(event);
  }

  // RN gates every inset on `enabled ?? true`; only an explicit `false` disables, forcing the inset
  // to 0 so every behavior mode renders the view untouched.
  private get effectiveInset(): number {
    return this.enabled === false ? 0 : this.inset;
  }

  // The behavior + effective inset → wrapper/inner styles and the nesting decision (the shared core
  // of RN's render). Recomputed per CD pass, the Angular twin of React/Vue's per-render call.
  // Named `resolvedLayout`, not `layout` — that name is now the onLayout @Output() EventEmitter.
  private get resolvedLayout(): IKeyboardAvoidingLayout {
    return resolveKeyboardAvoidingLayout({
      behavior: this.behavior,
      effectiveInset: this.effectiveInset,
      initialHeight: this.initialHeight,
      style: this.style,
      contentContainerStyle: this.contentContainerStyle,
    });
  }

  get isNested(): boolean {
    return this.resolvedLayout.kind === 'nested';
  }

  get wrapperStyle(): IStyleProp<IViewStyle> | undefined {
    return this.resolvedLayout.wrapperStyle;
  }

  get innerStyle(): IStyleProp<IViewStyle> | undefined {
    return this.resolvedLayout.kind === 'nested'
      ? this.resolvedLayout.innerStyle
      : undefined;
  }

  // The wrapper's full prop bag (style + identity + a11y) folded for `[symbioteHostProps]`,
  // the same pattern Modal's `hostProps` uses over its renderModal descriptor. The anchor's
  // class-derived style goes FIRST, the resolved wrapper style SECOND — flattenStyle's later-wins
  // collapse keeps an explicit [style] winning over its ambient class.
  get hostProps(): Record<string, unknown> {
    return {
      style: [anchorHostStyle(this.elementRef), this.wrapperStyle],
      testID: this.testID,
      nativeID: this.nativeID,
      accessible: this.accessible,
      ...this.folded,
      onAccessibilityAction: this.eventEmitterHandler(this.accessibilityAction),
      onAccessibilityTap: this.eventEmitterHandler(this.accessibilityTap),
      onMagicTap: this.eventEmitterHandler(this.magicTap),
      onAccessibilityEscape: this.eventEmitterHandler(this.accessibilityEscape),
    };
  }

  // Forward an engine event to the matching @Output(), narrowing the template's untyped $event
  // first.
  private emit(emitter: EventEmitter<ISymbioteEvent>, event: unknown): void {
    if (isSymbioteEvent(event)) emitter.emit(event);
  }

  // The four accessibility events are boolean-GATED Fabric events
  // (`.claude/rules/fabric-boolean-event-gates.md`). `.observed`-gated, unlike `layout` above which
  // this component needs unconditionally for its own internal frame measurement.
  private eventEmitterHandler(
    emitter: EventEmitter<ISymbioteEvent>,
  ): ((event: unknown) => void) | undefined {
    return emitter.observed ? event => this.emit(emitter, event) : undefined;
  }

  // Folds the aria-*/role aliases into the canonical accessibility* props, native ignores aria-*
  get folded(): Partial<IAngularKeyboardAvoidingViewProps> {
    return resolveAccessibilityProps(this.accessibilityInputProps());
  }
}
