// packages/navigation/src/react/tabs/index.ts
// Tab, the React lifecycle half. The focused-index router (tab-router-state) and the tab-bar
// Descriptor builder (render-tabs) live in @symbiote-native/navigation core, shared verbatim
// with the Vue/Angular adapters; here React supplies the lifecycle - useState for the dispatched
// router state, useId for route-key generation, useImperativeHandle for the jumpTo/setParams
// handle - plus the descriptor bridge for the tab-bar leaf, exactly like Stack bridges its header
// config (react/stack.ts). Unlike Stack, a bottom-tabs bar is a PURE-JS UI: it paints ordinary
// `symbiote-view`/`symbiote-text` primitives via the shared render fn, so there is no
// react-native-screens ViewConfig to register here - Tab needs no `../register` import.

import {
  createElement,
  forwardRef,
  isValidElement,
  useCallback,
  useContext,
  useEffect,
  useId,
  useImperativeHandle,
  useMemo,
  useState,
} from 'react';
import type { ReactElement, ReactNode } from 'react';
import { descriptorToReact } from '@symbiote-native/react';
import { dlog } from '@symbiote-native/engine';
import {
  NAVIGATION_EVENT_BLUR,
  NAVIGATION_EVENT_FOCUS,
  createInitialTabState,
  createNavigationEmitter,
  isFocusedRoute,
  reconcileTabRoutes,
  renderTabBar,
  tabRouterReducer,
} from '../../core';
import type {
  IRoute,
  ITabBarItemView,
  ITabNavigatorHandle,
  ITabOptions,
  ITabRouterAction,
  ITabRouterState,
} from '../../core';
import { collectRegistry } from '../collect-registry';
import { NavigationContext } from '../navigation-context';
import { TabScreen } from '../tab-screen';
import type { ITabScreenOptionsArgs, ITabScreenProps } from '../tab-screen';

export type { ITabNavigatorHandle } from '../../core';

export type ITabProps = {
  initialRouteName?: string;
  screenOptions?: ITabOptions;
  children?: ReactNode;
};

type ITabRegistryEntry = Omit<ITabScreenProps, 'name'>;

function isTabScreenElement(
  child: ReactNode,
): child is ReactElement<ITabScreenProps> {
  return isValidElement(child) && child.type === TabScreen;
}

function resolveTabOptions(
  entry: ITabRegistryEntry,
  optionsArgs: ITabScreenOptionsArgs,
  screenOptions: ITabOptions | undefined,
): ITabOptions {
  const own =
    typeof entry.options === 'function'
      ? entry.options(optionsArgs)
      : entry.options;
  return { ...screenOptions, ...own };
}

const TAB_CONTENT_STYLE = { flex: 1 };
const TAB_ROOT_STYLE = { flex: 1 };

const TabImpl = forwardRef<ITabNavigatorHandle, ITabProps>(
  (props, forwardedRef) => {
    // Read BEFORE establishing this Tab's own Context value below - becomes the `parent` link a
    // nested screen's useNavigation().getParent() walks (e.g. this Tab rendered as a Stack screen's
    // content reaches that Stack via this value). undefined when this Tab is the nesting root.
    const ambientContext = useContext(NavigationContext);
    const registry = useMemo(
      () => collectRegistry(props.children, isTabScreenElement),
      [props.children],
    );
    const routeIdPrefix = useId();

    const routes = useMemo<IRoute<unknown>[]>(
      () =>
        Array.from(registry.entries()).map(([name, entry]) => ({
          key: `${routeIdPrefix}-${name}`,
          name,
          params: entry.initialParams,
        })),
      [registry, routeIdPrefix],
    );

    // A <Tab.Screen> can appear or disappear after mount (a marker behind a conditional, a
    // data-driven screen list), so the route list is re-derived from `children` on every render and
    // the STORED state is reconciled against it (reconcileTabRoutes, core - it preserves each
    // surviving route's key and accumulated params and keeps focus on the same route NAME) rather
    // than staying frozen at whatever the first render saw. `null` means no marker had registered
    // yet: seeding an empty list would resolve initialRouteName against nothing and lose it, so the
    // state stays derived until either a marker arrives or something dispatches.
    const [storedState, setStoredState] = useState<ITabRouterState | null>(
      () =>
        routes.length === 0
          ? null
          : createInitialTabState(routes, props.initialRouteName),
    );

    const resolveState = useCallback(
      (stored: ITabRouterState | null): ITabRouterState =>
        stored === null
          ? createInitialTabState(routes, props.initialRouteName)
          : reconcileTabRoutes(stored, routes),
      [routes, props.initialRouteName],
    );

    const state = resolveState(storedState);

    if (routes.length === 0) dlog('Tab: no <Tab.Screen> children registered');

    // The updater re-resolves rather than closing over `state` so that two dispatches batched into
    // one render still compose: the second reduces over the first's result, not a stale snapshot.
    const dispatch = useCallback(
      (action: ITabRouterAction) =>
        setStoredState(current =>
          tabRouterReducer(resolveState(current), action),
        ),
      [resolveState],
    );

    const jumpTo = useCallback(
      (name: string, params?: unknown) =>
        dispatch({ type: 'jumpTo', name, params }),
      [dispatch],
    );
    const setParams = useCallback(
      (params: unknown, key: string) =>
        dispatch({ type: 'setParams', key, params }),
      [dispatch],
    );

    const handle = useMemo<ITabNavigatorHandle>(
      () => ({ jumpTo, setParams }),
      [jumpTo, setParams],
    );

    useImperativeHandle(forwardedRef, () => handle, [handle]);

    const focusedRoute: IRoute<unknown> | undefined = state.routes[state.index];

    const items: ITabBarItemView[] = state.routes.map((route, index) => {
      const entry = registry.get(route.name);
      const focused = isFocusedRoute(index, state.index);
      if (!entry) {
        dlog(`Tab: no screen registered for route name "${route.name}"`);
        return {
          key: route.key,
          focused,
          label: route.name,
          passthrough: {},
        };
      }

      const options = resolveTabOptions(
        entry,
        { route, navigation: handle },
        props.screenOptions,
      );

      return {
        key: route.key,
        focused,
        label: options.tabBarLabel ?? options.title ?? route.name,
        icon: options.tabBarIcon,
        badge: options.tabBarBadge,
        activeTintColor: options.tabBarActiveTintColor,
        inactiveTintColor: options.tabBarInactiveTintColor,
        passthrough: {
          onPress: () => jumpTo(route.name),
          accessibilityRole: 'tab',
          accessibilityState: { selected: focused },
        },
      };
    });

    const focusedEntry = focusedRoute
      ? registry.get(focusedRoute.name)
      : undefined;
    const focusedOptions: ITabOptions | undefined =
      focusedEntry && focusedRoute
        ? resolveTabOptions(
            focusedEntry,
            { route: focusedRoute, navigation: handle },
            props.screenOptions,
          )
        : props.screenOptions;

    const tabBar = descriptorToReact(
      renderTabBar({
        items,
        style: focusedOptions?.tabBarStyle,
        passthrough: {},
      }),
    );

    // Only the focused route's screen is ever mounted (unlike Stack, which keeps every pushed route
    // alive), so a fresh emitter per focus change is sufficient - no per-route emitter map to prune,
    // because the previous screen's whole subtree (and any listeners it registered) is torn down by
    // an ordinary React unmount when focus moves on. Keyed on the route KEY rather than the route
    // object so a setParams-only change (new route object, same key) doesn't spuriously re-fire
    // focus/blur.
    const focusedRouteKey = focusedRoute?.key;
    const routeEmitter = useMemo(
      () => createNavigationEmitter(),
      [focusedRouteKey],
    );

    // Tab paints its own bar in pure JS - there is no native onAppear/onDisappear to hook (unlike
    // Stack's RNSScreen), so focus/blur is synthesized here: mount = focus, cleanup = blur, exactly
    // what an effect keyed on focusedRouteKey already encodes - no diffFocusedRoute indirection
    // needed (unlike Vue/Angular, which diff real prev/next keys inside an imperative watch/CD
    // callback that has no mount/cleanup pairing of its own).
    useEffect(() => {
      if (focusedRouteKey === undefined) return undefined;
      dlog(`Tab: route "${focusedRoute?.name}" focused`);
      routeEmitter.emit(NAVIGATION_EVENT_FOCUS);
      return () => {
        dlog(`Tab: route "${focusedRoute?.name}" blurred`);
        routeEmitter.emit(NAVIGATION_EVENT_BLUR);
      };
      // focusedRoute omitted deliberately: only its .key (tracked via focusedRouteKey) should
      // re-run this effect - see the comment above on focusedRouteKey.
      // eslint-disable-next-line react-hooks/exhaustive-deps
    }, [routeEmitter, focusedRouteKey]);

    const content =
      focusedEntry && focusedRoute
        ? createElement(
            NavigationContext.Provider,
            {
              value: {
                route: focusedRoute,
                navigation: handle,
                emitter: routeEmitter,
                parent: ambientContext,
              },
            },
            createElement(focusedEntry.component),
          )
        : null;

    return createElement(
      'symbiote-view',
      { style: TAB_ROOT_STYLE },
      createElement('symbiote-view', { style: TAB_CONTENT_STYLE }, content),
      tabBar,
    );
  },
);

export const Tab = Object.assign(TabImpl, { Screen: TabScreen });

// packages/navigation/src/svelte/tabs/index.svelte
<script lang="ts" module>
  // Tab, the Svelte lifecycle half. The focused-index router (tab-router-state) and the tab-bar
  // Descriptor builder (render-tabs) live in @symbiote-native/navigation core, shared verbatim
  // with the React/Vue/Angular entries; here Svelte supplies the lifecycle - `$state.raw` for the
  // router (its twin of useReducer), a module counter for route-key generation, `export
  // function`s for the jumpTo/setParams handle - plus the Descriptor bridge for the tab-bar leaf.
  // Unlike Stack, a bottom-tabs bar is a PURE-JS UI: it paints ordinary `view`/
  // `text` primitives via the shared render fn, so there is no react-native-screens
  // ViewConfig to register here - Tab needs no `../../register` import.
  //
  // Screens are discovered through the context collector (../screen-registry.ts), not by reading
  // `children` - see stack/index.svelte's header for why, and ../registry-host.ts for where the
  // markers are rendered.
  let tabInstanceCounter = 0;

  const TAB_ROOT_PROPS: Record<string, unknown> = { style: { flex: 1 } };
  const TAB_CONTENT_PROPS: Record<string, unknown> = { style: { flex: 1 } };
</script>

<script lang="ts">
  import type { Component } from 'svelte';
  import { onDestroy, tick } from 'svelte';
  import { dlog } from '@symbiote-native/engine';
  import type { ShimElement } from '@symbiote-native/svelte/native-view-bridge';
  import {
    NAVIGATION_EVENT_BLUR,
    NAVIGATION_EVENT_FOCUS,
    createInitialTabState,
    createNavigationEmitter,
    diffFocusedRoute,
    isFocusedRoute,
    reconcileTabRoutes,
    renderTabBar,
    tabRouterReducer,
  } from '../../core';
  import type {
    IDescriptor,
    INavigationEmitter,
    IRoute,
    ITabBarItemView,
    ITabNavigatorHandle,
    ITabOptions,
    ITabRouterAction,
    ITabRouterState,
  } from '../../core';
  import { createDescriptorSubtreeSync } from '../descriptor-subtree';
  import { getNavigationScope } from '../navigation-context';
  import type { INavigationScopeValue } from '../navigation-context';
  import NavigationScope from '../navigation-scope.svelte';
  import { SCREEN_REGISTRY_HOST_PROPS } from '../registry-host';
  import {
    setScreenCollector,
    toRegistry,
    withoutScreen,
  } from '../screen-registry';
  import type { IRegisteredScreen } from '../screen-registry';
  import type { ITabScreenProps } from '../tab-screen-props';
  import type { ITabProps } from './tab-props';

  let { initialRouteName, screenOptions, children }: ITabProps = $props();

  // Read BEFORE this Tab establishes its own per-screen NavigationScope - becomes the `parent`
  // link a nested screen's useNavigation().getParent() walks. undefined at the nesting root.
  const parentScope = getNavigationScope();

  const routeIdPrefix = `tab-${(tabInstanceCounter += 1)}`;

  let screens = $state.raw<IRegisteredScreen<ITabScreenProps['options']>[]>([]);
  setScreenCollector<ITabScreenProps['options']>({
    kind: 'tab',
    register: screen => {
      screens = [...screens, screen];
    },
    unregister: screen => {
      screens = withoutScreen(screens, screen);
    },
  });

  const registry = $derived(toRegistry(screens));

  // A tab's route list is a PROJECTION of the registry, not navigation history the way Stack's
  // is: a marker registering or unregistering must add or drop its tab. Unlike Stack, a route key
  // here is derived from the route NAME rather than an incrementing sequence, so re-deriving this
  // list on every registry change re-keys nothing.
  const registeredRoutes = $derived.by<IRoute<unknown>[]>(() =>
    [...registry.entries()].map(([name, entry]) => ({
      key: `${routeIdPrefix}-${name}`,
      name,
      params: entry.initialParams,
    })),
  );

  // The dispatched half is the only STATE here; the registry half is re-derived and reconciled
  // against it on every change (reconcileTabRoutes, core - it is what preserves each surviving
  // route's key/params and keeps the focus on the same route NAME). Nothing needs memoizing
  // inside the derivation, so there is no state write during a derivation to avoid in the first
  // place. Until something dispatches there is nothing to reconcile against, hence the seed.
  let dispatchedState = $state.raw<ITabRouterState | null>(null);

  const state = $derived.by<ITabRouterState>(() => {
    if (registeredRoutes.length === 0)
      dlog('Tab: no <Tab.Screen> children registered');
    const dispatched = dispatchedState;
    return dispatched === null
      ? createInitialTabState(registeredRoutes, initialRouteName)
      : reconcileTabRoutes(dispatched, registeredRoutes);
  });

  function dispatch(action: ITabRouterAction): void {
    dispatchedState = tabRouterReducer(state, action);
  }

  export function jumpTo(name: string, params?: unknown): void {
    dispatch({ type: 'jumpTo', name, params });
  }
  export function setParams(params: unknown, key: string): void {
    dispatch({ type: 'setParams', key, params });
  }

  const handle: ITabNavigatorHandle = { jumpTo, setParams };

  // One emitter per route.key, created lazily and cached for the navigator's whole lifetime -
  // mirrors Stack's own `emitters` map. This decouples emitter IDENTITY (stable, looked up by
  // key, read below when a route's NavigationScope is built) from emit TIMING (must wait until
  // the focused screen has actually mounted and subscribed).
  const emitters = new Map<string, INavigationEmitter>();
  function emitterFor(routeKey: string): INavigationEmitter {
    let emitter = emitters.get(routeKey);
    if (emitter === undefined) {
      emitter = createNavigationEmitter();
      emitters.set(routeKey, emitter);
    }
    return emitter;
  }

  // Tab paints its own bar in pure JS - there is no native onAppear/onDisappear to hook (unlike
  // Stack's RNSScreen), so focus/blur is synthesized here. Keyed on the route KEY (not the route
  // object) so a setParams-only change doesn't spuriously re-fire focus/blur.
  //
  // The bookkeeping updates immediately, but the actual emit is deferred to `tick()` - Svelte's
  // twin of Vue's nextTick, and needed for the same reason: the newly-focused screen's own
  // `$effect`s (its useIsFocused/useFocusEffect subscriptions) are created during THIS flush,
  // after this effect was, so emitting synchronously here would reach zero subscribers.
  let previousFocusedKey: string | undefined;
  $effect(() => {
    const nextKey = state.routes[state.index]?.key;
    const { blurKey, focusKey } = diffFocusedRoute(previousFocusedKey, nextKey);
    if (blurKey === undefined && focusKey === undefined) return;
    previousFocusedKey = nextKey;
    void tick().then(() => {
      if (blurKey !== undefined) {
        dlog(`Tab: route "${blurKey}" blurred at t=${Date.now()}`);
        emitterFor(blurKey).emit(NAVIGATION_EVENT_BLUR);
      }
      if (focusKey !== undefined) {
        dlog(`Tab: route "${focusKey}" focused at t=${Date.now()}`);
        emitterFor(focusKey).emit(NAVIGATION_EVENT_FOCUS);
      }
    });
  });

  onDestroy(() => {
    if (previousFocusedKey !== undefined) {
      emitterFor(previousFocusedKey).emit(NAVIGATION_EVENT_BLUR);
    }
  });

  function resolveTabOptions(
    entry: IRegisteredScreen<ITabScreenProps['options']> | undefined,
    route: IRoute<unknown>,
  ): ITabOptions {
    const own =
      entry === undefined
        ? undefined
        : typeof entry.options === 'function'
          ? entry.options({ route, navigation: handle })
          : entry.options;
    return { ...screenOptions, ...own };
  }

  const items = $derived.by<ITabBarItemView[]>(() =>
    state.routes.map((route, index) => {
      const entry = registry.get(route.name);
      const focused = isFocusedRoute(index, state.index);
      if (entry === undefined) {
        dlog(`Tab: no screen registered for route name "${route.name}"`);
        return { key: route.key, focused, label: route.name, passthrough: {} };
      }
      const options = resolveTabOptions(entry, route);
      return {
        key: route.key,
        focused,
        label: options.tabBarLabel ?? options.title ?? route.name,
        icon: options.tabBarIcon,
        badge: options.tabBarBadge,
        activeTintColor: options.tabBarActiveTintColor,
        inactiveTintColor: options.tabBarInactiveTintColor,
        passthrough: {
          onPress: () => jumpTo(route.name),
          accessibilityRole: 'tab',
          accessibilityState: { selected: focused },
        },
      };
    }),
  );

  const focusedRoute = $derived(state.routes[state.index]);
  const focusedOptions = $derived(
    focusedRoute === undefined
      ? screenOptions
      : resolveTabOptions(registry.get(focusedRoute.name), focusedRoute),
  );

  const tabBar = $derived.by<IDescriptor>(() =>
    renderTabBar({
      items,
      style: focusedOptions?.tabBarStyle,
      passthrough: {},
    }),
  );

  // Only the focused route's screen is ever mounted (unlike Stack, which keeps every pushed route
  // alive), so a fresh NavigationScope per focus change is sufficient - the previous screen's
  // whole subtree (and any listeners it registered) is torn down by an ordinary unmount when
  // focus moves on.
  const focusedScreen = $derived.by<
    { scope: INavigationScopeValue; component: Component } | undefined
  >(() => {
    if (focusedRoute === undefined) return undefined;
    const entry = registry.get(focusedRoute.name);
    if (entry === undefined) return undefined;
    return {
      component: entry.component,
      scope: {
        route: focusedRoute,
        navigation: handle,
        emitter: emitterFor(focusedRoute.key),
        parent: parentScope?.current,
      },
    };
  });

  // The bar's ROOT stays a literal template tag (so `bind:this` has a statically known tag) and
  // only its children go through the Descriptor bridge - the uniform shape every Svelte component
  // consuming a `render-*.ts` uses (svelte-adapter-dom-shim skill §19). The item count varies with
  // the registry, hence the shape-change-tolerant wrapper rather than the raw bridge.
  let tabBarHost = $state.raw<ShimElement | null>(null);
  const syncTabBarChildren = createDescriptorSubtreeSync();
  $effect(() => {
    const host = tabBarHost;
    const barChildren = tabBar.children;
    syncTabBarChildren(host, barChildren);
  });
</script>

<view p={TAB_ROOT_PROPS}>
  <text p={SCREEN_REGISTRY_HOST_PROPS}>
    {@render children?.()}
  </text>
  <view p={TAB_CONTENT_PROPS}>
    {#if focusedScreen !== undefined}
      {@const FocusedComponent = focusedScreen.component}
      <NavigationScope value={focusedScreen.scope}>
        <FocusedComponent />
      </NavigationScope>
    {/if}
  </view>
  <view p={tabBar.props} bind:this={tabBarHost} />
</view>
