// adapters/angular/src/components/flat-list/index.ts
// FlatList, the Angular convenience surface over VirtualizedList. It takes a plain `data` array
// and derives getItem/getItemCount; numColumns packs items into rows (each row a flex-row of N
// columns), so the virtualized stream is rows, not items (RN's FlatList). Windowing / viewability /
// batching / imperative scrolling are inherited from VirtualizedList; the data shaping
// (chunkIntoRows / rowKeyExtractor / expandRowViewability / row-separator unwrap) is shared
// verbatim from @symbiote-native/components, same as React/Vue's FlatLists.
//
// TEMPLATE FORWARDING — both column paths RE-STAMP; neither uses a bare `<ng-content>` passthrough.
// Angular's @ContentChild does NOT resolve a directive across a SECOND `<ng-content>` re-projection
// hop (only what's projected directly onto the querying component's own tag) — a bare
// `<VirtualizedList ...><ng-content></ng-content></VirtualizedList>` left VirtualizedList's own
// itemDir/headerDir/etc. undefined, rendering every cell empty (confirmed device bug, see
// flat-list.test.ts). Fixed for both column modes:
//   * Single column (numColumns <= 1): FlatList captures the app's `<ng-template vListItem>` (and
//     vListHeader/vListFooter/vListEmpty/vListSeparator) with its OWN @ContentChild — a single,
//     direct projection hop, which always resolves. The per-cell item and separator templates go
//     straight in through VirtualizedList's `[itemTemplate]`/`[itemSeparatorTemplate]`, so a cell
//     is ONE outlet deep (a re-stamp doubled every cell's embedded views); the once-per-list
//     header/footer/empty slots are still re-stamped.
//   * Multi column (numColumns > 1): same re-stamp, but the app's vListItem is typed for ItemT
//     while the virtualized stream is rows (IRow<ItemT>), so a plain passthrough couldn't work
//     regardless. The row vListItem lays out the N columns side by side (each cell stamps the
//     app's item template via VListOutletDirective with context {item, index: row.startIndex +
//     column, separators}), the row vListSeparator unwraps the flanking rows to their last/first
//     item, and onViewableItemsChanged is wrapped with expandRowViewability so the caller still
//     sees per-item visibility — mirrors how Vue's FlatList intercepts renderItem with renderRow.
//
// The imperative handle (scrollToIndex / scrollToOffset / scrollToEnd / scrollToItem /
// recordInteraction / flashScrollIndicators / getScroll* / getNativeScrollRef) is RN's FlatList
// surface, delegated straight to the inner VirtualizedList (@ViewChild). The element-returning
// props (renderItem / ItemSeparatorComponent / List{Header,Footer,Empty}Component) are templates
// in Angular, so they're absent from IFlatListProps per the per-adapter children/render split;
// everything else mirrors IVirtualizedListProps.

import {
  CUSTOM_ELEMENTS_SCHEMA,
  ChangeDetectionStrategy,
  Component,
  ContentChild,
  ElementRef,
  EventEmitter,
  Input,
  Output,
  ViewChild,
  inject,
  type DoCheck,
  type OnChanges,
  type SimpleChanges,
} from '@angular/core';
import {
  SINGLE_COLUMN,
  chunkIntoRows,
  expandRowViewability,
  firstItemOfRow,
  lastItemOfRow,
  removeClippedSubviewsOrDefault,
  rowKeyExtractor,
  type IRow,
  type IScrollViewHandle,
  type ISeparators,
  type IViewabilityConfigCallbackPair,
  type IViewableItemsChangedInfo,
  type IVirtualizedListHandle,
} from '@symbiote-native/components';
import {
  Platform,
  dlog,
  flattenStyle,
  resolveClassName,
  type IStyleProp,
  type ISymbioteNode,
  type IViewStyle,
} from '@symbiote-native/engine';
import {
  VirtualizedList,
  VListEmptyDirective,
  VListFooterDirective,
  VListHeaderDirective,
  VListItemDirective,
  VListSeparatorDirective,
  type IVirtualizedListProps,
  type IVListItemContext,
  type IVListSeparatorContext,
} from '../virtualized-list';
import { VListOutletDirective } from '../virtualized-list/directives';
import {
  stableAnchorStyle,
  SymbioteStyleInputDirective,
  ViewHost,
} from '../../primitives';

function isRecord(value: unknown): value is Record<string, unknown> {
  return typeof value === 'object' && value !== null;
}
function isRow<ItemT>(value: unknown): value is IRow<ItemT> {
  return (
    isRecord(value) &&
    Array.isArray(value['items']) &&
    typeof value['startIndex'] === 'number'
  );
}
function isSeparators(value: unknown): value is ISeparators {
  return (
    isRecord(value) &&
    typeof value['highlight'] === 'function' &&
    typeof value['unhighlight'] === 'function'
  );
}
// Used only as a type-safe fallback if a row's separators handle is ever absent; VirtualizedList
// always supplies a real one, so in practice the live handle flows through.
const NOOP_SEPARATORS: ISeparators = {
  highlight: (): void => undefined,
  unhighlight: (): void => undefined,
  updateProps: (): void => undefined,
};

// Re-export the shared list types + the authoring directives so the app can import the cell/slot
// directives alongside FlatList (mirrors how virtualized-list/index re-exports them).
export type {
  ISeparators,
  IViewableItemsChangedInfo,
  IViewabilityConfigCallbackPair,
  IVirtualizedListHandle,
} from '@symbiote-native/components';
export {
  VListEmptyDirective,
  VListFooterDirective,
  VListHeaderDirective,
  VListItemDirective,
  VListSeparatorDirective,
} from '../virtualized-list';
export type {
  IVListItemContext,
  IVListSeparatorContext,
} from '../virtualized-list';

// FlatList's imperative handle is exactly VirtualizedList's.
export type IFlatListHandle = IVirtualizedListHandle;

// The Angular FlatList prop surface. Mirrors React/Vue's IFlatListProps: every agnostic
// VirtualizedList prop EXCEPT data/getItem/getItemCount (FlatList derives those from a plain `data`
// array), PLUS numColumns + columnWrapperStyle. The element-returning props are templates in
// Angular, so they are absent here (they were already absent from IVirtualizedListProps).
export type IFlatListProps<ItemT> = Omit<
  IVirtualizedListProps<ItemT>,
  'data' | 'getItem' | 'getItemCount'
> & {
  data: readonly ItemT[];
  numColumns?: number;
  // Style for the auto-generated row View when numColumns > 1 (RN's columnWrapperStyle). A bare
  // string resolves through the shared style registry.
  columnWrapperStyle?: IStyleProp<IViewStyle> | string;
};

// What the FlatList component itself takes as plain @Input()s: the full surface minus the events
// it exposes as real @Output() EventEmitters instead (see the class below), mirroring how
// pressable/index.ts derives IAngularPressableInputs from IAngularPressableProps.
export type IFlatListInputs<ItemT> = Omit<
  IFlatListProps<ItemT>,
  | 'onEndReached'
  | 'onStartReached'
  | 'onRefresh'
  | 'onViewableItemsChanged'
  | 'onScrollToIndexFailed'
>;

@Component({
  selector: 'FlatList',
  standalone: true,
  hostDirectives: [
    { directive: SymbioteStyleInputDirective, inputs: ['style'] },
  ],
  schemas: [CUSTOM_ELEMENTS_SCHEMA],
  imports: [
    VirtualizedList,
    VListItemDirective,
    VListHeaderDirective,
    VListFooterDirective,
    VListEmptyDirective,
    VListSeparatorDirective,
    VListOutletDirective,
    ViewHost,
  ],
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: `
    @if (isMultiColumn) {
      <VirtualizedList
        [data]="rows"
        [getItem]="getRow"
        [getItemCount]="getRowCount"
        [keyExtractor]="rowKey"
        [getItemLayout]="getItemLayout"
        [horizontal]="horizontal"
        [inverted]="inverted"
        [extraData]="extraData"
        (endReached)="endReached.emit($event)"
        [onEndReachedThreshold]="onEndReachedThreshold"
        (startReached)="startReached.emit($event)"
        [onStartReachedThreshold]="onStartReachedThreshold"
        (refresh)="refresh.emit()"
        [refreshRequested]="refresh.observed"
        [refreshing]="refreshing"
        [progressViewOffset]="progressViewOffset"
        (viewableItemsChanged)="rowViewableItemsChanged($event)"
        [viewabilityConfig]="viewabilityConfig"
        [viewabilityConfigCallbackPairs]="rowViewabilityPairs"
        (scrollToIndexFailed)="scrollToIndexFailed.emit($event)"
        [initialNumToRender]="initialNumToRender"
        [initialScrollIndex]="initialScrollIndex"
        [maxToRenderPerBatch]="maxToRenderPerBatch"
        [updateCellsBatchingPeriod]="updateCellsBatchingPeriod"
        [windowSize]="windowSize"
        [stickyHeaderIndices]="stickyHeaderIndices"
        [maintainVisibleContentPosition]="maintainVisibleContentPosition"
        [onScroll]="onScroll"
        [onScrollBeginDrag]="onScrollBeginDrag"
        [onScrollEndDrag]="onScrollEndDrag"
        [onMomentumScrollBegin]="onMomentumScrollBegin"
        [onMomentumScrollEnd]="onMomentumScrollEnd"
        [scrollEventThrottle]="scrollEventThrottle"
        [keyboardShouldPersistTaps]="keyboardShouldPersistTaps"
        [keyboardDismissMode]="keyboardDismissMode"
        [removeClippedSubviews]="resolvedRemoveClippedSubviews"
        [nestedScrollEnabled]="nestedScrollEnabled"
        [testID]="testID"
        [style]="resolvedStyle"
        [contentContainerStyle]="contentContainerStyle"
      >
        <ng-template vListItem let-row let-separators="separators">
          <view [style]="rowStyle">
            @for (cell of rowCells(row, separators); track cell.key) {
              <view [style]="columnCellStyle">
                <ng-container
                  [vListOutlet]="itemDir?.templateRef"
                  [vListOutletContext]="cell.context"
                ></ng-container>
              </view>
            }
          </view>
        </ng-template>
        @if (headerDir !== undefined) {
          <ng-template vListHeader>
            <ng-container [vListOutlet]="headerDir.templateRef"></ng-container>
          </ng-template>
        }
        @if (footerDir !== undefined) {
          <ng-template vListFooter>
            <ng-container [vListOutlet]="footerDir.templateRef"></ng-container>
          </ng-template>
        }
        @if (emptyDir !== undefined) {
          <ng-template vListEmpty>
            <ng-container [vListOutlet]="emptyDir.templateRef"></ng-container>
          </ng-template>
        }
        @if (separatorDir !== undefined) {
          <ng-template
            vListSeparator
            let-highlighted="highlighted"
            let-leadingItem="leadingItem"
            let-trailingItem="trailingItem"
          >
            <ng-container
              [vListOutlet]="separatorDir.templateRef"
              [vListOutletContext]="
                rowSeparatorContext(highlighted, leadingItem, trailingItem)
              "
            ></ng-container>
          </ng-template>
        }
      </VirtualizedList>
    } @else {
      <VirtualizedList
        [data]="data"
        [getItem]="getFlatItem"
        [getItemCount]="getFlatCount"
        [keyExtractor]="keyExtractor"
        [getItemLayout]="getItemLayout"
        [horizontal]="horizontal"
        [inverted]="inverted"
        [extraData]="extraData"
        (endReached)="endReached.emit($event)"
        [onEndReachedThreshold]="onEndReachedThreshold"
        (startReached)="startReached.emit($event)"
        [onStartReachedThreshold]="onStartReachedThreshold"
        (refresh)="refresh.emit()"
        [refreshRequested]="refresh.observed"
        [refreshing]="refreshing"
        [progressViewOffset]="progressViewOffset"
        (viewableItemsChanged)="viewableItemsChanged.emit($event)"
        [viewabilityConfig]="viewabilityConfig"
        [viewabilityConfigCallbackPairs]="viewabilityConfigCallbackPairs"
        (scrollToIndexFailed)="scrollToIndexFailed.emit($event)"
        [initialNumToRender]="initialNumToRender"
        [initialScrollIndex]="initialScrollIndex"
        [maxToRenderPerBatch]="maxToRenderPerBatch"
        [updateCellsBatchingPeriod]="updateCellsBatchingPeriod"
        [windowSize]="windowSize"
        [stickyHeaderIndices]="stickyHeaderIndices"
        [maintainVisibleContentPosition]="maintainVisibleContentPosition"
        [onScroll]="onScroll"
        [onScrollBeginDrag]="onScrollBeginDrag"
        [onScrollEndDrag]="onScrollEndDrag"
        [onMomentumScrollBegin]="onMomentumScrollBegin"
        [onMomentumScrollEnd]="onMomentumScrollEnd"
        [scrollEventThrottle]="scrollEventThrottle"
        [keyboardShouldPersistTaps]="keyboardShouldPersistTaps"
        [keyboardDismissMode]="keyboardDismissMode"
        [removeClippedSubviews]="resolvedRemoveClippedSubviews"
        [nestedScrollEnabled]="nestedScrollEnabled"
        [testID]="testID"
        [style]="resolvedStyle"
        [contentContainerStyle]="contentContainerStyle"
        [itemTemplate]="itemDir?.templateRef"
        [itemSeparatorTemplate]="separatorDir?.templateRef"
      >
        @if (headerDir !== undefined) {
          <ng-template vListHeader>
            <ng-container [vListOutlet]="headerDir.templateRef"></ng-container>
          </ng-template>
        }
        @if (footerDir !== undefined) {
          <ng-template vListFooter>
            <ng-container [vListOutlet]="footerDir.templateRef"></ng-container>
          </ng-template>
        }
        @if (emptyDir !== undefined) {
          <ng-template vListEmpty>
            <ng-container [vListOutlet]="emptyDir.templateRef"></ng-container>
          </ng-template>
        }
      </VirtualizedList>
    }
  `,
})
export class FlatList<ItemT = unknown>
  implements IFlatListInputs<ItemT>, IVirtualizedListHandle, DoCheck, OnChanges
{
  // The list's edge/viewability/failure events as real Angular events: `(endReached)="…"`, not
  // `[onEndReached]="…"` — re-emitted straight from the inner VirtualizedList's own @Output()s (see
  // the template's `(endReached)="endReached.emit($event)"` style forwarding above).
  @Output() readonly endReached = new EventEmitter<{
    distanceFromEnd: number;
  }>();
  @Output() readonly startReached = new EventEmitter<{
    distanceFromStart: number;
  }>();
  @Output() readonly refresh = new EventEmitter<void>();
  @Output() readonly viewableItemsChanged = new EventEmitter<
    IViewableItemsChangedInfo<ItemT>
  >();
  @Output() readonly scrollToIndexFailed = new EventEmitter<{
    index: number;
    highestMeasuredFrameIndex: number;
    averageItemLength: number;
  }>();
  @Input({ required: true }) data!: readonly ItemT[];
  // RN's FlatList spreads its props onto the VirtualizedList it renders, so `testID` lands on the
  // scroll view. Angular has no spread, and this one was simply missing: `<FlatList testID="x">`
  // compiled (a static attribute on a component tag is never checked), reached the non-painting
  // anchor host, and committed nowhere — so the list was untargetable by a test or an e2e selector
  // while looking perfectly healthy on screen. VirtualizedList has always declared it.
  @Input() testID?: string;
  @Input() numColumns?: number;
  @Input() columnWrapperStyle?: IStyleProp<IViewStyle> | string;
  @Input() keyExtractor?: (item: ItemT, index: number) => string;
  @Input() getItemLayout?: (
    data: unknown,
    index: number,
  ) => { length: number; offset: number; index: number };
  @Input() horizontal?: boolean;
  @Input() inverted?: boolean;
  @Input() extraData?: unknown;
  @Input() onEndReachedThreshold?: number;
  @Input() onStartReachedThreshold?: number;
  @Input() refreshing?: boolean | null;
  @Input() progressViewOffset?: number;
  @Input()
  viewabilityConfig?: IVirtualizedListProps<ItemT>['viewabilityConfig'];
  @Input()
  viewabilityConfigCallbackPairs?: IViewabilityConfigCallbackPair<ItemT>[];
  @Input() initialNumToRender?: number;
  @Input() initialScrollIndex?: number;
  @Input() maxToRenderPerBatch?: number;
  @Input() updateCellsBatchingPeriod?: number;
  @Input() windowSize?: number;
  @Input() stickyHeaderIndices?: number[];
  @Input() maintainVisibleContentPosition?: {
    minIndexForVisible: number;
    autoscrollToTopThreshold?: number;
  };
  @Input() onScroll?: IVirtualizedListProps<ItemT>['onScroll'];
  @Input()
  onScrollBeginDrag?: IVirtualizedListProps<ItemT>['onScrollBeginDrag'];
  @Input() onScrollEndDrag?: IVirtualizedListProps<ItemT>['onScrollEndDrag'];
  @Input()
  onMomentumScrollBegin?: IVirtualizedListProps<ItemT>['onMomentumScrollBegin'];
  @Input()
  onMomentumScrollEnd?: IVirtualizedListProps<ItemT>['onMomentumScrollEnd'];
  @Input() scrollEventThrottle?: number;
  @Input() keyboardShouldPersistTaps?: boolean | 'always' | 'never' | 'handled';
  @Input() keyboardDismissMode?: 'none' | 'on-drag' | 'interactive';
  @Input() removeClippedSubviews?: boolean;
  @Input() nestedScrollEnabled?: boolean;
  @Input() style?: IStyleProp<IViewStyle>;
  @Input() contentContainerStyle?: IStyleProp<IViewStyle>;

  // FlatList.js always sends it, defaulted per platform.
  get resolvedRemoveClippedSubviews(): boolean {
    return removeClippedSubviewsOrDefault(
      this.removeClippedSubviews,
      Platform.OS,
    );
  }

  // The app's cell + slot templates, captured for the multi-column re-stamp path. In the
  // single-column path they are ALSO projected through <ng-content> to the inner list and these
  // captures stay unused (the inner list's own @ContentChild resolves them across the projection).
  @ContentChild(VListItemDirective) itemDir?: VListItemDirective<ItemT>;
  @ContentChild(VListHeaderDirective) headerDir?: VListHeaderDirective;
  @ContentChild(VListFooterDirective) footerDir?: VListFooterDirective;
  @ContentChild(VListEmptyDirective) emptyDir?: VListEmptyDirective;
  @ContentChild(VListSeparatorDirective)
  separatorDir?: VListSeparatorDirective<ItemT>;

  // The composed inner list (whichever numColumns branch rendered). Its instance IS the
  // IVirtualizedListHandle, so FlatList's handle delegates straight to it.
  @ViewChild(VirtualizedList) private listRef?: VirtualizedList;

  // This component's OWN host — the non-painting anchor `class="..."` at the use site resolves
  // onto (see anchorHostStyle's doc comment) — NOT `listRef` above, which targets the real inner
  // `<VirtualizedList>` one level down (itself its own separate anchor host).
  private readonly elementRef = inject(ElementRef);

  // --- derived view state (recomputed in ngOnChanges, stable identity across CD) ---
  rows: IRow<ItemT>[] = [];
  // Angular's [style]="…" binding compiles to the built-in ɵɵstyleMap instruction (NOT a
  // regular @Input() property write), which only understands a flat object — an array (RN's
  // own `style={[a, b]}` composition idiom) crashes deep inside Angular's styling engine. So
  // every style value this component stamps onto a template `[style]=` binding is flattened
  // via the engine's own flattenStyle first, here at the source rather than at each call site.
  rowStyle: IViewStyle = flattenStyle([{ flexDirection: 'row' }]);
  rowViewabilityPairs?: IViewabilityConfigCallbackPair<IRow<ItemT>>[];
  readonly columnCellStyle: IViewStyle = { flex: 1 };
  resolvedStyle: IViewStyle | undefined = undefined;

  get columns(): number {
    return this.numColumns ?? SINGLE_COLUMN;
  }
  get isMultiColumn(): boolean {
    return this.columns > SINGLE_COLUMN;
  }

  // ngDoCheck, NOT ngOnChanges: a bare `class=` never becomes an @Input, so ngOnChanges does not
  // RUN for it and the merge froze at its creation value (a stranded tile on the ReactiveStyle
  // canary). stableAnchorStyle, not a bare flattenStyle, keeps `resolvedStyle`'s reference stable
  // across ticks that changed nothing - a fresh object every tick defeats VirtualizedList's own
  // dedup gate and free-runs CD (see stableAnchorStyle's doc comment).
  ngDoCheck(): void {
    this.resolvedStyle = stableAnchorStyle(
      this.elementRef,
      this.style,
      this.resolvedStyle,
    );
  }

  ngOnChanges(changes: SimpleChanges): void {
    if (changes['columnWrapperStyle'] !== undefined) {
      // A class-name string resolves through the shared registry before flattenStyle, which
      // only understands style objects/arrays.
      const resolvedColumnWrapperStyle =
        typeof this.columnWrapperStyle === 'string'
          ? resolveClassName(this.columnWrapperStyle)
          : this.columnWrapperStyle;
      this.rowStyle = flattenStyle([
        { flexDirection: 'row' },
        resolvedColumnWrapperStyle,
      ]);
    }
    if (changes['data'] !== undefined || changes['numColumns'] !== undefined) {
      this.rows = this.isMultiColumn
        ? chunkIntoRows(this.data, this.columns)
        : [];
      dlog(
        `Angular FlatList over ${this.data?.length ?? 0} items, ${this.columns} column(s)`,
      );
    }
    if (
      changes['viewabilityConfigCallbackPairs'] !== undefined ||
      changes['numColumns'] !== undefined
    ) {
      this.rowViewabilityPairs = this.buildRowViewabilityPairs();
    }
  }

  // ---- single-column data adaptation (plain array -> getItem/getItemCount) ----
  getFlatItem = (_data: unknown, index: number): ItemT => this.data[index];
  getFlatCount = (_data: unknown): number => this.data.length;

  // ---- multi-column data adaptation (the virtualized stream is rows) ----
  getRow = (_data: unknown, index: number): IRow<ItemT> => this.rows[index];
  getRowCount = (_data: unknown): number => this.rows.length;
  rowKey = (row: IRow<ItemT>, _index: number): string =>
    rowKeyExtractor(row, this.keyExtractor);

  // Viewability over rows expands back to per-item tokens, so the caller sees item-level
  // visibility, not row-level (shared expandRowViewability), matching Vue.
  rowViewableItemsChanged = (
    info: IViewableItemsChangedInfo<IRow<ItemT>>,
  ): void => {
    this.viewableItemsChanged.emit(
      expandRowViewability(info, this.keyExtractor),
    );
  };

  private buildRowViewabilityPairs():
    IViewabilityConfigCallbackPair<IRow<ItemT>>[] | undefined {
    return this.viewabilityConfigCallbackPairs?.map(pair => ({
      viewabilityConfig: pair.viewabilityConfig,
      onViewableItemsChanged: (
        rowInfo: IViewableItemsChangedInfo<IRow<ItemT>>,
      ): void => {
        pair.onViewableItemsChanged?.(
          expandRowViewability(rowInfo, this.keyExtractor),
        );
      },
    }));
  }

  // Lay out one row's N columns: every item shares the row's separators handle (the divider sits
  // between rows, not columns) and carries its absolute index (row.startIndex + column), like RN's
  // multi-column FlatList. Args arrive `unknown` from the template's `let` bindings (Angular cannot
  // type a generic structural directive's context), narrowed here — no `as`.
  rowCells(
    row: unknown,
    separators: unknown,
  ): { key: string; context: IVListItemContext<ItemT> }[] {
    if (!isRow<ItemT>(row)) return [];
    const handle = isSeparators(separators) ? separators : NOOP_SEPARATORS;
    return row.items.map((item, column) => {
      const index = row.startIndex + column;
      const key = this.keyExtractor
        ? this.keyExtractor(item, index)
        : String(index);
      return { key, context: { $implicit: item, index, separators: handle } };
    });
  }

  // The divider between rows shows real items (last of the row above, first of the row below), so the
  // app's separator template, typed on ItemT, sees items rather than the IRow wrapper. Args arrive
  // `unknown` from the template's `let` bindings, narrowed here.
  rowSeparatorContext(
    highlighted: unknown,
    leadingRow: unknown,
    trailingRow: unknown,
  ): IVListSeparatorContext<ItemT> {
    const isHighlighted = highlighted === true;
    return {
      $implicit: isHighlighted,
      highlighted: isHighlighted,
      leadingItem: isRow<ItemT>(leadingRow)
        ? lastItemOfRow(leadingRow)
        : undefined,
      trailingItem: isRow<ItemT>(trailingRow)
        ? firstItemOfRow(trailingRow)
        : undefined,
    };
  }

  // ---- imperative handle (RN FlatList surface) — delegates to the inner VirtualizedList ----

  scrollToOffset(params: { offset: number; animated?: boolean }): void {
    this.listRef?.scrollToOffset(params);
  }
  scrollToIndex(params: {
    index: number;
    animated?: boolean;
    viewOffset?: number;
    viewPosition?: number;
  }): void {
    this.listRef?.scrollToIndex(params);
  }
  scrollToItem(params: {
    item: unknown;
    animated?: boolean;
    viewPosition?: number;
  }): void {
    this.listRef?.scrollToItem(params);
  }
  scrollToEnd(params?: { animated?: boolean }): void {
    this.listRef?.scrollToEnd(params);
  }
  flashScrollIndicators(): void {
    this.listRef?.flashScrollIndicators();
  }
  getNativeScrollRef(): IScrollViewHandle | null {
    return this.listRef?.getNativeScrollRef() ?? null;
  }
  getScrollableNode(): IScrollViewHandle | null {
    return this.listRef?.getScrollableNode() ?? null;
  }
  getScrollResponder(): IScrollViewHandle | null {
    return this.listRef?.getScrollResponder() ?? null;
  }
  getScrollNode(): ISymbioteNode | null {
    return this.listRef?.getScrollNode() ?? null;
  }
  recordInteraction(): void {
    this.listRef?.recordInteraction();
  }
}

// adapters/react/src/components/flat-list/index.ts
// FlatList: the convenience surface over VirtualizedList. It takes a plain `data` array and
// derives getItem/getItemCount, so callers never touch the VirtualizedList data-access protocol.
// `numColumns` packs that many items into each row (a horizontal sub-View), so the virtualized
// stream is rows, not items (RN's FlatList). All windowing, viewability, batching, and imperative
// scrolling are inherited from VirtualizedList; the data shaping and the row/viewability/separator
// transforms are shared from @symbiote-native/components. This file only adapts to React's lifecycle
// (element creation + ref threading).

import {
  createElement,
  type ComponentType,
  type ReactElement,
  type ReactNode,
  type Ref,
} from 'react';
import {
  Platform,
  dlog,
  resolveClassName,
  type ISymbioteEvent,
} from '@symbiote-native/engine';
import {
  SINGLE_COLUMN,
  chunkIntoRows,
  expandRowViewability,
  firstItemOfRow,
  lastItemOfRow,
  removeClippedSubviewsOrDefault,
  rowKeyExtractor,
  type IRow,
} from '@symbiote-native/components';
import {
  VirtualizedList,
  type ISeparators,
  type ISeparatorProps,
  type IViewabilityConfig,
  type IViewabilityConfigCallbackPair,
  type IViewableItemsChangedInfo,
  type IVirtualizedListHandle,
} from '../virtualized-list';
import type {
  IAccessibilityProps,
  IAriaProps,
} from '@symbiote-native/components';
import type { IStyleProp, IViewStyle } from '../../utils/styles';

type IRenderItem<ItemT> = (info: {
  item: ItemT;
  index: number;
  separators: ISeparators;
}) => ReactNode;

// FlatList's imperative handle is exactly VirtualizedList's: scrollTo* forwarded
// down to the underlying list.
export type IFlatListHandle = IVirtualizedListHandle;

export interface IFlatListProps<ItemT> extends IAccessibilityProps, IAriaProps {
  data: readonly ItemT[];
  renderItem: IRenderItem<ItemT>;
  keyExtractor?: (item: ItemT, index: number) => string;
  getItemLayout?: (
    data: unknown,
    index: number,
  ) => { length: number; offset: number; index: number };
  numColumns?: number;
  // Style for the auto-generated row View when numColumns > 1 (RN's columnWrapperStyle). A bare
  // string resolves through the shared style registry, like `className` below.
  columnWrapperStyle?: IStyleProp<IViewStyle> | string;
  ItemSeparatorComponent?: ComponentType<ISeparatorProps<ItemT>>;
  ListHeaderComponent?: ComponentType<Record<string, never>> | ReactElement;
  ListFooterComponent?: ComponentType<Record<string, never>> | ReactElement;
  ListEmptyComponent?: ComponentType<Record<string, never>> | ReactElement;
  horizontal?: boolean;
  inverted?: boolean;
  extraData?: unknown;
  onEndReached?: (info: { distanceFromEnd: number }) => void;
  onEndReachedThreshold?: number;
  onStartReached?: (info: { distanceFromStart: number }) => void;
  onStartReachedThreshold?: number;
  onRefresh?: () => void;
  refreshing?: boolean | null;
  progressViewOffset?: number;
  onViewableItemsChanged?: (info: IViewableItemsChangedInfo<ItemT>) => void;
  viewabilityConfig?: IViewabilityConfig;
  viewabilityConfigCallbackPairs?: IViewabilityConfigCallbackPair<ItemT>[];
  onScrollToIndexFailed?: (info: {
    index: number;
    highestMeasuredFrameIndex: number;
    averageItemLength: number;
  }) => void;
  initialNumToRender?: number;
  initialScrollIndex?: number;
  maxToRenderPerBatch?: number;
  updateCellsBatchingPeriod?: number;
  windowSize?: number;
  maintainVisibleContentPosition?: {
    minIndexForVisible: number;
    autoscrollToTopThreshold?: number;
  };
  onScroll?: (event: ISymbioteEvent) => void;
  onScrollBeginDrag?: (event: ISymbioteEvent) => void;
  onScrollEndDrag?: (event: ISymbioteEvent) => void;
  onMomentumScrollBegin?: (event: ISymbioteEvent) => void;
  onMomentumScrollEnd?: (event: ISymbioteEvent) => void;
  scrollEventThrottle?: number;
  keyboardShouldPersistTaps?: boolean | 'always' | 'never' | 'handled';
  keyboardDismissMode?: 'none' | 'on-drag' | 'interactive';
  style?: IStyleProp<IViewStyle>;
  contentContainerStyle?: IStyleProp<IViewStyle>;
  // Forwarded onto the inner VirtualizedList like `style` — resolves through the shared style
  // registry.
  className?: string;
  // RN defaults it per platform (true on Android); see removeClippedSubviewsOrDefault.
  removeClippedSubviews?: boolean;
  nestedScrollEnabled?: boolean;
}

export function FlatList<ItemT>(
  props: IFlatListProps<ItemT> & { ref?: Ref<IFlatListHandle> },
): ReactElement {
  const {
    ref,
    data,
    renderItem,
    keyExtractor,
    numColumns = SINGLE_COLUMN,
    columnWrapperStyle,
    // onViewableItemsChanged/viewability are typed against ItemT here; in the multi-column path
    // the underlying stream is IRow<ItemT>, so they are dropped from `rest` and pulled out.
    onViewableItemsChanged,
    viewabilityConfigCallbackPairs,
    // ItemSeparatorComponent is typed on ItemT; the multi-column stream is IRow<ItemT>, so it is
    // wrapped there to unwrap rows back to items, exactly like viewability above.
    ItemSeparatorComponent,
    removeClippedSubviews: authoredRemoveClippedSubviews,
    ...ownRest
  } = props;
  // FlatList.js always sends it, defaulted per platform.
  const rest = {
    ...ownRest,
    removeClippedSubviews: removeClippedSubviewsOrDefault(
      authoredRemoveClippedSubviews,
      Platform.OS,
    ),
  };

  dlog(`FlatList over ${data.length} items, ${numColumns} column(s)`);

  if (numColumns <= SINGLE_COLUMN) {
    return createElement(VirtualizedList<ItemT>, {
      ref,
      data,
      getItem: (_source: unknown, index: number): ItemT => data[index],
      getItemCount: (): number => data.length,
      renderItem,
      keyExtractor,
      onViewableItemsChanged,
      viewabilityConfigCallbackPairs,
      ItemSeparatorComponent,
      ...rest,
    });
  }

  // Multi-column: the virtualized stream is rows. Each cell renders its items side by side in a
  // flex-row View so windowing accounts for whole rows.
  const rows = chunkIntoRows(data, numColumns);
  const resolvedColumnWrapperStyle =
    typeof columnWrapperStyle === 'string'
      ? resolveClassName(columnWrapperStyle)
      : columnWrapperStyle;
  const rowStyle: IStyleProp<IViewStyle> = [
    { flexDirection: 'row' },
    resolvedColumnWrapperStyle,
  ];

  const renderRow = (info: {
    item: IRow<ItemT>;
    index: number;
    separators: ISeparators;
  }): ReactNode => {
    const cells = info.item.items.map((item, column) => {
      const index = info.item.startIndex + column;
      const key = keyExtractor ? keyExtractor(item, index) : String(index);
      // The row IS the virtualized cell, so every item in it shares the row's separators handle
      // (the divider sits between rows, not columns), like RN's multi-column FlatList.
      return createElement(
        'view',
        { key, style: { flex: 1 } },
        renderItem({ item, index, separators: info.separators }),
      );
    });
    return createElement('view', { style: rowStyle }, ...cells);
  };

  // Viewability over rows expands back to per-item tokens so the caller sees item-level
  // visibility, not row-level (shared expandRowViewability).
  const rowOnViewableItemsChanged =
    onViewableItemsChanged !== undefined
      ? (rowInfo: IViewableItemsChangedInfo<IRow<ItemT>>): void => {
          onViewableItemsChanged(expandRowViewability(rowInfo, keyExtractor));
        }
      : undefined;
  const rowViewabilityPairs = viewabilityConfigCallbackPairs?.map(pair => ({
    viewabilityConfig: pair.viewabilityConfig,
    onViewableItemsChanged: (
      rowInfo: IViewableItemsChangedInfo<IRow<ItemT>>,
    ): void => {
      pair.onViewableItemsChanged(expandRowViewability(rowInfo, keyExtractor));
    },
  }));

  // The divider between rows shows real items (last of the row above, first of the row below), so
  // the user's separator, typed on ItemT, sees items rather than the IRow wrapper.
  const rowSeparatorComponent:
    ComponentType<ISeparatorProps<IRow<ItemT>>> | undefined =
    ItemSeparatorComponent === undefined
      ? undefined
      : (rowProps): ReactNode =>
          createElement(ItemSeparatorComponent, {
            ...rowProps,
            leadingItem: lastItemOfRow(rowProps.leadingItem),
            trailingItem: firstItemOfRow(rowProps.trailingItem),
          });

  return createElement(VirtualizedList<IRow<ItemT>>, {
    ref,
    data: rows,
    getItem: (_source: unknown, index: number): IRow<ItemT> => rows[index],
    getItemCount: (): number => rows.length,
    renderItem: renderRow,
    keyExtractor: (row: IRow<ItemT>): string =>
      rowKeyExtractor(row, keyExtractor),
    onViewableItemsChanged: rowOnViewableItemsChanged,
    viewabilityConfigCallbackPairs: rowViewabilityPairs,
    ItemSeparatorComponent: rowSeparatorComponent,
    ...rest,
  });
}
