// packages/navigation/src/react/drawer-screen.ts
// Drawer.Screen: a declarative marker, never rendered on its own — Drawer reads its props via
// React.Children to build the static name -> {component, options} registry, then mounts the
// FOCUSED route's component. Mirrors react/tab-screen.ts (Tab's twin — the closer sibling, both
// are fixed-route-list/no-push navigators) and react/screen.ts (Stack's twin); see CLAUDE.md
// <third_party_rn_packages_are_react_only> — this and Drawer import nothing from react-native.

import type { FC, ReactElement } from 'react';
import type { IDrawerScreenOptions, IRoute } from '../core';
import type { IDrawerNavigatorHandle } from './drawer';

export type IDrawerScreenComponentProps = {
  route: IRoute<unknown>;
  navigation: IDrawerNavigatorHandle;
};

export type IDrawerScreenOptionsResolver = (
  props: IDrawerScreenComponentProps,
) => IDrawerScreenOptions;

export type IDrawerScreenProps = {
  name: string;
  component: FC<IDrawerScreenComponentProps>;
  options?: IDrawerScreenOptions | IDrawerScreenOptionsResolver;
  initialParams?: unknown;
};

export function DrawerScreen(_props: IDrawerScreenProps): ReactElement | null {
  return null;
}

// packages/navigation/src/svelte/drawer-screen.svelte
<script lang="ts">
  // Drawer.Screen: a declarative marker that paints nothing, registered through the same
  // context-based collector Stack.Screen/Tab.Screen use (screen-registry.ts). See CLAUDE.md
  // <third_party_rn_packages_are_react_only> - this and Drawer import nothing from react-native.
  import { collectScreen } from './screen-registry';
  import type { IDrawerScreenProps } from './drawer-screen-props';

  let { name, component, options, initialParams }: IDrawerScreenProps = $props();

  collectScreen('drawer', {
    get name(): IDrawerScreenProps['name'] {
      return name;
    },
    get component(): IDrawerScreenProps['component'] {
      return component;
    },
    get options(): IDrawerScreenProps['options'] {
      return options;
    },
    get initialParams(): unknown {
      return initialParams;
    },
  });
</script>
