// adapters/svelte/src/components/RefreshControl.svelte
<script lang="ts" module>
  // RefreshControl primitive. On iOS this is the PullToRefreshView Fabric node that lives INSIDE
  // a ScrollView (a sibling of the content container), giving the pull-to-refresh gesture. On
  // Android it is AndroidSwipeRefreshLayout and WRAPS the scroll view (a childless-on-iOS,
  // wraps-on-Android shape — see refresh-control-props.ts). `refreshing` is a controlled prop:
  // the parent owns it and pushes it down each commit; native reports the gesture via the direct
  // `topRefresh` event, which the engine routes to the host's `onRefresh` bag entry.
  import type { IRefreshControlProps } from './refresh-control-props';

  export type { IRefreshControlProps };
</script>

<script lang="ts">
  import { dlog } from '@symbiote-native/engine';
  import { resolveAccessibilityProps } from '@symbiote-native/components';
  import { createAttachmentsSync } from '../runes/attachments';
  import type { ShimElement } from '../dom-shim';

  let { children, ...rest }: IRefreshControlProps = $props();

  dlog('RefreshControl -> PullToRefreshView');
  dlog(`RefreshControl refreshing=${String(rest.refreshing)}`);
  if (rest.enabled !== undefined)
    dlog(`RefreshControl enabled=${String(rest.enabled)} (Android-only)`);
  if (rest.onRefresh !== undefined)
    dlog('RefreshControl onRefresh listener wired');

  const bag = $derived(resolveAccessibilityProps(rest));

  // See View.svelte's note on `{@attach}`.
  let hostShim = $state.raw<ShimElement | null>(null);
  const syncAttachments = createAttachmentsSync();
  $effect(() => {
    syncAttachments(hostShim, rest);
  });
</script>

<symbiote-refresh-control p={bag} bind:this={hostShim}>
  {@render children?.()}
</symbiote-refresh-control>

// packages/react/src/refresh-control.ts
// RefreshControl primitive. On iOS this is the PullToRefreshView Fabric node that
// lives INSIDE a ScrollView (a sibling of the content container), giving the
// pull-to-refresh gesture. `refreshing` is a controlled prop — the parent owns it
// and pushes it down each commit; native reports the gesture via the direct
// `topRefresh` event, which shared routes to the `refresh` listener (onRefresh).

import { createElement, type FC, type ReactNode } from 'react'
import { dlog } from '@symbiote/shared'

export interface RefreshControlProps {
  refreshing: boolean
  // RN's onRefresh is `() => void | Promise<void>` — the handler may be async; the
  // promise is fire-and-forget (native already starts refreshing on the gesture).
  onRefresh?: () => void | Promise<void>
  tintColor?: string
  title?: string
  titleColor?: string
  progressViewOffset?: number
  // Android-only. RN's iOS RefreshControl.render() destructures `enabled` OUT
  // before spreading to PullToRefreshView, so iOS native never receives it. We
  // target PullToRefreshView (iOS-first), so it is stripped below, not forwarded.
  enabled?: boolean
  // On Android the RefreshControl WRAPS the ScrollView (ADR 0020), so it receives the
  // scroll view as its child via cloneElement. On iOS it is a childless sibling, so this
  // is undefined there — passing it through is harmless.
  children?: ReactNode
}

export const RefreshControl: FC<RefreshControlProps> = (props) => {
  const { enabled: _enabled, children, ...nativeProps } = props
  dlog('RefreshControl -> PullToRefreshView')
  dlog(`RefreshControl refreshing=${String(props.refreshing)}`)
  if (props.onRefresh !== undefined) dlog('RefreshControl onRefresh listener wired')
  return createElement('symbiote-refresh-control', { ...nativeProps }, children)
}
