// packages/navigation-bar/src/solid/navigation-bar.ts
// Solid twin of `../react`/`../vue`'s `NavigationBar`, same shared stack core - only the
// lifecycle wiring differs per adapter (`components_split_logic_view_lifecycle`)

import { createEffect, onCleanup, onMount } from 'solid-js';
import { createColorScheme } from '@symbiote-native/solid';
import {
  popStackEntry,
  pushStackEntry,
  replaceStackEntry,
  type INavigationBarProps,
  type INavigationBarStackEntry,
} from '../core';

export function NavigationBar(props: INavigationBarProps): null {
  const colorScheme = createColorScheme();
  let stackEntry: INavigationBarStackEntry | null = null;

  onMount(() => {
    stackEntry = pushStackEntry({ style: props.style, hidden: props.hidden });
  });

  onCleanup(() => {
    if (stackEntry) popStackEntry(stackEntry);
  });

  createEffect(() => {
    const style = props.style;
    const hidden = props.hidden;
    colorScheme();
    if (stackEntry)
      stackEntry = replaceStackEntry(stackEntry, { style, hidden });
  });

  return null;
}

// packages/navigation-bar/src/angular/navigation-bar.ts
// Angular twin of `../react`/`../vue`/`../solid`/`../svelte`'s `NavigationBar`, same shared
// stack core - only the lifecycle wiring differs per adapter
// (`components_split_logic_view_lifecycle`)

import {
  Component,
  effect,
  inject,
  Input,
  type OnChanges,
  type OnDestroy,
  type OnInit,
} from '@angular/core';
import { ColorSchemeService } from '@symbiote-native/angular';
import {
  popStackEntry,
  pushStackEntry,
  replaceStackEntry,
  type INavigationBarStackEntry,
  type INavigationBarStyle,
} from '../core';

@Component({
  selector: 'navigation-bar',
  standalone: true,
  template: '',
})
export class NavigationBar implements OnInit, OnChanges, OnDestroy {
  @Input() style?: INavigationBarStyle;
  @Input() hidden?: boolean;

  private readonly colorScheme = inject(ColorSchemeService).colorScheme;
  private stackEntry: INavigationBarStackEntry | null = null;
  private isInitialized = false;

  constructor() {
    effect(() => {
      this.colorScheme();
      if (this.stackEntry) {
        this.stackEntry = replaceStackEntry(this.stackEntry, {
          style: this.style,
          hidden: this.hidden,
        });
      }
    });
  }

  ngOnInit(): void {
    this.stackEntry = pushStackEntry({
      style: this.style,
      hidden: this.hidden,
    });
    this.isInitialized = true;
  }

  ngOnChanges(): void {
    if (!this.isInitialized || !this.stackEntry) return;
    this.stackEntry = replaceStackEntry(this.stackEntry, {
      style: this.style,
      hidden: this.hidden,
    });
  }

  ngOnDestroy(): void {
    if (this.stackEntry) popStackEntry(this.stackEntry);
  }
}
