// examples/expo-vue-sfc/screens/AppMetricsReport.vue
<script setup lang="ts">
import { ref } from 'vue';
import { reportError } from '@symbiote-native/app-metrics/vue';
import type { IReportErrorInput } from '@symbiote-native/app-metrics/vue';
import CallConsole from '../components/CallConsole.vue';
import Card from '../components/Card.vue';
import ChoiceRow from '../components/ChoiceRow.vue';
import Field from '../components/Field.vue';
import ToggleRow from '../components/ToggleRow.vue';
import { lineColorOf } from '../components/line-color';
import { ROUTE_NAME } from '../routes';
import { SOURCE_CHOICES } from './app-metrics-helpers';

const color = lineColorOf(ROUTE_NAME.AppMetrics);

const source = ref<IReportErrorInput['source']>('reportedByUser');
const type = ref('CanaryError');
const message = ref('Reported from the canary');
const stacktrace = ref('at ReportCard (AppMetricsScreen.tsx)');
const componentStack = ref('');
const isFatal = ref(false);

const calls = [
  {
    label: 'reportError',
    run: async () =>
      reportError({
        source: source.value,
        type: type.value,
        message: message.value,
        stacktrace: stacktrace.value,
        componentStack: componentStack.value === '' ? undefined : componentStack.value,
        isFatal: isFatal.value,
      }),
  },
];
</script>

<template>
  <Card testID="app-metrics-report-card" title="reportError input">
    <ChoiceRow
      testID="app-metrics-source"
      label="source"
      :options="SOURCE_CHOICES"
      :value="source"
      :onChange="next => (source = next)"
      :color="color"
    />
    <Field
      testID="app-metrics-type-input"
      label="type"
      :value="type"
      :onChange="next => (type = next)"
    />
    <Field
      testID="app-metrics-message-input"
      label="message"
      :value="message"
      :onChange="next => (message = next)"
    />
    <Field
      testID="app-metrics-stack-input"
      label="stacktrace"
      :value="stacktrace"
      :onChange="next => (stacktrace = next)"
    />
    <Field
      testID="app-metrics-component-stack-input"
      label="componentStack"
      :value="componentStack"
      :onChange="next => (componentStack = next)"
    />
    <ToggleRow
      testID="app-metrics-fatal-switch"
      label="isFatal"
      :value="isFatal"
      :onChange="next => (isFatal = next)"
      :color="color"
    />
  </Card>
  <CallConsole prefix="app-metrics-report" title="Error reporting" :color="color" :calls="calls" />
</template>

// examples/expo-angular/src/screens/AppMetricsReport.ts
import { Component, signal } from '@angular/core';
import { reportError } from '@symbiote-native/app-metrics/angular';
import type { IReportErrorInput } from '@symbiote-native/app-metrics/angular';
import { CallConsole } from '../components/CallConsole';
import { Card } from '../components/Card';
import { ChoiceRow } from '../components/ChoiceRow';
import { Field } from '../components/Field';
import { ToggleRow } from '../components/ToggleRow';
import type { ICall } from '../components/call-console';
import { lineColorOf } from '../components/line-color';
import { ROUTE_NAME } from '../routes';
import { SOURCE_CHOICES } from './app-metrics-helpers';

@Component({
  selector: 'AppMetricsReport',
  standalone: true,
  imports: [CallConsole, Card, ChoiceRow, Field, ToggleRow],
  template: `
    <Card testID="app-metrics-report-card" title="reportError input">
      <ChoiceRow
        testID="app-metrics-source"
        label="source"
        [options]="sourceChoices"
        [(value)]="source"
        [color]="color"
      />
      <Field testID="app-metrics-type-input" label="type" [(value)]="type" />
      <Field
        testID="app-metrics-message-input"
        label="message"
        [(value)]="message"
      />
      <Field
        testID="app-metrics-stack-input"
        label="stacktrace"
        [(value)]="stacktrace"
      />
      <Field
        testID="app-metrics-component-stack-input"
        label="componentStack"
        [(value)]="componentStack"
      />
      <ToggleRow
        testID="app-metrics-fatal-switch"
        label="isFatal"
        [(value)]="isFatal"
        [color]="color"
      />
    </Card>
    <CallConsole
      prefix="app-metrics-report"
      title="Error reporting"
      [color]="color"
      [calls]="calls"
    />
  `,
})
export class AppMetricsReport {
  readonly color = lineColorOf(ROUTE_NAME.AppMetrics);
  readonly sourceChoices = SOURCE_CHOICES;

  readonly source = signal<IReportErrorInput['source']>('reportedByUser');
  readonly type = signal('CanaryError');
  readonly message = signal('Reported from the canary');
  readonly stacktrace = signal('at ReportCard (AppMetricsScreen.tsx)');
  readonly componentStack = signal('');
  readonly isFatal = signal(false);

  readonly calls: ICall[] = [
    {
      label: 'reportError',
      run: async () =>
        reportError({
          source: this.source(),
          type: this.type(),
          message: this.message(),
          stacktrace: this.stacktrace(),
          componentStack:
            this.componentStack() === '' ? undefined : this.componentStack(),
          isFatal: this.isFatal(),
        }),
    },
  ];
}
