// examples/expo-vue-sfc/screens/AuthSessionSplitHookFlow.vue
<script setup lang="ts">
import { computed } from 'vue';
import {
  AuthRequest,
  useAuthRequestResult,
  useLoadedAuthRequest,
} from '@symbiote-native/auth-session/vue';
import type { IDiscoveryDocument } from '@symbiote-native/auth-session/vue';
import ActionButton from '../components/ActionButton.vue';
import ResultRow from '../components/ResultRow.vue';
import { toRequestConfig } from './auth-session-form';
import type { IForm } from './auth-session-form';

const props = defineProps<{ form: IForm; discovery: IDiscoveryDocument | null; color: string }>();

const request = useLoadedAuthRequest(
  () => toRequestConfig(props.form),
  () => props.discovery,
  AuthRequest,
);
const [result, promptAsync] = useAuthRequestResult(request, () => props.discovery);

const stateText = computed(
  () =>
    `${request.value === null ? 'request loading' : 'request ready'}, result ${result.value?.type ?? 'none'}`,
);
</script>

<template>
  <ResultRow
    testID="auth-session-split-state"
    label="useLoadedAuthRequest + useAuthRequestResult"
    :value="stateText"
  />
  <ActionButton
    testID="auth-session-split-prompt"
    title="promptAsync from useAuthRequestResult"
    :onPress="() => promptAsync()"
    :color="color"
  />
</template>

// examples/expo-angular/src/screens/AuthSessionSplitHookFlow.ts
import { Component, computed, input } from '@angular/core';
import {
  AuthRequest,
  injectAuthRequestResult,
  injectLoadedAuthRequest,
} from '@symbiote-native/auth-session/angular';
import type { IDiscoveryDocument } from '@symbiote-native/auth-session/angular';
import { ActionButton } from '../components/ActionButton';
import { ResultRow } from '../components/ResultRow';
import { toRequestConfig } from './auth-session-form';
import type { IForm } from './auth-session-form';

@Component({
  selector: 'AuthSessionSplitHookFlow',
  standalone: true,
  imports: [ActionButton, ResultRow],
  template: `
    <ResultRow
      testID="auth-session-split-state"
      label="useLoadedAuthRequest + useAuthRequestResult"
      [value]="stateText()"
    />
    <ActionButton
      testID="auth-session-split-prompt"
      title="promptAsync from useAuthRequestResult"
      [color]="color()"
      (press)="prompt()"
    />
  `,
})
export class AuthSessionSplitHookFlow {
  readonly form = input.required<IForm>();
  readonly discovery = input.required<IDiscoveryDocument | null>();
  readonly color = input.required<string>();

  private readonly request = injectLoadedAuthRequest(
    () => toRequestConfig(this.form()),
    () => this.discovery(),
    AuthRequest,
  );
  private readonly hook = injectAuthRequestResult(this.request, () =>
    this.discovery(),
  );

  readonly stateText = computed(() => {
    const [result] = this.hook;
    return `${this.request() === null ? 'request loading' : 'request ready'}, result ${result()?.type ?? 'none'}`;
  });

  prompt(): void {
    const [, promptAsync] = this.hook;
    void promptAsync();
  }
}
