// examples/expo-vue-sfc/screens/PhotoScenario.vue
<script setup lang="ts">
import { ref } from 'vue';
import type { ICameraCapturedPicture, ICameraViewHandle } from '@symbiote-native/camera/vue';
import ActionButton from '../components/ActionButton.vue';
import ChoiceRow from '../components/ChoiceRow.vue';
import ResultRow from '../components/ResultRow.vue';
import Scenario from '../components/Scenario.vue';
import ToggleRow from '../components/ToggleRow.vue';
import { QUALITIES, errorLine } from './camera-shared';

const props = defineProps<{ camera: ICameraViewHandle | null; color: string }>();

const picture = ref<ICameraCapturedPicture | null>(null);
const quality = ref(0.7);
const isSilent = ref(false);
const isRaw = ref(false);
const line = ref('no photo yet');

async function shoot(): Promise<void> {
  line.value = 'shooting…';
  try {
    const result = await props.camera?.takePictureAsync({
      quality: quality.value,
      shutterSound: !isSilent.value,
      skipProcessing: isRaw.value,
      exif: true,
    });
    picture.value = result ?? null;
    line.value = result === undefined ? 'no picture returned' : `${result.width}x${result.height} ${result.format}`;
  } catch (error) {
    line.value = `failed: ${errorLine(error)}`;
  }
}
</script>

<template>
  <Scenario
    testID="camera-photo-scenario"
    title="Take a photo for a profile, a receipt or a document"
    why="The core camera task. The app shows a live preview, takes a still on a button and gets a file it can upload or show. Quality trades size for sharpness."
    :steps="['Allow the camera and wait for the preview', 'Press Take photo', 'Change the quality to 0.3 and shoot again']"
    expect="A thumbnail of the shot appears with its pixel size. Quality 0.3 gives the same pixel size as 1, only the file gets smaller and softer."
  >
    <ChoiceRow
      testID="camera-quality"
      label="quality"
      :color="color"
      :value="quality"
      :options="QUALITIES"
      @change="value => (quality = value)"
    />
    <ToggleRow
      testID="camera-silent"
      label="shutter sound off (not allowed everywhere)"
      :value="isSilent"
      :color="color"
      @change="value => (isSilent = value)"
    />
    <ToggleRow
      testID="camera-raw"
      label="skipProcessing: the raw sensor image"
      :value="isRaw"
      :color="color"
      @change="value => (isRaw = value)"
    />
    <ActionButton
      testID="camera-take-photo"
      title="Take photo"
      :color="color"
      @press="shoot"
    />
    <ResultRow
      testID="camera-photo-result"
      label="takePictureAsync"
      :value="line"
    />
    <template v-if="picture !== null">
      <image
        testID="camera-photo"
        :source="{ uri: picture.uri }"
        class="cam-photo"
      />
      <ResultRow
        v-if="picture.exif !== undefined"
        testID="camera-photo-exif"
        label="EXIF tags"
        :value="String(Object.keys(picture.exif).length)"
      />
    </template>
  </Scenario>
</template>

// examples/expo-angular/src/screens/PhotoScenario.ts
import { Component, computed, input, signal } from '@angular/core';
import { SYMBIOTE_ELEMENTS } from '@symbiote-native/angular';
import type {
  CameraView,
  ICameraCapturedPicture,
} from '@symbiote-native/camera/angular';
import { ActionButton } from '../components/ActionButton';
import { ChoiceRow } from '../components/ChoiceRow';
import { ResultRow } from '../components/ResultRow';
import { Scenario } from '../components/Scenario';
import { ToggleRow } from '../components/ToggleRow';
import { QUALITIES, errorLine } from './camera-shared';

@Component({
  selector: 'PhotoScenario',
  standalone: true,
  imports: [
    ActionButton,
    ChoiceRow,
    ResultRow,
    Scenario,
    SYMBIOTE_ELEMENTS,
    ToggleRow,
  ],
  template: `
    <Scenario
      testID="camera-photo-scenario"
      title="Take a photo for a profile, a receipt or a document"
      why="The core camera task. The app shows a live preview, takes a still on a button and gets a file it can upload or show. Quality trades size for sharpness."
      [steps]="steps"
      expect="A thumbnail of the shot appears with its pixel size. Quality 0.3 gives the same pixel size as 1, only the file gets smaller and softer."
    >
      <ChoiceRow
        testID="camera-quality"
        label="quality"
        [color]="color()"
        [options]="qualities"
        [(value)]="quality"
      />
      <ToggleRow
        testID="camera-silent"
        label="shutter sound off (not allowed everywhere)"
        [color]="color()"
        [(value)]="isSilent"
      />
      <ToggleRow
        testID="camera-raw"
        label="skipProcessing: the raw sensor image"
        [color]="color()"
        [(value)]="isRaw"
      />
      <ActionButton
        testID="camera-take-photo"
        title="Take photo"
        [color]="color()"
        (press)="shoot()"
      />
      <ResultRow
        testID="camera-photo-result"
        label="takePictureAsync"
        [value]="line()"
      />
      @if (picture(); as shot) {
        <image
          testID="camera-photo"
          [source]="photoSource()"
          class="cam-photo"
        />
        @if (shot.exif !== undefined) {
          <ResultRow
            testID="camera-photo-exif"
            label="EXIF tags"
            [value]="exifCount()"
          />
        }
      }
    </Scenario>
  `,
})
export class PhotoScenario {
  readonly camera = input<CameraView | undefined>();
  readonly color = input.required<string>();

  readonly steps = [
    'Allow the camera and wait for the preview',
    'Press Take photo',
    'Change the quality to 0.3 and shoot again',
  ];
  readonly qualities = QUALITIES;
  readonly picture = signal<ICameraCapturedPicture | null>(null);
  readonly quality = signal(0.7);
  readonly isSilent = signal(false);
  readonly isRaw = signal(false);
  readonly line = signal('no photo yet');

  readonly photoSource = computed(() => ({ uri: this.picture()?.uri ?? '' }));
  readonly exifCount = computed(() =>
    String(Object.keys(this.picture()?.exif ?? {}).length),
  );

  async shoot(): Promise<void> {
    this.line.set('shooting…');
    try {
      const result = await this.camera()?.takePictureAsync({
        quality: this.quality(),
        shutterSound: !this.isSilent(),
        skipProcessing: this.isRaw(),
        exif: true,
      });
      this.picture.set(result ?? null);
      this.line.set(
        result === undefined
          ? 'no picture returned'
          : `${result.width}x${result.height} ${result.format}`,
      );
    } catch (error) {
      this.line.set(`failed: ${errorLine(error)}`);
    }
  }
}
