// examples/vue-sfc/components/JsFrameRateMeter.vue
<!--
  JS-thread frame rate. A requestAnimationFrame loop measures the delta between consecutive
  frames, reports the averaged rate over a half-second window, and keeps a running count of frames
  that arrived later than one and a half budgets — the visible cost of a long commit. Vue SFC twin
  of .examples/react/components/JsFrameRateMeter.tsx, numbers and testIDs identical so the four
  canaries' meters can be read against each other.
-->
<script lang="ts">
// `readCommitProfile()` is read-and-RESET, and this meter calls it once per window off rAF. A
// benchmark step that wants the profile of its OWN commit must stop the meter first: otherwise a
// window can close inside the step and consume the step's numbers, leaving a plausible zero and no
// sign that anything was lost.
//
// A mutable module field, not a prop. A prop change re-renders the meter, and that re-render is a
// commit landing inside the very window being measured — which would both perturb the duration and
// (because the screen's post-commit hook stops the clock on ANY commit) risk settling the step
// early against the wrong commit. A plain object rather than a ref for the same reason: a reactive
// read would tie the gate to the render.
export const commitProfileGate = { isHeldByBenchmark: false };
</script>

<script setup lang="ts">
import { onMounted, onUnmounted, ref } from 'vue';
import { readCommitProfile } from '@symbiote-native/engine';
import ActionButton from './ActionButton.vue';

defineProps<{ accent: string }>();

// 60 Hz budget. Frames are timed on the JS thread only: requestAnimationFrame is scheduled by
// JS, so a stall here is a stall in the code we actually optimize. The native UI thread keeps
// compositing at 60/120 Hz regardless, which is why a native FPS readout would stay flat and
// tell us nothing about the engine's commit cost.
const FRAME_BUDGET_MS = 1000 / 60;

// 1.5x slack so ordinary scheduler jitter (a frame landing a millisecond or two late) is not
// counted as jank - only a frame that missed its slot outright.
const DROPPED_FRAME_THRESHOLD_MS = FRAME_BUDGET_MS * 1.5;

// requestAnimationFrame stops ticking while the app is backgrounded, so the first frame after it
// returns carries the whole suspended interval. That is not jank and must not enter the stats -
// an idle stretch once reported a 102-second "worst frame".
const SUSPENDED_FRAME_MS = 1_000;

// The rate is averaged over a window instead of published per frame: a state write at 60 Hz would
// itself dominate the very commit path this meter is supposed to observe.
const SAMPLE_WINDOW_MS = 500;

// What the engine's reconcile walk cost inside the last window, next to the frame numbers so the
// two can be read against each other: the walk is a term in every adapter's frame budget.
//
// Reported as two halves, never as `walkMs / nodesVisited`. Dirty-marking means the denominator
// counts only the nodes reconcile did NOT skip, while the numerator still covers everything it does
// (the JSI createNode/appendChild calls included), so that ratio inflates by the skip factor: 13.4
// us/node without dirty-marking, 438 us/node with it, on a device that had got ~2x faster. So
// `nodesPerCommit` is the skip itself (read against the screen's node count) and `msPerCommit` is
// what a commit costs. A true per-node figure needs a full walk - a cold mount, where nothing is
// skippable.
type IWalkSample = {
  sharePercent: number;
  nodesPerCommit: number;
  msPerCommit: number;
};

const EMPTY_WALK_SAMPLE: IWalkSample = {
  sharePercent: 0,
  nodesPerCommit: 0,
  msPerCommit: 0,
};

const framesPerSecond = ref(0);
const droppedFrames = ref(0);
const worstFrameMs = ref(0);
const walk = ref<IWalkSample>(EMPTY_WALK_SAMPLE);

let handle = 0;
let stopped = false;
// Accumulated off the render, published at window close: a ref write per dropped frame would put
// a commit inside whatever the meter is watching, and inside a gated step it would defeat the gate.
let droppedTotal = 0;
let worstMs = 0;

onMounted(() => {
  let previousFrameAt = performance.now();
  let windowStartedAt = previousFrameAt;
  let framesInWindow = 0;

  const onFrame = (): void => {
    if (stopped) return;
    const now = performance.now();
    const deltaMs = now - previousFrameAt;
    previousFrameAt = now;
    framesInWindow += 1;

    if (deltaMs < SUSPENDED_FRAME_MS) {
      if (deltaMs > DROPPED_FRAME_THRESHOLD_MS) droppedTotal += 1;
      if (deltaMs > worstMs) worstMs = deltaMs;
    }

    const windowMs = now - windowStartedAt;
    // While a benchmark step holds the gate the whole window-close block is skipped, publish and
    // reset alike: the readCommitProfile() below would eat the step's profile, and the ref writes
    // would put an extra commit inside its measured window. The window simply grows and publishes
    // once, longer, after the step releases.
    if (windowMs >= SAMPLE_WINDOW_MS && !commitProfileGate.isHeldByBenchmark) {
      framesPerSecond.value = Math.round((framesInWindow * 1000) / windowMs);
      droppedFrames.value = droppedTotal;
      worstFrameMs.value = worstMs;
      // Read-and-reset, once per window, so each sample covers exactly the window just closed
      // rather than an ever-growing total.
      const commitProfile = readCommitProfile();
      walk.value = {
        sharePercent: (commitProfile.walkMs / windowMs) * 100,
        nodesPerCommit:
          commitProfile.commits === 0
            ? 0
            : commitProfile.nodesVisited / commitProfile.commits,
        msPerCommit:
          commitProfile.commits === 0
            ? 0
            : commitProfile.walkMs / commitProfile.commits,
      };
      framesInWindow = 0;
      windowStartedAt = now;
    }

    handle = requestAnimationFrame(onFrame);
  };

  handle = requestAnimationFrame(onFrame);
});

onUnmounted(() => {
  stopped = true;
  cancelAnimationFrame(handle);
});

const onReset = (): void => {
  droppedTotal = 0;
  worstMs = 0;
  droppedFrames.value = 0;
  worstFrameMs.value = 0;
  walk.value = EMPTY_WALK_SAMPLE;
};
</script>

<template>
  <view class="bench-meter">
    <text class="section-label">
      JS-THREAD FRAME RATE
    </text>
    <view class="bench-meter-row">
      <view class="bench-metric">
        <text
          testID="bench-fps"
          class="bench-metric-value"
          :style="{ color: accent }"
        >
          {{ framesPerSecond }}
        </text>
        <text class="bench-metric-label">
          fps
        </text>
      </view>
      <view class="bench-metric">
        <text
          testID="bench-dropped"
          class="bench-metric-value"
          :style="{ color: accent }"
        >
          {{ droppedFrames }}
        </text>
        <text class="bench-metric-label">
          dropped
        </text>
      </view>
      <view class="bench-metric">
        <text
          class="bench-metric-value"
          :style="{ color: accent }"
        >
          {{
            worstFrameMs.toFixed(0)
          }}
        </text>
        <text class="bench-metric-label">
          worst ms
        </text>
      </view>
    </view>
    <text class="section-label">
      ENGINE RECONCILE WALK
    </text>
    <view class="bench-meter-row">
      <view class="bench-metric">
        <text
          testID="bench-walk-share"
          class="bench-metric-value"
          :style="{ color: accent }"
        >
          {{ walk.sharePercent.toFixed(1) }}
        </text>
        <text class="bench-metric-label">
          % of window
        </text>
      </view>
      <view class="bench-metric">
        <text
          testID="bench-walk-nodes-per-commit"
          class="bench-metric-value"
          :style="{ color: accent }"
        >
          {{ walk.nodesPerCommit.toFixed(0) }}
        </text>
        <text class="bench-metric-label">
          nodes / commit
        </text>
      </view>
      <view class="bench-metric">
        <text
          testID="bench-walk-ms-per-commit"
          class="bench-metric-value"
          :style="{ color: accent }"
        >
          {{ walk.msPerCommit.toFixed(1) }}
        </text>
        <text class="bench-metric-label">
          ms / commit
        </text>
      </view>
    </view>
    <ActionButton
      testID="bench-fps-reset"
      title="Reset frame counters"
      :onPress="onReset"
      :color="accent"
    />
  </view>
</template>

// examples/react/components/JsFrameRateMeter.tsx
import { useEffect, useRef, useState } from 'react';
import { readCommitProfile } from '@symbiote-native/engine';
import { ActionButton } from './ActionButton';

// 60 Hz budget. Frames are timed on the JS thread only: requestAnimationFrame is scheduled by
// JS, so a stall here is a stall in the code we actually optimize. The native UI thread keeps
// compositing at 60/120 Hz regardless, which is why a native FPS readout would stay flat and
// tell us nothing about the engine's commit cost.
const FRAME_BUDGET_MS = 1000 / 60;

// 1.5x slack so ordinary scheduler jitter (a frame landing a millisecond or two late) is not
// counted as jank - only a frame that missed its slot outright.
const DROPPED_FRAME_THRESHOLD_MS = FRAME_BUDGET_MS * 1.5;

// requestAnimationFrame stops ticking while the app is backgrounded, so the first frame after it
// returns carries the whole suspended interval. That is not jank and must not enter the stats -
// an idle stretch once reported a 102-second "worst frame".
const SUSPENDED_FRAME_MS = 1_000;

// The rate is averaged over a window instead of published per frame: a setState at 60 Hz would
// itself dominate the very commit path this meter is supposed to observe.
const SAMPLE_WINDOW_MS = 500;

type IJsFrameRateMeterProps = {
  accent: string;
};

// What the engine's reconcile walk cost inside the last window, next to the frame numbers so the
// two can be read against each other: the walk is a term in every adapter's frame budget.
//
// Reported as two halves, never as `walkMs / nodesVisited`. Dirty-marking means the denominator
// counts only the nodes reconcile did NOT skip, while the numerator still covers everything it does
// (the JSI createNode/appendChild calls included), so that ratio inflates by the skip factor: 13.4
// us/node without dirty-marking, 438 us/node with it, on a device that had got ~2x faster. So
// `nodesPerCommit` is the skip itself (read against the screen's node count) and `msPerCommit` is
// what a commit costs. A true per-node figure needs a full walk - a cold mount, where nothing is
// skippable.
type IWalkSample = {
  sharePercent: number;
  nodesPerCommit: number;
  msPerCommit: number;
};

const EMPTY_WALK_SAMPLE: IWalkSample = {
  sharePercent: 0,
  nodesPerCommit: 0,
  msPerCommit: 0,
};

// `readCommitProfile()` is read-and-RESET, and this meter calls it once per window off rAF. A
// benchmark step that wants the profile of its OWN commit must stop the meter first: otherwise a
// window can close inside the step and consume the step's numbers, leaving a plausible zero and no
// sign that anything was lost.
//
// A mutable module field, not a prop. A prop change re-renders the meter, and that re-render is a
// commit landing inside the very window being measured — which would both perturb the duration and
// (because the screen's post-commit hook stops the clock on ANY commit) risk settling the step
// early against the wrong commit.
export const commitProfileGate = { isHeldByBenchmark: false };

/**
 * JS-thread frame rate. A requestAnimationFrame loop measures the delta between consecutive
 * frames, reports the averaged rate over a half-second window, and keeps a running count of
 * frames that arrived later than one and a half budgets - the visible cost of a long commit.
 */
export function JsFrameRateMeter({ accent }: IJsFrameRateMeterProps) {
  const [framesPerSecond, setFramesPerSecond] = useState(0);
  const [droppedFrames, setDroppedFrames] = useState(0);
  const [worstFrameMs, setWorstFrameMs] = useState(0);
  const [walk, setWalk] = useState<IWalkSample>(EMPTY_WALK_SAMPLE);
  const droppedRef = useRef(0);
  const worstRef = useRef(0);

  useEffect(() => {
    let previousFrameAt = performance.now();
    let windowStartedAt = previousFrameAt;
    let framesInWindow = 0;
    let handle = 0;
    let stopped = false;

    const onFrame = () => {
      if (stopped) return;
      const now = performance.now();
      const deltaMs = now - previousFrameAt;
      previousFrameAt = now;
      framesInWindow += 1;

      if (deltaMs < SUSPENDED_FRAME_MS) {
        if (deltaMs > DROPPED_FRAME_THRESHOLD_MS) droppedRef.current += 1;
        if (deltaMs > worstRef.current) worstRef.current = deltaMs;
      }

      const windowMs = now - windowStartedAt;
      // While a benchmark step holds the gate the whole window-close block is skipped, publish and
      // reset alike: the readCommitProfile() below would eat the step's profile, and the three
      // setStates would put an extra commit inside its measured window. The window simply grows and
      // publishes once, longer, after the step releases.
      if (
        windowMs >= SAMPLE_WINDOW_MS &&
        !commitProfileGate.isHeldByBenchmark
      ) {
        setFramesPerSecond(Math.round((framesInWindow * 1000) / windowMs));
        setDroppedFrames(droppedRef.current);
        setWorstFrameMs(worstRef.current);
        // Read-and-reset, once per window, so each sample covers exactly the window just closed
        // rather than an ever-growing total.
        const commitProfile = readCommitProfile();
        setWalk({
          sharePercent: (commitProfile.walkMs / windowMs) * 100,
          nodesPerCommit:
            commitProfile.commits === 0
              ? 0
              : commitProfile.nodesVisited / commitProfile.commits,
          msPerCommit:
            commitProfile.commits === 0
              ? 0
              : commitProfile.walkMs / commitProfile.commits,
        });
        framesInWindow = 0;
        windowStartedAt = now;
      }

      handle = requestAnimationFrame(onFrame);
    };

    handle = requestAnimationFrame(onFrame);
    return () => {
      stopped = true;
      cancelAnimationFrame(handle);
    };
  }, []);

  const onReset = () => {
    droppedRef.current = 0;
    worstRef.current = 0;
    setDroppedFrames(0);
    setWorstFrameMs(0);
    setWalk(EMPTY_WALK_SAMPLE);
  };

  return (
    <view className="bench-meter">
      <text className="section-label">JS-THREAD FRAME RATE</text>
      <view className="bench-meter-row">
        <view className="bench-metric">
          <text
            testID="bench-fps"
            className="bench-metric-value"
            style={{ color: accent }}
          >
            {String(framesPerSecond)}
          </text>
          <text className="bench-metric-label">fps</text>
        </view>
        <view className="bench-metric">
          <text
            testID="bench-dropped"
            className="bench-metric-value"
            style={{ color: accent }}
          >
            {String(droppedFrames)}
          </text>
          <text className="bench-metric-label">dropped</text>
        </view>
        <view className="bench-metric">
          <text className="bench-metric-value" style={{ color: accent }}>
            {worstFrameMs.toFixed(0)}
          </text>
          <text className="bench-metric-label">worst ms</text>
        </view>
      </view>
      <text className="section-label">ENGINE RECONCILE WALK</text>
      <view className="bench-meter-row">
        <view className="bench-metric">
          <text
            testID="bench-walk-share"
            className="bench-metric-value"
            style={{ color: accent }}
          >
            {walk.sharePercent.toFixed(1)}
          </text>
          <text className="bench-metric-label">% of window</text>
        </view>
        <view className="bench-metric">
          <text
            testID="bench-walk-nodes-per-commit"
            className="bench-metric-value"
            style={{ color: accent }}
          >
            {walk.nodesPerCommit.toFixed(0)}
          </text>
          <text className="bench-metric-label">nodes / commit</text>
        </view>
        <view className="bench-metric">
          <text
            testID="bench-walk-ms-per-commit"
            className="bench-metric-value"
            style={{ color: accent }}
          >
            {walk.msPerCommit.toFixed(1)}
          </text>
          <text className="bench-metric-label">ms / commit</text>
        </view>
      </view>
      <ActionButton
        testID="bench-fps-reset"
        title="Reset frame counters"
        onPress={onReset}
        color={accent}
      />
    </view>
  );
}
