// examples/vue-tsx/components/PlatformColorDemo.tsx
import { defineComponent } from 'vue';
import { DynamicColorIOS, Platform, PlatformColor, useColorScheme } from '@symbiote-native/vue';

// Names resolve on the native side and a wrong one silently falls back, so this is device-only.
// The opaque color objects stay dynamic: they are resolved at runtime
export const PlatformColorDemo = defineComponent({
  name: 'PlatformColorDemo',
  setup() {
    const scheme = useColorScheme();
    return () => (
      <view class="section-nested">
        <text class="section-label">
          {`PlatformColor · semantic + DynamicColorIOS (${scheme.value ?? 'unknown'})`}
        </text>
        <view class="row">
          <view
            class="color-tile"
            style={{ backgroundColor: PlatformColor('systemBlue', '@android:color/holo_blue_dark') }}
          >
            <text class="tile-label">systemBlue</text>
          </view>
          {/* DynamicColorIOS throws off iOS, as in RN */}
          {Platform.OS === 'ios' && (
            <view
              class="color-tile-bordered"
              style={{
                backgroundColor: DynamicColorIOS({ light: '#dcf3e8', dark: '#2c3e50' }),
                borderColor: PlatformColor('separator'),
              }}
            >
              <text class="bold-label" style={{ color: PlatformColor('label') }}>
                dynamic
              </text>
            </view>
          )}
        </view>
      </view>
    );
  },
});

// examples/react/components/PlatformColorDemo.tsx
import {
  useColorScheme,
  PlatformColor,
  DynamicColorIOS,
  Platform,
} from '@symbiote-native/react';

// PlatformColor / DynamicColorIOS resolve on the native side: 'systemBlue' / 'label'
// become iOS UIColor selectors, and the dynamic tuple flips with the system
// appearance. The opaque color objects flow through the same color seam as CSS
// strings (processColor), so no special handling reaches Fabric. Name resolution is
// device-only: a wrong name silently falls back, so this is verified on simulator.
export function PlatformColorDemo() {
  const scheme = useColorScheme();
  return (
    <view className="section-nested">
      <text className="section-label">
        {`PlatformColor · semantic + DynamicColorIOS (${scheme ?? 'unknown'})`}
      </text>
      <view className="row">
        <view
          className="color-tile"
          style={{
            backgroundColor: PlatformColor(
              'systemBlue',
              '@android:color/holo_blue_dark',
            ),
          }}
        >
          <text className="tile-label">systemBlue</text>
        </view>
        {/* DynamicColorIOS throws off iOS, as in RN */}
        {Platform.OS === 'ios' && (
          <view
            className="color-tile-bordered"
            style={{
              backgroundColor: DynamicColorIOS({
                light: '#dbeafe',
                dark: '#13243a',
              }),
              borderColor: PlatformColor('separator'),
            }}
          >
            <text
              className="bold-label"
              style={{ color: PlatformColor('label') }}
            >
              dynamic
            </text>
          </view>
        )}
      </view>
    </view>
  );
}
