// packages/cli/templates/styling/js/react/css-modules/App.jsx
import { useState } from 'react';
import styles from './App.module.css';

export default function App() {
  const [count, setCount] = useState(0);

  return (
    <safe-area-view className={styles['screen']}>
      <image
        className={styles['brand-logo']}
        resizeMode="contain"
        source={require('./assets/react-native-logo.png')}
      />
      <text className={styles['title']}>Welcome to SymbioteNative!</text>
      <text className={styles['subtitle']}>Framework-agnostic React Native, driven by React.</text>

      <view className={styles['counter-card']}>
        <text className={styles['counter-label']}>TAPS</text>
        <text className={styles['counter-value']}>{count}</text>
      </view>

      <pressable className={styles['button-primary']} onPress={() => setCount((value) => value + 1)}>
        <text className={styles['button-primary-text']}>Tap me</text>
      </pressable>
    </safe-area-view>
  );
}

// packages/cli/templates/styling/js/solid/css-modules/App.jsx
import { createSignal } from 'solid-js';
import styles from './App.module.css';

export default function App() {
  const [count, setCount] = createSignal(0);

  return (
    <safe-area-view class={styles['screen']}>
      <view class={styles['brand-row']}>
        <image
          class={`${styles['brand-logo']} ${styles['brand-logo-react']}`}
          resizeMode="contain"
          source={require('./assets/react-native-logo.png')}
        />
        <image
          class={styles['plus-icon']}
          resizeMode="contain"
          source={require('./assets/plus-icon.png')}
        />
        <image
          class={`${styles['brand-logo']} ${styles['brand-logo-solid']}`}
          resizeMode="contain"
          source={require('./assets/solid-logo.png')}
        />
      </view>
      <text class={styles['title']}>Welcome to SymbioteNative!</text>
      <text class={styles['subtitle']}>Framework-agnostic React Native, driven by Solid.</text>

      <view class={styles['counter-card']}>
        <text class={styles['counter-label']}>TAPS</text>
        <text class={styles['counter-value']}>{count()}</text>
      </view>

      <pressable class={styles['button-primary']} onPress={() => setCount((value) => value + 1)}>
        <text class={styles['button-primary-text']}>Tap me</text>
      </pressable>
    </safe-area-view>
  );
}
