// adapters/solid/src/primitives/create-event-value-hook.ts
// Every `useXStatus`-style primitive (`useAudioPlayerStatus`, `useAudioPlaylistStatus`, ...)
// binds this to its own event name + initial-value getter instead of repeating the effect wiring

import { createEffect, createSignal, onCleanup, type Accessor } from 'solid-js';
import type { IEventValueSource } from '@symbiote-native/engine';

export function createEventValueHook<
  TSource extends IEventValueSource<TValue, TEvent>,
  TValue,
  TEvent extends string = string,
>(event: TEvent, getValue: (source: TSource) => TValue) {
  return function useEventValue(
    getSource: Accessor<TSource>,
  ): Accessor<TValue> {
    const [value, setValue] = createSignal(getValue(getSource()));

    createEffect(() => {
      const source = getSource();
      setValue(() => getValue(source));
      const subscription = source.addListener(event, next =>
        setValue(() => next),
      );
      onCleanup(() => subscription.remove());
    });

    return value;
  };
}

// adapters/angular/src/services/create-event-value-hook.ts
// Every `useXStatus`-style `injectX` (`injectAudioPlayerStatus`, ...) binds this to its own
// event name + initial-value getter instead of repeating the signal/effect wiring

import { effect, signal, type Signal } from '@angular/core';
import type { IEventValueSource } from '@symbiote-native/engine';

export function createEventValueHook<
  TSource extends IEventValueSource<TValue, TEvent>,
  TValue,
  TEvent extends string = string,
>(event: TEvent, getValue: (source: TSource) => TValue) {
  return function injectValue(getSource: () => TSource): Signal<TValue> {
    const value = signal(getValue(getSource()));

    effect(onCleanup => {
      const source = getSource();
      value.set(getValue(source));
      const subscription = source.addListener(event, next => value.set(next));
      onCleanup(() => subscription.remove());
    });

    return value.asReadonly();
  };
}
