// adapters/svelte/src/components/input-accessory-view/index.svelte
<script lang="ts" module>
  // InputAccessoryView: render-only host assembly (iOS). Calls the shared
  // core/components/src/view/render-input-accessory-view.ts's renderInputAccessoryView()
  // directly (nativeID/backgroundColor/style -> the host node, everything else passthrough) —
  // the same calling convention as keyboard-avoiding-view/index.svelte's shared-render-fn call,
  // rather than hand-duplicating its prop-assembly logic (per the svelte-adapter-dom-shim
  // skill's §15/§19 correction: a fixed-shape Descriptor still has to be CALLED, not
  // re-derived). The root tag stays literal below since renderInputAccessoryView always paints
  // the same 'symbiote-input-accessory-view' host — no dynamic <svelte:element> needed. The
  // host has no structural children of its own; the user's children nest directly under it.
  import type { IInputAccessoryViewProps } from './input-accessory-view-props';

  export type { IInputAccessoryViewProps };
</script>

<script lang="ts">
  import {
    renderInputAccessoryView,
    resolveAccessibilityProps,
  } from '@symbiote-native/components';
  import { createAttachmentsSync } from '../../runes/attachments';
  import type { ShimElement } from '../../dom-shim';

  let {
    nativeID,
    backgroundColor,
    style,
    children,
    ...passthrough
  }: IInputAccessoryViewProps = $props();

  const descriptor = $derived(
    renderInputAccessoryView({
      nativeID,
      backgroundColor,
      style,
      passthrough: resolveAccessibilityProps(passthrough),
    }),
  );

  // See View.svelte's note on `{@attach}`.
  let hostShim = $state.raw<ShimElement | null>(null);
  const syncAttachments = createAttachmentsSync();
  $effect(() => {
    syncAttachments(hostShim, passthrough);
  });
</script>

<symbiote-input-accessory-view p={descriptor.props} bind:this={hostShim}>
  {@render children?.()}
</symbiote-input-accessory-view>

// adapters/react/src/components/input-accessory-view/index.ts
// InputAccessoryView: the React lifecycle half (iOS). The host-node assembly (nativeID /
// backgroundColor / style / accessibility forwarding) lives framework-agnostic in
// @symbiote-native/components/renderInputAccessoryView and is shared verbatim with Vue; here React only
// folds aria/role, bridges the Descriptor, and nests the user children under the host.

import { createElement, type FC, type ReactNode } from 'react';
import {
  renderInputAccessoryView,
  resolveAccessibilityProps,
  type IAccessibilityProps,
  type IAriaProps,
} from '@symbiote-native/components';
import type { IStyleProp, IViewStyle } from '../../utils/styles';

export interface IInputAccessoryViewProps
  extends IAccessibilityProps, IAriaProps {
  // The id a TextInput's inputAccessoryViewID points at to dock above its keyboard.
  nativeID?: string;
  backgroundColor?: string;
  style?: IStyleProp<IViewStyle>;
  // Not destructured below, so it lands in ...passthrough and forwards onto the host, which
  // already resolves className.
  className?: string;
  children?: ReactNode;
}

export const InputAccessoryView: FC<IInputAccessoryViewProps> = rawProps => {
  // Owns its host element (symbiote-input-accessory-view), so it folds aria/role here; the
  // resolved accessibility* surface rides the node via `...passthrough`.
  const { nativeID, backgroundColor, style, children, ...passthrough } =
    resolveAccessibilityProps(rawProps);
  const host = renderInputAccessoryView({
    nativeID,
    backgroundColor,
    style,
    passthrough,
  });
  // host has no structural children; the user children nest directly under it.
  return createElement(host.type, { key: host.key, ...host.props }, children);
};
