// packages/navigation/src/react/drawer.ts
// Drawer, the React lifecycle half. The open/closed + focused-route router (drawer-router-state)
// and the pure swipe/geometry math (drawer-options) live in @symbiote-native/navigation core,
// shared verbatim with the Vue/Angular adapters; here React supplies the lifecycle — useReducer
// for the router, a PanResponder for the swipe gesture (RN's own idiom: build it ONCE via
// useRef, let its callbacks read current values off refs rather than rebuilding it every render),
// an Animated.Value driving the slide/opacity transforms, and useImperativeHandle for the
// open/close/toggle/jumpTo handle — mirroring react/tabs.ts's shape (Tab is the closer sibling:
// both are fixed-route-list, no-react-native-screens navigators; Stack's push/pop + native-screen
// bridging don't apply here).
//
// FEASIBILITY NOTE (see the drawer skill / PR description for the full writeup): the REAL
// @react-navigation/drawer is built on react-native-gesture-handler + react-native-reanimated,
// neither of which this codebase depends on. What's built here reaches the same swipe-to-open/
// close + front/back/slide/permanent behavior using only PanResponder + Animated (both already in
// @symbiote-native/engine), which is sufficient for a solid drawer but NOT byte-for-byte parity —
// see the explicit gap list at the bottom of this file.

import {
  Children,
  createElement,
  forwardRef,
  isValidElement,
  useContext,
  useEffect,
  useId,
  useImperativeHandle,
  useMemo,
  useReducer,
  useRef,
} from 'react';
import type { ReactElement, ReactNode } from 'react';
import { Animated, PanResponder, useWindowDimensions } from '@symbiote-native/react';
import type { IPanResponderGestureState, ISymbioteEvent } from '@symbiote-native/react';
import type { IDescriptor } from '@symbiote-native/components';
import { dlog, type IStyleProp, type IViewStyle } from '@symbiote-native/engine';
import {
  DRAWER_DEFAULT_OVERLAY_COLOR,
  DRAWER_DEFAULT_SWIPE_ENABLED,
  NAVIGATION_EVENT_BLUR,
  NAVIGATION_EVENT_FOCUS,
  createInitialDrawerRouterState,
  createNavigationEmitter,
  drawerChildOrder,
  drawerRouterReducer,
  isDrawerAnimated,
  isHorizontalDrag,
  isSwipeStartInEdge,
  renderDrawer,
  resolveDrawerGeometry,
  resolveDrawerPosition,
  resolveDrawerWidth,
  resolveSwipeIntent,
} from '../core';
import type {
  IDrawerOptions,
  IDrawerRouterState,
  IDrawerScreenOptions,
  IDrawerSlot,
  IRoute,
} from '../core';
import { NavigationContext } from './navigation-context';
import { DrawerScreen } from './drawer-screen';
import type { IDrawerScreenComponentProps, IDrawerScreenProps } from './drawer-screen';

export type IDrawerNavigatorHandle = {
  openDrawer: () => void;
  closeDrawer: () => void;
  toggleDrawer: () => void;
  jumpTo: (name: string) => void;
};

// Keyed by route.key, mirroring @react-navigation/drawer's own `descriptors` prop shape — the
// options a caller's renderDrawerContent reads to label its menu entries (Drawer ships no
// built-in menu UI, matching react-native-drawer-layout's Drawer primitive; see this file's
// header).
export type IDrawerDescriptorMap = Record<
  string,
  { options: IDrawerScreenOptions; navigation: IDrawerNavigatorHandle }
>;

export type IDrawerProps = IDrawerOptions & {
  initialRouteName?: string;
  drawerStyle?: IStyleProp<IViewStyle>;
  renderDrawerContent?: (props: {
    state: IDrawerRouterState;
    descriptors: IDrawerDescriptorMap;
    navigation: IDrawerNavigatorHandle;
  }) => ReactNode;
  children?: ReactNode;
};

type IDrawerRegistryEntry = {
  component: IDrawerScreenProps['component'];
  options: IDrawerScreenProps['options'];
  initialParams: unknown;
};

function isDrawerScreenElement(
  child: ReactNode,
): child is ReturnType<typeof DrawerScreen> & { props: IDrawerScreenProps } {
  return isValidElement(child) && child.type === DrawerScreen;
}

function collectRegistry(children: ReactNode): Map<string, IDrawerRegistryEntry> {
  const registry = new Map<string, IDrawerRegistryEntry>();
  Children.forEach(children, child => {
    if (!isDrawerScreenElement(child)) return;
    registry.set(child.props.name, {
      component: child.props.component,
      options: child.props.options,
      initialParams: child.props.initialParams,
    });
  });
  return registry;
}

function resolveDrawerScreenOptions(
  entry: IDrawerRegistryEntry,
  screenComponentProps: IDrawerScreenComponentProps,
): IDrawerScreenOptions {
  if (typeof entry.options === 'function') return entry.options(screenComponentProps);
  return entry.options ?? {};
}

function clamp01(value: number): number {
  return Math.min(1, Math.max(0, value));
}

function isRecord(value: unknown): value is Record<string, unknown> {
  return typeof value === 'object' && value !== null;
}

function toFiniteNumber(value: unknown): number | undefined {
  return typeof value === 'number' && Number.isFinite(value) ? value : undefined;
}

// The touch's real starting page-X, read off the raw event rather than gestureState.x0:
// the engine's capture phase (core/engine/src/pan-responder/index.ts's
// onStartShouldSetResponderCapture/onMoveShouldSetResponderCapture) resets gestureState
// before the bubble-phase onStartShouldSetPanResponder/onMoveShouldSetPanResponder callbacks
// below run, so x0 is only populated later, inside onResponderGrant. Mirrors
// core/engine/src/events/index.ts's readTouchPoint: RN puts pageX on the event directly for
// a single touch, or on touches[0] for multi-touch.
function startPageXOf(event: ISymbioteEvent): number | undefined {
  const { nativeEvent } = event;
  const direct = toFiniteNumber(nativeEvent.pageX);
  if (direct !== undefined) return direct;
  const touches = nativeEvent.touches;
  if (Array.isArray(touches) && isRecord(touches[0])) return toFiniteNumber(touches[0].pageX);
  return undefined;
}

const DRAWER_SNAP_DURATION = 250;

const DrawerImpl = forwardRef<IDrawerNavigatorHandle, IDrawerProps>((props, forwardedRef) => {
  // Read BEFORE establishing this Drawer's own Context value below — becomes the `parent` link a
  // nested screen's useNavigation().getParent() walks (e.g. this Drawer rendered as a Stack
  // screen's content reaches that Stack via this value). undefined when this Drawer is the
  // nesting root.
  const ambientContext = useContext(NavigationContext);
  const {
    initialRouteName,
    renderDrawerContent,
    children,
    drawerStyle,
    drawerType,
    drawerPosition,
    drawerWidth,
    overlayColor,
    swipeEnabled,
    swipeEdgeWidth,
    swipeMinDistance,
    swipeMinVelocity,
  } = props;

  const options: IDrawerOptions = {
    drawerType,
    drawerPosition,
    drawerWidth,
    overlayColor,
    swipeEnabled,
    swipeEdgeWidth,
    swipeMinDistance,
    swipeMinVelocity,
  };

  const registry = useMemo(() => collectRegistry(children), [children]);
  const routeIdPrefix = useId();

  const routes = useMemo<IRoute<unknown>[]>(
    () =>
      Array.from(registry.entries()).map(([name, entry]) => ({
        key: `${routeIdPrefix}-${name}`,
        name,
        params: entry.initialParams,
      })),
    [registry, routeIdPrefix],
  );

  const [state, dispatch] = useReducer(drawerRouterReducer, undefined, () =>
    createInitialDrawerRouterState(routes, initialRouteName),
  );

  if (routes.length === 0) dlog('Drawer: no <Drawer.Screen> children registered');

  const { width: screenWidth } = useWindowDimensions();

  // progress: 0 closed -> 1 open, the single Animated.Value every slide/opacity transform below
  // interpolates from.
  const progress = useRef(new Animated.Value(state.isOpen ? 1 : 0)).current;
  // Where a drag STARTS from, in progress units. Always exactly 0 or 1: a gesture only ever
  // begins at rest, since terminate/release always snap the value back to a resting state before
  // another grant can fire.
  const dragStartProgress = useRef(0);

  // Refs so the PanResponder's callbacks — built ONCE below, RN's own idiom — always read the
  // CURRENT render's values without forcing a new PanResponder identity on every state/prop
  // change (recreating panHandlers mid-gesture would drop the in-flight touch).
  const optionsRef = useRef(options);
  optionsRef.current = options;
  const screenWidthRef = useRef(screenWidth);
  screenWidthRef.current = screenWidth;
  const isOpenRef = useRef(state.isOpen);
  isOpenRef.current = state.isOpen;

  function animateProgressTo(open: boolean): void {
    // Investigation instrumentation (Drawer openDrawer-no-op / toggleDrawer-no-animation bug):
    // every imperative caller (openDrawer/closeDrawer/toggleDrawer/jumpTo) funnels through here,
    // so this single seam proves whether Animated.timing is actually being started at all, and
    // with what toValue — a live-only failure (e.g. a stale progress ref, or Animated.timing
    // silently short-circuiting) would show up as this log firing with no visible motion. Kept
    // behind DEBUG per <keep_logs_gate_behind_DEBUG>, never removed.
    dlog(`Drawer: animateProgressTo(open=${open}) starting at t=${Date.now()}`);
    Animated.timing(progress, {
      toValue: open ? 1 : 0,
      duration: DRAWER_SNAP_DURATION,
      // Native-driver wiring (the AnimatedComponent passthrough opt-in ADR 0017 defines) is
      // deferred for v1 — see this file's header feasibility note. The JS timing loop still
      // drives every frame, same as any other non-native-driven Animated.timing in this codebase.
      useNativeDriver: false,
    }).start();
  }

  const handle: IDrawerNavigatorHandle = {
    openDrawer: () => {
      dlog(`Drawer: openDrawer() called, isOpen=${isOpenRef.current} at t=${Date.now()}`);
      animateProgressTo(true);
      dispatch({ type: 'openDrawer' });
    },
    closeDrawer: () => {
      dlog(`Drawer: closeDrawer() called, isOpen=${isOpenRef.current} at t=${Date.now()}`);
      animateProgressTo(false);
      dispatch({ type: 'closeDrawer' });
    },
    toggleDrawer: () => {
      dlog(`Drawer: toggleDrawer() called, isOpen=${isOpenRef.current} at t=${Date.now()}`);
      animateProgressTo(!isOpenRef.current);
      dispatch({ type: 'toggleDrawer' });
    },
    jumpTo: (name: string) => {
      dispatch({ type: 'jumpTo', name });
      if (isOpenRef.current) animateProgressTo(false);
    },
  };

  useImperativeHandle(forwardedRef, () => handle);

  const panResponder = useRef(
    PanResponder.create({
      onStartShouldSetPanResponder: (
        event: ISymbioteEvent,
        gestureState: IPanResponderGestureState,
      ): boolean => {
        const currentOptions = optionsRef.current;
        if ((currentOptions.swipeEnabled ?? DRAWER_DEFAULT_SWIPE_ENABLED) === false) return false;
        if (!isDrawerAnimated(currentOptions)) return false;
        return isSwipeStartInEdge(
          startPageXOf(event) ?? gestureState.x0,
          screenWidthRef.current,
          isOpenRef.current,
          currentOptions,
        );
      },
      onMoveShouldSetPanResponder: (
        event: ISymbioteEvent,
        gestureState: IPanResponderGestureState,
      ): boolean => {
        const currentOptions = optionsRef.current;
        if ((currentOptions.swipeEnabled ?? DRAWER_DEFAULT_SWIPE_ENABLED) === false) return false;
        if (!isDrawerAnimated(currentOptions)) return false;
        if (
          !isSwipeStartInEdge(
            startPageXOf(event) ?? gestureState.x0,
            screenWidthRef.current,
            isOpenRef.current,
            currentOptions,
          )
        ) {
          return false;
        }
        return isHorizontalDrag(gestureState);
      },
      onPanResponderGrant: (): void => {
        dlog('Drawer: gesture grant');
        dragStartProgress.current = isOpenRef.current ? 1 : 0;
      },
      onPanResponderMove: (
        _event: ISymbioteEvent,
        gestureState: IPanResponderGestureState,
      ): void => {
        const currentOptions = optionsRef.current;
        const width = resolveDrawerWidth(currentOptions);
        const sign = resolveDrawerPosition(currentOptions) === 'right' ? -1 : 1;
        const delta = (sign * gestureState.dx) / width;
        progress.setValue(clamp01(dragStartProgress.current + delta));
      },
      onPanResponderRelease: (
        _event: ISymbioteEvent,
        gestureState: IPanResponderGestureState,
      ): void => {
        const intent = resolveSwipeIntent(gestureState, isOpenRef.current, optionsRef.current);
        const open = intent === 'open';
        dlog(`Drawer: gesture release -> ${open ? 'open' : 'close'}`);
        animateProgressTo(open);
        dispatch(open ? { type: 'openDrawer' } : { type: 'closeDrawer' });
      },
      onPanResponderTerminate: (): void => {
        dlog('Drawer: gesture terminated, snapping back');
        animateProgressTo(isOpenRef.current);
      },
    }),
  ).current;

  const animated = isDrawerAnimated(options);
  const geometry = useMemo(
    () => resolveDrawerGeometry(options),
    [options.drawerType, options.drawerPosition, options.drawerWidth],
  );

  const panelTranslateX = animated
    ? progress.interpolate({
        inputRange: [0, 1],
        outputRange: [geometry.panelTranslateXClosed, geometry.panelTranslateXOpen],
      })
    : undefined;
  const contentTranslateX = animated
    ? progress.interpolate({
        inputRange: [0, 1],
        outputRange: [geometry.contentTranslateXClosed, geometry.contentTranslateXOpen],
      })
    : undefined;
  const overlayOpacity = animated
    ? progress.interpolate({
        inputRange: [0, 1],
        outputRange: [geometry.overlayOpacityClosed, geometry.overlayOpacityOpen],
      })
    : undefined;
  // The overlay is a full-screen absolutely-positioned sibling BELOW content in paint order
  // (see render-drawer.ts's drawerChildOrder) — for 'front' that's fine since content never moves,
  // but for 'slide' content itself translates away by contentTranslateX, and without following it
  // the overlay stays pinned full-screen, dimming (and touch-capturing) the now-revealed panel
  // underneath instead of just the content sliver it's meant to dim. Tying overlay to the SAME
  // translateX as content keeps it registered exactly under content, wherever content actually is.
  const overlayTranslateX = animated
    ? progress.interpolate({
        inputRange: [0, 1],
        outputRange: [geometry.contentTranslateXClosed, geometry.contentTranslateXOpen],
      })
    : undefined;

  const focusedRoute = state.routes[state.index];
  const focusedEntry = focusedRoute ? registry.get(focusedRoute.name) : undefined;
  if (focusedRoute && !focusedEntry) {
    dlog(`Drawer: no screen registered for route name "${focusedRoute.name}"`);
  }

  // Only the focused route's screen is ever mounted (like Tab, unlike Stack which keeps every
  // pushed route alive), so a fresh emitter per focus change is sufficient — see tabs.ts's
  // matching comment for why no per-route emitter map is needed. Keyed on the route KEY, not the
  // route object, so a jumpTo-with-no-params re-focus of the ALREADY-focused route (a no-op in
  // drawerRouterReducer) and any future params merge don't spuriously re-fire focus/blur.
  const focusedRouteKey = focusedRoute?.key;
  const routeEmitter = useMemo(() => createNavigationEmitter(), [focusedRouteKey]);

  // Drawer paints its own panel in pure JS — there is no native onAppear/onDisappear to hook
  // (unlike Stack's RNSScreen), so focus/blur is synthesized here: emit 'focus' once the
  // newly-focused route's content has mounted, 'blur' when it's about to be replaced or the
  // Drawer itself unmounts.
  useEffect(() => {
    if (focusedRouteKey === undefined) return undefined;
    dlog(`Drawer: route "${focusedRoute?.name}" focused`);
    routeEmitter.emit(NAVIGATION_EVENT_FOCUS);
    return () => {
      dlog(`Drawer: route "${focusedRoute?.name}" blurred`);
      routeEmitter.emit(NAVIGATION_EVENT_BLUR);
    };
    // focusedRoute omitted deliberately: only its .key (tracked via focusedRouteKey) should
    // re-run this effect — see the comment above on focusedRouteKey.
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [routeEmitter, focusedRouteKey]);

  const content =
    focusedEntry && focusedRoute
      ? createElement(
          NavigationContext.Provider,
          {
            value: {
              route: focusedRoute,
              navigation: handle,
              emitter: routeEmitter,
              parent: ambientContext,
            },
          },
          createElement(focusedEntry.component, { route: focusedRoute, navigation: handle }),
        )
      : null;

  const descriptors: IDrawerDescriptorMap = {};
  for (const route of state.routes) {
    const entry = registry.get(route.name);
    if (entry === undefined) continue;
    descriptors[route.key] = {
      options: resolveDrawerScreenOptions(entry, { route, navigation: handle }),
      navigation: handle,
    };
  }

  const drawerContent = renderDrawerContent?.({ state, descriptors, navigation: handle }) ?? null;

  const root = renderDrawer(
    {
      overlayColor: overlayColor ?? DRAWER_DEFAULT_OVERLAY_COLOR,
      drawerStyle,
      contentPassthrough: {},
      overlayPassthrough: animated
        ? {
            pointerEvents: state.isOpen ? 'auto' : 'none',
            onStartShouldSetResponder: () => true,
            onResponderRelease: () => {
              animateProgressTo(false);
              dispatch({ type: 'closeDrawer' });
            },
          }
        : {},
      panelPassthrough: {},
    },
    options,
  );

  const order = drawerChildOrder(options);
  const slots = new Map<IDrawerSlot, IDescriptor>();
  order.forEach((slot, index) => {
    const descriptor = root.children[index];
    if (typeof descriptor !== 'string') slots.set(slot, descriptor);
  });

  const slotChildren: Record<IDrawerSlot, ReactNode> = {
    content,
    overlay: null,
    panel: drawerContent,
  };
  // Each animated style holds an AnimatedInterpolation node, not a plain number/color — it feeds
  // only Animated.View's deliberately permissive `style?: unknown` (see create-animated-component.tsx),
  // never the plain-IViewStyle branch below, so this stays untyped rather than widening IViewStyle.
  const slotAnimatedStyle: Record<IDrawerSlot, unknown> = {
    content:
      contentTranslateX === undefined
        ? undefined
        : { transform: [{ translateX: contentTranslateX }] },
    overlay:
      overlayOpacity === undefined
        ? undefined
        : { opacity: overlayOpacity, transform: [{ translateX: overlayTranslateX }] },
    panel:
      panelTranslateX === undefined ? undefined : { transform: [{ translateX: panelTranslateX }] },
  };

  function renderSlot(slot: IDrawerSlot): ReactElement | null {
    const descriptor = slots.get(slot);
    if (descriptor === undefined) return null;
    const animatedStyle = slotAnimatedStyle[slot];
    if (animatedStyle === undefined) {
      return createElement(
        descriptor.type,
        { key: descriptor.key, ...descriptor.props },
        slotChildren[slot],
      );
    }
    const style = [descriptor.props.style, animatedStyle];
    return createElement(
      Animated.View,
      { key: descriptor.key, ...descriptor.props, style },
      slotChildren[slot],
    );
  }

  const drawerChildren = order
    .map(renderSlot)
    .filter((element): element is ReactElement => element !== null);

  return createElement(
    'symbiote-view',
    { style: root.props.style, ...panResponder.panHandlers },
    ...drawerChildren,
  );
});

export const Drawer = Object.assign(DrawerImpl, { Screen: DrawerScreen });

// --- Explicit gap list vs the real react-native-gesture-handler + react-native-reanimated
// @react-navigation/drawer (confirmed against its current docs) ---
// 1. `configureGestureHandler` — a raw react-native-gesture-handler `Gesture` object escape
//    hatch. No PanResponder equivalent exists; not ported.
// 2. Simultaneous/failure gesture RELATIONSHIPS (gesture-handler's declarative composition vs a
//    nested ScrollView, another PanResponder, etc.) — PanResponder only offers negotiation via the
//    should-set boolean gates used here (edge-start + dominant-axis), which is more prone to an
//    accidental hijack of a nested horizontal ScrollView/Swiper than gesture-handler's system.
// 3. `useDrawerProgress` — a Reanimated SharedValue read on the UI thread. `progress` here is a
//    JS-thread AnimatedValue; interpolating it for consumer-facing content animation works, but
//    without native-driver wiring (gap noted above) it does not carry the same synchronous
//    UI-thread guarantee under JS-thread load.
// 4. `hideStatusBarOnOpen` / `keyboardDismissMode` / `statusBarAnimation` / `overlayStyle` — not
//    wired in this pass; straightforward additions once StatusBar/Keyboard module wiring is
//    needed here (not a PanResponder/Animated limitation, just unscoped for v1).

// packages/navigation/src/svelte/drawer/index.svelte
<script lang="ts" module>
  // Drawer, the Svelte lifecycle half. The open/closed + focused-route router
  // (drawer-router-state) and the pure swipe/geometry math (drawer-options) live in
  // @symbiote-native/navigation core, shared verbatim with the React/Vue/Angular entries; here
  // Svelte supplies the lifecycle - `$state.raw` for the router (its twin of useReducer), a
  // PanResponder for the swipe gesture (built ONCE, its callbacks reading options and open-state
  // LIVE off `$props()`/`$state` at gesture time), an AnimatedValue driving the slide/opacity
  // transforms, and `export function`s for the open/close/toggle/jumpTo handle - mirroring
  // tabs/index.svelte's shape (Tab is the closer sibling: both are fixed-route-list,
  // no-react-native-screens navigators; Stack's push/pop + native-screen bridging don't apply).
  //
  // FEASIBILITY NOTE (mirrored from the React/Vue twins): the REAL @react-navigation/drawer is
  // built on react-native-gesture-handler + react-native-reanimated, neither of which this
  // codebase depends on. What's built here reaches the same swipe-to-open/close +
  // front/back/slide/permanent behavior using only PanResponder + Animated (both already in
  // @symbiote-native/engine), which is sufficient for a solid drawer but NOT byte-for-byte parity
  // - see the explicit gap list at the bottom of this file (verbatim from the React twin - the
  // gaps are architectural, not adapter-specific).
  let drawerInstanceCounter = 0;

  const DRAWER_SNAP_DURATION = 250;
</script>

<script lang="ts">
  import type { Component } from 'svelte';
  import { onDestroy, tick } from 'svelte';
  import { AnimatedValue, Dimensions, PanResponder, dlog, timing } from '@symbiote-native/engine';
  import type { IPanResponderGestureState, ISymbioteEvent } from '@symbiote-native/engine';
  // The ONLY import from the adapter's main barrel: `Animated.View` is a compiled `.svelte`
  // component, so unlike PanResponder/Dimensions/AnimatedValue (pure engine re-exports, taken
  // from the engine directly here) it has no `.svelte`-free home to import from.
  import { Animated } from '@symbiote-native/svelte';
  import {
    DRAWER_DEFAULT_OVERLAY_COLOR,
    NAVIGATION_EVENT_BLUR,
    NAVIGATION_EVENT_FOCUS,
    createInitialDrawerRouterState,
    createNavigationEmitter,
    diffFocusedRoute,
    drawerChildOrder,
    drawerRouterReducer,
    isDrawerAnimated,
    renderDrawer,
    resolveDragProgress,
    resolveDrawerGeometry,
    resolveDrawerSlotInterpolation,
    resolveSwipeIntent,
    shouldClaimDrawerSwipe,
  } from '../../core';
  import type {
    IDescriptor,
    IDrawerDescriptorMap,
    IDrawerNavigatorHandle,
    IDrawerOptions,
    IDrawerRouterAction,
    IDrawerRouterState,
    IDrawerScreenOptions,
    IDrawerSlot,
    INavigationEmitter,
    IRoute,
  } from '../../core';
  import { getNavigationScope } from '../navigation-context';
  import type { INavigationScopeValue } from '../navigation-context';
  import NavigationScope from '../navigation-scope.svelte';
  import { SCREEN_REGISTRY_HOST_PROPS } from '../registry-host';
  import { setScreenCollector, toRegistry, withoutScreen } from '../screen-registry';
  import type { IRegisteredScreen } from '../screen-registry';
  import type { IDrawerScreenProps } from '../drawer-screen-props';
  import type { IDrawerProps } from './drawer-props';

  let {
    initialRouteName,
    drawerStyle,
    drawerType,
    drawerPosition,
    drawerWidth,
    overlayColor,
    swipeEnabled,
    swipeEdgeWidth,
    swipeMinDistance,
    swipeMinVelocity,
    children,
    drawerContent,
  }: IDrawerProps = $props();

  // Read BEFORE this Drawer establishes its own per-screen NavigationScope - becomes the `parent`
  // link a nested screen's useNavigation().getParent() walks. undefined at the nesting root.
  const parentScope = getNavigationScope();

  const routeIdPrefix = `drawer-${(drawerInstanceCounter += 1)}`;

  // Unlike Vue (which reads everything off untyped `attrs` and needs a per-field guard to get
  // back into the typed core surface), Svelte's `$props()` is already typed by IDrawerProps, so
  // this is a plain re-assembly with no narrowing at all.
  const options = $derived<IDrawerOptions>({
    drawerType,
    drawerPosition,
    drawerWidth,
    overlayColor,
    swipeEnabled,
    swipeEdgeWidth,
    swipeMinDistance,
    swipeMinVelocity,
  });

  let screens = $state.raw<IRegisteredScreen<IDrawerScreenProps['options']>[]>([]);
  setScreenCollector<IDrawerScreenProps['options']>({
    kind: 'drawer',
    register: screen => {
      screens = [...screens, screen];
    },
    unregister: screen => {
      screens = withoutScreen(screens, screen);
    },
  });

  const registry = $derived(toRegistry(screens));

  // Same seed-once-then-dispatch shape Stack and Tab use.
  let dispatchedState = $state.raw<IDrawerRouterState | null>(null);
  let seededState: IDrawerRouterState | undefined;
  let routeSequence = 0;

  function seedState(): IDrawerRouterState {
    if (seededState !== undefined) return seededState;
    const routes: IRoute<unknown>[] = [...registry.entries()].map(([name, entry]) => {
      routeSequence += 1;
      return { key: `${routeIdPrefix}-${name}-${routeSequence}`, name, params: entry.initialParams };
    });
    if (routes.length === 0) {
      dlog('Drawer: no <Drawer.Screen> children registered');
      // Deliberately not memoized - markers may still be registering.
      return createInitialDrawerRouterState(routes, initialRouteName);
    }
    seededState = createInitialDrawerRouterState(routes, initialRouteName);
    return seededState;
  }

  const state = $derived(dispatchedState ?? seedState());

  function dispatch(action: IDrawerRouterAction): void {
    dispatchedState = drawerRouterReducer(state, action);
  }

  // progress: 0 closed -> 1 open, the single AnimatedValue every slide/opacity transform below
  // interpolates from. A plain `const`: a Svelte component's script runs once, so this needs no
  // re-creation guard the way React's useRef(new Animated.Value(...)).current does.
  const progress = new AnimatedValue(state.isOpen ? 1 : 0);
  // Where a drag STARTS from, in progress units. Always exactly 0 or 1: a gesture only ever
  // begins at rest, since terminate/release always snap the value back to a resting state before
  // another grant can fire.
  let dragStartProgress = 0;

  function animateProgressTo(open: boolean): void {
    dlog(`Drawer: animateProgressTo(open=${open}) starting at t=${Date.now()}`);
    timing(progress, {
      toValue: open ? 1 : 0,
      duration: DRAWER_SNAP_DURATION,
      // Native-driver wiring is deferred for v1 - see this file's header feasibility note. The
      // JS timing loop still drives every frame, same as any other non-native-driven timing in
      // this codebase.
      useNativeDriver: false,
    }).start();
  }

  export function openDrawer(): void {
    dlog(`Drawer: openDrawer() called, isOpen=${state.isOpen} at t=${Date.now()}`);
    animateProgressTo(true);
    dispatch({ type: 'openDrawer' });
  }
  export function closeDrawer(): void {
    dlog(`Drawer: closeDrawer() called, isOpen=${state.isOpen} at t=${Date.now()}`);
    animateProgressTo(false);
    dispatch({ type: 'closeDrawer' });
  }
  export function toggleDrawer(): void {
    dlog(`Drawer: toggleDrawer() called, isOpen=${state.isOpen} at t=${Date.now()}`);
    animateProgressTo(!state.isOpen);
    dispatch({ type: 'toggleDrawer' });
  }
  export function jumpTo(name: string): void {
    // Captured BEFORE dispatch: `state` is recomputed synchronously from the reassigned
    // `dispatchedState`, so reading it after would already see the reducer's own isOpen: false.
    const wasOpen = state.isOpen;
    dispatch({ type: 'jumpTo', name });
    if (wasOpen) animateProgressTo(false);
  }

  const handle: IDrawerNavigatorHandle = { openDrawer, closeDrawer, toggleDrawer, jumpTo };

  // The window width is read fresh AT GESTURE TIME rather than through a reactive
  // window-dimensions rune: it is only ever consumed inside these PanResponder callbacks (never
  // rendered), so a live `Dimensions.get` is both simpler and strictly more current than a
  // subscription that has to round-trip a re-render first.
  const panResponder = PanResponder.create({
    onStartShouldSetPanResponder: (
      event: ISymbioteEvent,
      gestureState: IPanResponderGestureState,
    ): boolean =>
      shouldClaimDrawerSwipe(
        event,
        gestureState,
        Dimensions.get('window').width,
        state.isOpen,
        options,
        'start',
      ),
    onMoveShouldSetPanResponder: (
      event: ISymbioteEvent,
      gestureState: IPanResponderGestureState,
    ): boolean =>
      shouldClaimDrawerSwipe(
        event,
        gestureState,
        Dimensions.get('window').width,
        state.isOpen,
        options,
        'move',
      ),
    onPanResponderGrant: (): void => {
      dlog('Drawer: gesture grant');
      dragStartProgress = state.isOpen ? 1 : 0;
    },
    onPanResponderMove: (_event: ISymbioteEvent, gestureState: IPanResponderGestureState): void => {
      progress.setValue(resolveDragProgress(gestureState, dragStartProgress, options));
    },
    onPanResponderRelease: (
      _event: ISymbioteEvent,
      gestureState: IPanResponderGestureState,
    ): void => {
      const intent = resolveSwipeIntent(gestureState, state.isOpen, options);
      const open = intent === 'open';
      dlog(`Drawer: gesture release -> ${open ? 'open' : 'close'}`);
      animateProgressTo(open);
      dispatch(open ? { type: 'openDrawer' } : { type: 'closeDrawer' });
    },
    onPanResponderTerminate: (): void => {
      dlog('Drawer: gesture terminated, snapping back');
      animateProgressTo(state.isOpen);
    },
  });

  // Only the focused route's screen is ever mounted (like Tab, unlike Stack which keeps every
  // pushed route alive). One emitter per route.key, created lazily and cached for the navigator's
  // whole lifetime.
  const emitters = new Map<string, INavigationEmitter>();
  function emitterFor(routeKey: string): INavigationEmitter {
    let emitter = emitters.get(routeKey);
    if (emitter === undefined) {
      emitter = createNavigationEmitter();
      emitters.set(routeKey, emitter);
    }
    return emitter;
  }

  // Focus/blur synthesis, deferred to `tick()` for the same reason tabs/index.svelte documents:
  // the newly-focused screen's own subscriptions are created during THIS flush, after this
  // effect was.
  let previousFocusedKey: string | undefined;
  $effect(() => {
    const nextKey = state.routes[state.index]?.key;
    const { blurKey, focusKey } = diffFocusedRoute(previousFocusedKey, nextKey);
    if (blurKey === undefined && focusKey === undefined) return;
    previousFocusedKey = nextKey;
    void tick().then(() => {
      if (blurKey !== undefined) {
        dlog(`Drawer: route "${blurKey}" blurred at t=${Date.now()}`);
        emitterFor(blurKey).emit(NAVIGATION_EVENT_BLUR);
      }
      if (focusKey !== undefined) {
        dlog(`Drawer: route "${focusKey}" focused at t=${Date.now()}`);
        emitterFor(focusKey).emit(NAVIGATION_EVENT_FOCUS);
      }
    });
  });

  onDestroy(() => {
    if (previousFocusedKey !== undefined) {
      emitterFor(previousFocusedKey).emit(NAVIGATION_EVENT_BLUR);
    }
  });

  const animated = $derived(isDrawerAnimated(options));
  const geometry = $derived(resolveDrawerGeometry(options));

  const panelTranslateX = $derived(
    animated
      ? progress.interpolate(resolveDrawerSlotInterpolation(geometry, 'panel').translateX)
      : undefined,
  );
  const contentTranslateX = $derived(
    animated
      ? progress.interpolate(resolveDrawerSlotInterpolation(geometry, 'content').translateX)
      : undefined,
  );
  // The overlay is a full-screen absolutely-positioned sibling BELOW content in paint order (see
  // render-drawer.ts's drawerChildOrder) - for 'front' that's fine since content never moves, but
  // for 'slide' content itself translates away by contentTranslateX, and without following it the
  // overlay stays pinned full-screen. resolveDrawerSlotInterpolation's 'overlay' branch ties its
  // translateX to the SAME range as content's for exactly this reason, so overlayOpacity and
  // overlayTranslateX below share one resolved config.
  const overlayInterpolation = $derived(
    animated ? resolveDrawerSlotInterpolation(geometry, 'overlay') : undefined,
  );
  const overlayStyle = $derived(
    overlayInterpolation === undefined
      ? undefined
      : {
          opacity: progress.interpolate(overlayInterpolation.opacity),
          transform: [{ translateX: progress.interpolate(overlayInterpolation.translateX) }],
        },
  );
  const contentStyle = $derived(
    contentTranslateX === undefined ? undefined : { transform: [{ translateX: contentTranslateX }] },
  );
  const panelStyle = $derived(
    panelTranslateX === undefined ? undefined : { transform: [{ translateX: panelTranslateX }] },
  );

  const focusedRoute = $derived(state.routes[state.index]);
  const focusedScreen = $derived.by<
    { scope: INavigationScopeValue; component: Component } | undefined
  >(() => {
    if (focusedRoute === undefined) return undefined;
    const entry = registry.get(focusedRoute.name);
    if (entry === undefined) {
      dlog(`Drawer: no screen registered for route name "${focusedRoute.name}"`);
      return undefined;
    }
    return {
      component: entry.component,
      scope: {
        route: focusedRoute,
        navigation: handle,
        emitter: emitterFor(focusedRoute.key),
        parent: parentScope?.current,
      },
    };
  });

  function resolveDrawerScreenOptions(
    entry: IRegisteredScreen<IDrawerScreenProps['options']>,
    route: IRoute<unknown>,
  ): IDrawerScreenOptions {
    if (typeof entry.options === 'function') return entry.options({ route, navigation: handle });
    return entry.options ?? {};
  }

  const descriptors = $derived.by<IDrawerDescriptorMap>(() => {
    const map: IDrawerDescriptorMap = {};
    for (const route of state.routes) {
      const entry = registry.get(route.name);
      if (entry === undefined) continue;
      map[route.key] = { options: resolveDrawerScreenOptions(entry, route), navigation: handle };
    }
    return map;
  });

  const root = $derived.by<IDescriptor>(() =>
    renderDrawer(
      {
        overlayColor: overlayColor ?? DRAWER_DEFAULT_OVERLAY_COLOR,
        drawerStyle,
        contentPassthrough: {},
        overlayPassthrough: animated
          ? {
              pointerEvents: state.isOpen ? 'auto' : 'none',
              onStartShouldSetResponder: () => true,
              onResponderRelease: () => {
                animateProgressTo(false);
                dispatch({ type: 'closeDrawer' });
              },
            }
          : {},
        panelPassthrough: {},
      },
      options,
    ),
  );

  const order = $derived(drawerChildOrder(options));

  // renderDrawer emits its slots as root children IN `drawerChildOrder`'s order, so the two zip
  // together - the same index-pairing Vue's own render loop does.
  const slotDescriptors = $derived.by<Partial<Record<IDrawerSlot, IDescriptor>>>(() => {
    const map: Partial<Record<IDrawerSlot, IDescriptor>> = {};
    order.forEach((slot, index) => {
      const descriptor = root.children[index];
      if (typeof descriptor !== 'string' && descriptor !== undefined) map[slot] = descriptor;
    });
    return map;
  });

  const rootProps = $derived<Record<string, unknown>>({
    style: root.props.style,
    ...panResponder.panHandlers,
  });
</script>

{#snippet screenContent()}{#if focusedScreen !== undefined}{@const FocusedComponent = focusedScreen.component}<NavigationScope value={focusedScreen.scope}><FocusedComponent /></NavigationScope>{/if}{/snippet}{#snippet contentSlot()}{@const descriptor = slotDescriptors.content}{#if descriptor !== undefined}{#if contentStyle !== undefined}<Animated.View {...descriptor.props} style={[descriptor.props.style, contentStyle]}>{@render screenContent()}</Animated.View>{:else}<symbiote-view p={descriptor.props}>{@render screenContent()}</symbiote-view>{/if}{/if}{/snippet}{#snippet overlaySlot()}{@const descriptor = slotDescriptors.overlay}{#if descriptor !== undefined}{#if overlayStyle !== undefined}<Animated.View {...descriptor.props} style={[descriptor.props.style, overlayStyle]} />{:else}<symbiote-view p={descriptor.props} />{/if}{/if}{/snippet}{#snippet panelSlot()}{@const descriptor = slotDescriptors.panel}{#if descriptor !== undefined}{#if panelStyle !== undefined}<Animated.View {...descriptor.props} style={[descriptor.props.style, panelStyle]}>{@render drawerContent?.({ state, descriptors, navigation: handle })}</Animated.View>{:else}<symbiote-view p={descriptor.props}>{@render drawerContent?.({ state, descriptors, navigation: handle })}</symbiote-view>{/if}{/if}{/snippet}<symbiote-view p={rootProps}><symbiote-text p={SCREEN_REGISTRY_HOST_PROPS}>{@render children?.()}</symbiote-text>{#each order as slot (slot)}{#if slot === 'content'}{@render contentSlot()}{:else if slot === 'overlay'}{@render overlaySlot()}{:else}{@render panelSlot()}{/if}{/each}</symbiote-view>

<!-- --- Explicit gap list vs the real react-native-gesture-handler + react-native-reanimated
     @react-navigation/drawer (confirmed against its current docs, mirrored verbatim from the
     React twin - the gaps are architectural, not adapter-specific) ---
     1. `configureGestureHandler` - a raw react-native-gesture-handler `Gesture` object escape
        hatch. No PanResponder equivalent exists; not ported.
     2. Simultaneous/failure gesture RELATIONSHIPS (gesture-handler's declarative composition vs
        a nested ScrollView, another PanResponder, etc.) - PanResponder only offers negotiation
        via the should-set boolean gates used here (edge-start + dominant-axis), which is more
        prone to an accidental hijack of a nested horizontal ScrollView/Swiper than
        gesture-handler's system.
     3. `useDrawerProgress` - a Reanimated SharedValue read on the UI thread. `progress` here is a
        JS-thread AnimatedValue; interpolating it for consumer-facing content animation works, but
        without native-driver wiring (gap noted above) it does not carry the same synchronous
        UI-thread guarantee under JS-thread load.
     4. `hideStatusBarOnOpen` / `keyboardDismissMode` / `statusBarAnimation` / `overlayStyle` -
        not wired in this pass; straightforward additions once StatusBar/Keyboard module wiring is
        needed here (not a PanResponder/Animated limitation, just unscoped for v1). -->
