// examples/expo-angular/src/screens/LocationWatchRow.ts
import { Component, DestroyRef, inject, input, signal } from '@angular/core';
import type { ILocationSubscription } from '@symbiote-native/location/angular';
import { ResultRow } from '../components/ResultRow';
import { ToggleRow } from '../components/ToggleRow';

@Component({
  selector: 'LocationWatchRow',
  standalone: true,
  imports: [ResultRow, ToggleRow],
  template: `
    <ToggleRow
      [testID]="prefix() + '-switch'"
      [label]="label()"
      [value]="isOn()"
      (valueChange)="toggle($event)"
      [color]="color()"
    />
    <ResultRow
      [testID]="prefix() + '-output'"
      label="latest"
      [value]="output()"
    />
  `,
})
export class LocationWatchRow<T> {
  readonly prefix = input.required<string>();
  readonly label = input.required<string>();
  readonly color = input.required<string>();
  readonly start =
    input.required<
      (
        onValue: (value: T) => void,
        onError: (reason: string) => void,
      ) => Promise<ILocationSubscription>
    >();
  readonly format = input.required<(value: T) => string>();

  readonly isOn = signal(false);
  readonly output = signal('not watching');
  private subscription: ILocationSubscription | null = null;

  constructor() {
    inject(DestroyRef).onDestroy(() => this.subscription?.remove());
  }

  toggle(next: boolean): void {
    if (!next) {
      this.subscription?.remove();
      this.subscription = null;
      this.isOn.set(false);
      return;
    }
    this.start()(
      value => this.output.set(this.format()(value)),
      reason => this.output.set(`error: ${reason}`),
    )
      .then(sub => {
        this.subscription = sub;
        this.isOn.set(true);
      })
      .catch((error: Error) => this.output.set(`failed: ${error.message}`));
  }
}

// examples/expo-svelte/screens/LocationWatchRow.svelte
<script lang="ts" generics="T">
  import type { ILocationSubscription } from '@symbiote-native/location/svelte';
  import ResultRow from '../components/ResultRow.svelte';
  import ToggleRow from '../components/ToggleRow.svelte';

  let {
    prefix,
    label,
    color,
    start,
    format,
  }: {
    prefix: string;
    label: string;
    color: string;
    start: (
      onValue: (value: T) => void,
      onError: (reason: string) => void,
    ) => Promise<ILocationSubscription>;
    format: (value: T) => string;
  } = $props();

  let isOn = $state(false);
  let output = $state('not watching');
  let subscription: ILocationSubscription | null = null;

  $effect(() => () => subscription?.remove());

  function toggle(next: boolean): void {
    if (!next) {
      subscription?.remove();
      subscription = null;
      isOn = false;
      return;
    }
    start(
      value => {
        output = format(value);
      },
      reason => {
        output = `error: ${reason}`;
      },
    )
      .then(sub => {
        subscription = sub;
        isOn = true;
      })
      .catch((error: Error) => {
        output = `failed: ${error.message}`;
      });
  }
</script>

<ToggleRow testID={`${prefix}-switch`} {label} value={isOn} onChange={toggle} {color} />
<ResultRow testID={`${prefix}-output`} label="latest" value={output} />
