// examples/react/screens/ApiPlaygroundScreen.tsx
import { SafeAreaView, ScrollView, Text, View } from '@symbiote-native/react';
import { ROUTE_NAME } from '../routes';
import { LINE_COLOR, ROUTE_LINE_INFO } from '../navigation-lines';
import { HooksStateContextDemo } from '../components/HooksStateContextDemo';
import { HooksRefEffectDemo } from '../components/HooksRefEffectDemo';
import { HooksPerformanceDemo } from '../components/HooksPerformanceDemo';
import { HooksMiscDemo } from '../components/HooksMiscDemo';
import { HooksActionsDemo } from '../components/HooksActionsDemo';
import { FragmentProfilerStrictModeDemo } from '../components/FragmentProfilerStrictModeDemo';
import { MemoForwardRefDemo } from '../components/MemoForwardRefDemo';
import { SuspenseActivityLazyDemo } from '../components/SuspenseActivityLazyDemo';
import { ContextProviderDemo } from '../components/ContextProviderDemo';
import { RefsApiDemo } from '../components/RefsApiDemo';
import { ElementsApiDemo } from '../components/ElementsApiDemo';
import { ChildrenApiDemo } from '../components/ChildrenApiDemo';
import { ClassLifecycleDemo } from '../components/ClassLifecycleDemo';
import { PureComponentDemo } from '../components/PureComponentDemo';
import { ErrorBoundaryDemo } from '../components/ErrorBoundaryDemo';
import { PortalDemo } from '../components/PortalDemo';
import { OtherApisDemo } from '../components/OtherApisDemo';

/**
 * API Playground: live-demos React's OWN idiomatic API surface (hooks, Suspense, Context, refs,
 * error boundaries, portals…) running under Symbiote's custom react-reconciler host config —
 * not RN-shaped equivalents. Every section below tracks one `##` category from
 * .docs/framework-api-surface/react.md; a Partial row's caveat renders inline via CaveatNote
 * instead of pretending the gap doesn't exist. Distinct from HooksDemoScreen, which exercises
 * @symbiote-native/navigation's OWN hooks (useFocusEffect/useIsFocused/useNavigationState) — the
 * only overlap is useState/useCallback appearing incidentally in both, which is not this
 * screen's concern.
 */
export function ApiPlaygroundScreen() {
  const lineInfo = ROUTE_LINE_INFO[ROUTE_NAME.ApiPlayground];

  return (
    <SafeAreaView className="screen">
      <ScrollView
        testID="api-playground-scroll"
        className="screen"
        contentContainerStyle="scroll-content"
      >
        <View className={`line-tag line-tag-${lineInfo.line}`}>
          <Text className="line-tag-text">{`${lineInfo.code} · ${lineInfo.label}`}</Text>
        </View>
        <View className="hero-card">
          <View
            className="hero-badge"
            style={{ backgroundColor: LINE_COLOR.introspection }}
          >
            <Text className="hero-badge-text">AP</Text>
          </View>
          <View className="hero-copy">
            <Text className="hero-title">API Playground</Text>
            <Text className="hero-body">
              React's own API surface, live — hooks, built-in components, the
              component model, and the handful of top-level APIs that still
              apply with react-dom out of the picture.
            </Text>
          </View>
        </View>

        <Text className="category-header">Hooks</Text>
        <Text className="category-intro">
          State, context, refs, effects, performance, and the newer
          resource/action hooks.
        </Text>
        <HooksStateContextDemo />
        <HooksRefEffectDemo />
        <HooksPerformanceDemo />
        <HooksMiscDemo />
        <HooksActionsDemo />

        <Text className="category-header">Built-in Components</Text>
        <Text className="category-intro">
          Fragment, Profiler, StrictMode, memo/forwardRef/lazy, and the two
          Partial rows — Suspense and Activity — whose hide/unhide is currently
          a no-op.
        </Text>
        <FragmentProfilerStrictModeDemo />
        <MemoForwardRefDemo />
        <SuspenseActivityLazyDemo />

        <Text className="category-header">Component Model</Text>
        <Text className="category-intro">
          Context, refs, the Elements/Children APIs, class components end to
          end, PureComponent, Error Boundaries, and createPortal.
        </Text>
        <ContextProviderDemo />
        <RefsApiDemo />
        <ElementsApiDemo />
        <ChildrenApiDemo />
        <ClassLifecycleDemo />
        <PureComponentDemo />
        <ErrorBoundaryDemo />
        <PortalDemo />

        <Text className="category-header">Other</Text>
        <Text className="category-intro">
          The remaining top-level APIs that still apply with no react-dom in the
          picture.
        </Text>
        <OtherApisDemo />
      </ScrollView>
    </SafeAreaView>
  );
}

// examples/svelte/screens/ApiPlaygroundScreen.svelte
<script lang="ts">
  // API Playground: live demos of Svelte 5's own idiomatic API surface (runes, template syntax,
  // bindings, snippets, stores, context, lifecycle) running under Symbiote's custom renderer — the
  // exact, already-triaged checklist is .docs/framework-api-surface/svelte.md. Sections below
  // mirror that document's `##` categories in order; each section component's own header comment
  // records exactly which rows it covers and why any row is skipped.
  //
  // Whitespace in this markup is free, unlike when the screen was written. The shim maps a
  // whitespace-only text node under a parent that takes no raw text to an anchor, so a gap
  // between siblings never reaches Fabric as an RCTRawText (svelte-adapter-dom-shim §16b), and
  // svelte.config.js's collapseTextWhitespace() folds a sentence wrapped across source lines.
  import {
    SafeAreaView,
    ScrollView,
    Text,
    View,
  } from '@symbiote-native/svelte';
  import { ROUTE_NAME } from '../routes';
  import { LINE_COLOR, ROUTE_LINE_INFO } from '../navigation-lines';
  import RunesDemo from '../components/api-playground/RunesDemo.svelte';
  import TemplateSyntaxDemo from '../components/api-playground/TemplateSyntaxDemo.svelte';
  import BindingsDemo from '../components/api-playground/BindingsDemo.svelte';
  import EventsActionsDemo from '../components/api-playground/EventsActionsDemo.svelte';
  import CompositionDemo from '../components/api-playground/CompositionDemo.svelte';
  import StoresDemo from '../components/api-playground/StoresDemo.svelte';
  import SpecialElementsDemo from '../components/api-playground/SpecialElementsDemo.svelte';
  import LifecycleDemo from '../components/api-playground/LifecycleDemo.svelte';

  const lineInfo = ROUTE_LINE_INFO[ROUTE_NAME.ApiPlayground];
  const accent = LINE_COLOR.primitives;
</script>

<SafeAreaView class="screen">
  <ScrollView
    testID="api-playground-scroll"
    class="screen"
    contentContainerStyle="scroll-content"
  >
    <View class={`line-tag line-tag-${lineInfo.line}`}>
      <Text class="line-tag-text">
        {`${lineInfo.code} · ${lineInfo.label}`}
      </Text>
    </View>
    <View class="hero-card">
      <View class="hero-badge" style={{ backgroundColor: accent }}>
        <Text class="hero-badge-text">{lineInfo.code}</Text>
      </View>
      <View class="hero-copy">
        <Text class="hero-title">API Playground</Text>
        <Text class="hero-body">
          Svelte 5's own runes, template syntax, bindings, stores, context and
          lifecycle — running live under Symbiote's custom renderer.
        </Text>
      </View>
    </View>
    <RunesDemo />
    <TemplateSyntaxDemo />
    <BindingsDemo />
    <EventsActionsDemo />
    <CompositionDemo>
      {#snippet header()}
        <Text class="note-text">
          this section's `header` is a NAMED snippet prop, supplied by
          ApiPlaygroundScreen.svelte
        </Text>
      {/snippet}
      <Text class="list-row-text">
        this line is CompositionDemo's default `children` snippet — also
        supplied by ApiPlaygroundScreen.svelte
      </Text>
    </CompositionDemo>
    <StoresDemo />
    <SpecialElementsDemo />
    <LifecycleDemo />
    <View class="section-nested">
      <Text class="section-label">Legacy reactivity (Svelte 4 style)</Text>
      <Text class="note-text">
        No, across the board — top-level `let` reactivity, `$:` reactive
        statements and `export let` props are all disallowed in runes mode,
        which every component on this screen (and this whole adapter) uses
        exclusively; `$state`/`$derived`/`$effect`/`$props()` replace them.
      </Text>
    </View>
  </ScrollView>
</SafeAreaView>
