// adapters/svelte/src/modules/status-bar/index.svelte
<script lang="ts">
  // StatusBar, the Svelte lifecycle half. The native StatusBarManager driving
  // (applyStatusBarProps), the imperative statics, and the Android bar-height constant all
  // live in @symbiote-native/engine, shared verbatim with React/Vue; Metro selects the
  // engine's status-bar.ios.ts / status-bar.android.ts per host, so the platform divergence
  // never reaches this file. Svelte supplies only the declarative shape: a component that
  // renders no Fabric view (empty template) and re-applies the props through an `$effect` on
  // mount + every prop change — the Svelte twin of Vue's watchEffect / React's useEffect.
  //
  // Unlike Vue's twin (status-bar.ts), no untyped-attrs guard layer is needed: Svelte's
  // `$props()` already destructures real typed fields straight from the compiler, so there is
  // no kebab-case-attrs normalization step to run first.
  import {
    applyStatusBarProps,
    type IStatusBarProps,
  } from '@symbiote-native/engine';

  let props: IStatusBarProps = $props();

  $effect(() => {
    applyStatusBarProps(props);
  });
</script>

// adapters/angular/src/modules/status-bar.ts
// StatusBar, the Angular lifecycle half. The native StatusBarManager driving, the imperative
// statics, and the Android bar-height constant all live in @symbiote/engine, shared verbatim with
// React and Vue; Metro selects the engine's platform variant. Angular supplies only the
// declarative shape: a component that renders nothing and re-applies the props through
// ngOnChanges on mount + every prop change. Imperative statics are attached to the component
// object the same way RN does.

import { Component, Input, type OnChanges, type SimpleChanges } from '@angular/core';
import {
  applyStatusBarProps,
  statusBarImperative,
  statusBarCurrentHeight,
  type IColorValue,
  type IStatusBarProps,
  type IStatusBarStyle,
} from '@symbiote/engine';

export type { IStatusBarProps, IStatusBarStyle } from '@symbiote/engine';

@Component({
  selector: 'StatusBar',
  standalone: true,
  template: '',
})
class StatusBarComponent implements OnChanges {
  @Input() barStyle?: IStatusBarStyle;
  @Input() hidden?: boolean;
  @Input() animated?: boolean;
  @Input() networkActivityIndicatorVisible?: boolean;
  @Input() backgroundColor?: IColorValue;
  @Input() translucent?: boolean;

  ngOnChanges(_changes: SimpleChanges): void {
    applyStatusBarProps(this.buildProps());
  }

  private buildProps(): IStatusBarProps {
    return {
      barStyle: this.barStyle,
      hidden: this.hidden,
      animated: this.animated,
      networkActivityIndicatorVisible: this.networkActivityIndicatorVisible,
      backgroundColor: this.backgroundColor,
      translucent: this.translucent,
    };
  }
}

const StatusBarWithStatics = Object.assign(StatusBarComponent, statusBarImperative);

Object.defineProperty(StatusBarWithStatics, 'currentHeight', {
  get: statusBarCurrentHeight,
  enumerable: true,
});

export const StatusBar: typeof StatusBarWithStatics & { readonly currentHeight?: number } =
  StatusBarWithStatics;
